/* Curated resources for the System Design roadmap.
   Every video id below was verified against YouTube's oEmbed API: the title and
   channel are the ones YouTube returned. Generated by tools/build_sd_resources.py. */
window.sdResources = {
 "lessons": {
  "requirements-scope.md": {
   "videos": [],
   "docs": [
    [
     "AlgoMaster — How to answer a system design question",
     "https://algomaster.io/learn/system-design-interviews/answering-framework"
    ],
    [
     "Hello Interview — System design in a hurry: requirements",
     "https://www.hellointerview.com/learn/system-design/in-a-hurry/delivery"
    ],
    [
     "System Design Primer — Step 1: outline use cases and constraints",
     "https://github.com/donnemartin/system-design-primer#step-1-outline-use-cases-constraints-and-assumptions"
    ]
   ]
  },
  "capacity-estimation.md": {
   "videos": [],
   "docs": [
    [
     "Latency numbers every programmer should know",
     "https://gist.github.com/jboner/2841832"
    ],
    [
     "Interactive latency numbers (by year)",
     "https://colin-scott.github.io/personal_website/research/interactive_latency.html"
    ],
    [
     "System Design Primer — Back-of-the-envelope calculations",
     "https://github.com/donnemartin/system-design-primer#back-of-the-envelope-calculations"
    ]
   ]
  },
  "architecture-diagrams-communication.md": {
   "videos": [],
   "docs": [
    [
     "The C4 model for software architecture",
     "https://c4model.com/"
    ],
    [
     "Martin Fowler — Software architecture guide",
     "https://martinfowler.com/architecture/"
    ],
    [
     "AWS architecture icons and diagram conventions",
     "https://aws.amazon.com/architecture/icons/"
    ]
   ]
  },
  "5-step-interview-framework.md": {
   "videos": [],
   "docs": [
    [
     "AlgoMaster — Answering framework",
     "https://algomaster.io/learn/system-design-interviews/answering-framework"
    ],
    [
     "Hello Interview — System design in a hurry",
     "https://www.hellointerview.com/learn/system-design/in-a-hurry/introduction"
    ],
    [
     "System Design Primer — How to approach a system design interview",
     "https://github.com/donnemartin/system-design-primer#how-to-approach-a-system-design-interview-question"
    ]
   ]
  },
  "senior-engineer-signals.md": {
   "videos": [],
   "docs": [
    [
     "Google SRE Book — Embracing risk",
     "https://sre.google/sre-book/embracing-risk/"
    ],
    [
     "AWS Builders' Library — Challenges with distributed systems",
     "https://aws.amazon.com/builders-library/challenges-with-distributed-systems/"
    ],
    [
     "Martin Fowler — Architectural trade-offs (Software Architecture Guide)",
     "https://martinfowler.com/architecture/"
    ]
   ]
  },
  "reference-numbers-estimation-cheat-sheet.md": {
   "videos": [],
   "docs": [
    [
     "Latency numbers every programmer should know",
     "https://gist.github.com/jboner/2841832"
    ],
    [
     "Interactive latency numbers (by year)",
     "https://colin-scott.github.io/personal_website/research/interactive_latency.html"
    ],
    [
     "AlgoMaster — Latency vs throughput vs bandwidth",
     "https://algomaster.io/learn/system-design/latency-vs-throughput"
    ]
   ]
  },
  "latency-throughput-scalability-basics.md": {
   "videos": [],
   "docs": [
    [
     "AlgoMaster — Scalability",
     "https://algomaster.io/learn/system-design/scalability"
    ],
    [
     "AlgoMaster — Vertical vs horizontal scaling",
     "https://algomaster.io/learn/system-design/vertical-vs-horizontal-scaling"
    ],
    [
     "AWS — Throughput vs latency",
     "https://aws.amazon.com/compare/the-difference-between-throughput-and-latency/"
    ],
    [
     "Universal Scalability Law (Gunther)",
     "https://en.wikipedia.org/wiki/Neil_J._Gunther#Universal_Law_of_Computational_Scalability"
    ]
   ]
  },
  "availability-reliability-slas.md": {
   "videos": [],
   "docs": [
    [
     "AlgoMaster — Availability",
     "https://algomaster.io/learn/system-design/availability"
    ],
    [
     "Google SRE Book — Service level objectives",
     "https://sre.google/sre-book/service-level-objectives/"
    ],
    [
     "Cockroach Labs — What is fault tolerance?",
     "https://www.cockroachlabs.com/blog/what-is-fault-tolerance/"
    ],
    [
     "AlgoMaster — Single point of failure",
     "https://algomaster.io/learn/system-design/single-point-of-failure-spof"
    ]
   ]
  },
  "consistency-models.md": {
   "videos": [
    [
     "LAsMrghdFP0",
     "Eventual Consistency vs. Strong Consistency — how to decide",
     "Think Software"
    ]
   ],
   "docs": [
    [
     "Jepsen — Consistency models map",
     "https://jepsen.io/consistency"
    ],
    [
     "AlgoMaster — Strong vs eventual consistency",
     "https://blog.algomaster.io/p/strong-vs-eventual-consistency"
    ],
    [
     "Kleppmann — Linearizability vs serializability",
     "https://www.bailis.org/blog/linearizability-versus-serializability/"
    ]
   ]
  },
  "cap-pacelc-theorems.md": {
   "videos": [],
   "docs": [
    [
     "CAP theorem revisited (Robert Greiner)",
     "https://robertgreiner.com/cap-theorem-revisited/"
    ],
    [
     "The CAP FAQ (Henry Robinson)",
     "https://github.com/henryr/cap-faq"
    ],
    [
     "AlgoMaster — CAP theorem",
     "https://algomaster.io/learn/system-design/cap-theorem"
    ],
    [
     "PACELC theorem",
     "https://en.wikipedia.org/wiki/PACELC_theorem"
    ]
   ]
  },
  "http-tls-protocol-fundamentals.md": {
   "videos": [],
   "docs": [
    [
     "High Performance Browser Networking (free book)",
     "https://hpbn.co/"
    ],
    [
     "Cloudflare — What is SSL/TLS?",
     "https://www.cloudflare.com/learning/ssl/what-is-ssl/"
    ],
    [
     "MDN — HTTP overview",
     "https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview"
    ],
    [
     "AlgoMaster — TCP vs UDP",
     "https://algomaster.io/learn/system-design/tcp-vs-udp"
    ]
   ]
  },
  "api-styles-rest-graphql-grpc.md": {
   "videos": [],
   "docs": [
    [
     "AlgoMaster — REST vs GraphQL",
     "https://blog.algomaster.io/p/rest-vs-graphql"
    ],
    [
     "gRPC — Introduction and core concepts",
     "https://grpc.io/docs/what-is-grpc/introduction/"
    ],
    [
     "GraphQL — Learn",
     "https://graphql.org/learn/"
    ],
    [
     "Google API design guide",
     "https://cloud.google.com/apis/design"
    ]
   ]
  },
  "dns-load-balancers-traffic-routing.md": {
   "videos": [
    [
     "YM_dEeXmnuY",
     "Load Balancers: Algorithms and Design",
     "Gaurav Sen"
    ]
   ],
   "docs": [
    [
     "AlgoMaster — How DNS actually works",
     "https://blog.algomaster.io/p/how-dns-actually-works"
    ],
    [
     "AlgoMaster — Load balancing algorithms explained with code",
     "https://blog.algomaster.io/p/load-balancing-algorithms-explained-with-code"
    ],
    [
     "NGINX — Inside NGINX: designed for performance and scale",
     "https://www.nginx.com/blog/inside-nginx-how-we-designed-for-performance-scale/"
    ],
    [
     "Google SRE Book — Load balancing at the datacenter",
     "https://sre.google/sre-book/load-balancing-datacenter/"
    ]
   ]
  },
  "proxies-api-gateways-service-mesh.md": {
   "videos": [],
   "docs": [
    [
     "AlgoMaster — Proxy vs reverse proxy",
     "https://blog.algomaster.io/p/proxy-vs-reverse-proxy-explained"
    ],
    [
     "AlgoMaster — What is an API gateway?",
     "https://blog.algomaster.io/p/what-is-an-api-gateway"
    ],
    [
     "microservices.io — API gateway pattern",
     "https://microservices.io/patterns/apigateway.html"
    ],
    [
     "Istio — What is a service mesh?",
     "https://istio.io/latest/about/service-mesh/"
    ]
   ]
  },
  "rate-limiting-algorithms.md": {
   "videos": [
    [
     "mhUQe4BKZXs",
     "Rate Limiting system design — token bucket, leaky bucket, sliding logs",
     "Tech Dummies - Narendra Lakshmana Gowda"
    ]
   ],
   "docs": [
    [
     "AlgoMaster — Rate limiting algorithms explained with code",
     "https://blog.algomaster.io/p/rate-limiting-algorithms-explained-with-code"
    ],
    [
     "Cloudflare — How we built rate limiting (sliding window)",
     "https://blog.cloudflare.com/counting-things-a-lot-of-different-things/"
    ],
    [
     "Stripe — Scaling your API with rate limiters",
     "https://stripe.com/blog/rate-limiters"
    ]
   ]
  },
  "real-time-communication-polling-sse-websockets-webrtc.md": {
   "videos": [
    [
     "1cFyfT0m3bA",
     "HTTP Long Polling vs Server Sent Events vs WebSockets",
     "Tech Primers"
    ]
   ],
   "docs": [
    [
     "AlgoMaster — Long polling vs WebSockets",
     "https://blog.algomaster.io/p/long-polling-vs-websockets"
    ],
    [
     "MDN — Using server-sent events",
     "https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events"
    ],
    [
     "MDN — WebSockets API",
     "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API"
    ],
    [
     "WebRTC — Getting started",
     "https://webrtc.org/getting-started/overview"
    ]
   ]
  },
  "storage-types-block-object-file.md": {
   "videos": [],
   "docs": [
    [
     "AWS — Block vs file vs object storage",
     "https://aws.amazon.com/compare/the-difference-between-block-file-object-storage/"
    ],
    [
     "Amazon S3 — How S3 works",
     "https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html"
    ],
    [
     "The Google File System (paper)",
     "https://static.googleusercontent.com/media/research.google.com/en//archive/gfs-sosp2003.pdf"
    ]
   ]
  },
  "sql-vs-nosql-decision-framework.md": {
   "videos": [],
   "docs": [
    [
     "AlgoMaster — SQL vs NoSQL",
     "https://algomaster.io/learn/system-design/sql-vs-nosql"
    ],
    [
     "AlgoMaster — 15 types of databases",
     "https://blog.algomaster.io/p/15-types-of-databases"
    ],
    [
     "MongoDB — Data modelling introduction",
     "https://www.mongodb.com/docs/manual/data-modeling/"
    ],
    [
     "System Design Primer — SQL or NoSQL",
     "https://github.com/donnemartin/system-design-primer#sql-or-nosql"
    ]
   ]
  },
  "acid-transactions-isolation.md": {
   "videos": [],
   "docs": [
    [
     "PostgreSQL — Transaction isolation levels",
     "https://www.postgresql.org/docs/current/transaction-iso.html"
    ],
    [
     "AlgoMaster — ACID transactions",
     "https://algomaster.io/learn/system-design/acid-transactions"
    ],
    [
     "Jepsen — Consistency and isolation models",
     "https://jepsen.io/consistency"
    ],
    [
     "A critique of ANSI SQL isolation levels (paper)",
     "https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/tr-95-51.pdf"
    ]
   ]
  },
  "indexes-query-optimization.md": {
   "videos": [],
   "docs": [
    [
     "Use The Index, Luke! — SQL indexing and tuning",
     "https://use-the-index-luke.com/"
    ],
    [
     "PostgreSQL — Indexes",
     "https://www.postgresql.org/docs/current/indexes.html"
    ],
    [
     "AlgoMaster — Database indexing",
     "https://algomaster.io/learn/system-design/indexing"
    ],
    [
     "MySQL — Slow query log",
     "https://dev.mysql.com/doc/refman/8.0/en/slow-query-log.html"
    ]
   ]
  },
  "replication-read-scaling.md": {
   "videos": [],
   "docs": [
    [
     "MySQL — Replication",
     "https://dev.mysql.com/doc/refman/8.0/en/replication.html"
    ],
    [
     "AlgoMaster — How to scale a database",
     "https://blog.algomaster.io/p/system-design-how-to-scale-a-database"
    ],
    [
     "PostgreSQL — High availability and replication",
     "https://www.postgresql.org/docs/current/high-availability.html"
    ]
   ]
  },
  "partitioning-sharding-data-distribution.md": {
   "videos": [
    [
     "L521gizea4s",
     "Sharding in System Design Interviews (w/ Meta Staff Engineer)",
     "Hello Interview"
    ]
   ],
   "docs": [
    [
     "AlgoMaster — Database sharding",
     "https://algomaster.io/learn/system-design/sharding"
    ],
    [
     "MongoDB — Sharding",
     "https://www.mongodb.com/docs/manual/sharding/"
    ],
    [
     "Vitess — Horizontal sharding concepts",
     "https://vitess.io/docs/concepts/shard/"
    ]
   ]
  },
  "consistent-hashing-rebalancing.md": {
   "videos": [
    [
     "UF9Iqmg94tk",
     "Consistent Hashing | Algorithms You Should Know #1",
     "ByteByteGo"
    ],
    [
     "zaRkONvyGr8",
     "What is CONSISTENT HASHING and where is it used?",
     "Gaurav Sen"
    ]
   ],
   "docs": [
    [
     "AlgoMaster — Consistent hashing",
     "https://algomaster.io/learn/system-design/consistent-hashing"
    ],
    [
     "The magic of consistent hashing",
     "http://www.paperplanes.de/2011/12/9/the-magic-of-consistent-hashing.html"
    ],
    [
     "Dynamo: Amazon's highly available key-value store (paper)",
     "https://www.allthingsdistributed.com/files/amazon-dynamo-sosp2007.pdf"
    ]
   ]
  },
  "nosql-internals.md": {
   "videos": [],
   "docs": [
    [
     "The Log-Structured Merge-Tree (LSM-tree) paper",
     "https://www.cs.umb.edu/~poneil/lsmtree.pdf"
    ],
    [
     "Bigtable: a distributed storage system (paper)",
     "https://static.googleusercontent.com/media/research.google.com/en//archive/bigtable-osdi06.pdf"
    ],
    [
     "AlgoMaster — Bloom filters",
     "https://algomaster.io/learn/system-design/bloom-filters"
    ],
    [
     "Cassandra — Storage engine and architecture",
     "https://cassandra.apache.org/doc/latest/cassandra/architecture/storage-engine.html"
    ]
   ]
  },
  "cache-strategies.md": {
   "videos": [],
   "docs": [
    [
     "AlgoMaster — Caching strategies",
     "https://algomaster.io/learn/system-design/caching-strategies"
    ],
    [
     "AWS Builders' Library — Caching challenges and strategies",
     "https://aws.amazon.com/builders-library/caching-challenges-and-strategies/"
    ],
    [
     "AlgoMaster — Read-through vs write-through cache",
     "https://blog.algomaster.io/p/59cae60d-9717-4e20-a59e-759e370db4e5"
    ]
   ]
  },
  "cache-eviction-ttl-invalidation.md": {
   "videos": [],
   "docs": [
    [
     "AlgoMaster — 7 cache eviction strategies",
     "https://blog.algomaster.io/p/7-cache-eviction-strategies"
    ],
    [
     "Cache replacement policies",
     "https://en.wikipedia.org/wiki/Cache_replacement_policies"
    ],
    [
     "Redis — Key eviction policies",
     "https://redis.io/docs/latest/develop/reference/eviction/"
    ]
   ]
  },
  "cache-failure-modes-pitfalls.md": {
   "videos": [],
   "docs": [
    [
     "AWS Builders' Library — Caching challenges and strategies",
     "https://aws.amazon.com/builders-library/caching-challenges-and-strategies/"
    ],
    [
     "Facebook — Scaling Memcache at Facebook (paper)",
     "https://www.usenix.org/system/files/conference/nsdi13/nsdi13-final170_update.pdf"
    ],
    [
     "Cache stampede",
     "https://en.wikipedia.org/wiki/Cache_stampede"
    ]
   ]
  },
  "redis-distributed-caching.md": {
   "videos": [],
   "docs": [
    [
     "AlgoMaster — Distributed caching",
     "https://blog.algomaster.io/p/distributed-caching"
    ],
    [
     "Redis — Data types and when to use them",
     "https://redis.io/docs/latest/develop/data-types/"
    ],
    [
     "Redis — Distributed locks with Redlock",
     "https://redis.io/docs/latest/develop/clients/patterns/distributed-locks/"
    ],
    [
     "Redis — Cluster specification",
     "https://redis.io/docs/latest/operate/oss_and_stack/reference/cluster-spec/"
    ]
   ]
  },
  "cdn-caching.md": {
   "videos": [
    [
     "8zX0rue2Hic",
     "System Design: Content Delivery Networks (simplified)",
     "Gaurav Sen"
    ]
   ],
   "docs": [
    [
     "Cloudflare — What is a CDN?",
     "https://www.cloudflare.com/learning/cdn/what-is-a-cdn/"
    ],
    [
     "Push vs pull CDNs",
     "https://www.geeksforgeeks.org/system-design/pull-cdn-vs-push-cdn/"
    ],
    [
     "MDN — HTTP caching",
     "https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching"
    ]
   ]
  },
  "edge-delivery-global-acceleration.md": {
   "videos": [],
   "docs": [
    [
     "Cloudflare — What is edge computing?",
     "https://www.cloudflare.com/learning/serverless/glossary/what-is-edge-computing/"
    ],
    [
     "AWS — Global Accelerator: how it works",
     "https://docs.aws.amazon.com/global-accelerator/latest/dg/introduction-how-it-works.html"
    ],
    [
     "Cloudflare — Anycast network",
     "https://www.cloudflare.com/learning/cdn/glossary/anycast-network/"
    ]
   ]
  },
  "message-queues-vs-event-streams.md": {
   "videos": [
    [
     "iJLL-KPqBpM",
     "System Design Interview — Distributed Message Queue",
     "System Design Interview"
    ]
   ],
   "docs": [
    [
     "AlgoMaster — Message queues",
     "https://algomaster.io/learn/system-design/message-queues"
    ],
    [
     "Confluent — Event streaming vs message queues",
     "https://www.confluent.io/learn/event-streaming/"
    ],
    [
     "AWS — Amazon SQS dead-letter queues",
     "https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html"
    ]
   ]
  },
  "kafka-architecture.md": {
   "videos": [
    [
     "2pioVWPblXs",
     "Apache Kafka Architecture: overview of Kafka's internal components",
     "Confluent"
    ]
   ],
   "docs": [
    [
     "Kafka — Design (official docs)",
     "https://kafka.apache.org/documentation/#design"
    ],
    [
     "Kafka: a distributed messaging system for log processing (paper)",
     "https://notes.stephenholiday.com/Kafka.pdf"
    ],
    [
     "Confluent — Kafka internals course",
     "https://developer.confluent.io/courses/architecture/get-started/"
    ]
   ]
  },
  "delivery-semantics-reliability.md": {
   "videos": [],
   "docs": [
    [
     "Confluent — Exactly-once semantics in Kafka",
     "https://www.confluent.io/blog/exactly-once-semantics-are-possible-heres-how-apache-kafka-does-it/"
    ],
    [
     "AWS Builders' Library — Timeouts, retries and backoff with jitter",
     "https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/"
    ],
    [
     "AlgoMaster — Idempotency",
     "https://algomaster.io/learn/system-design/idempotency"
    ]
   ]
  },
  "event-driven-architecture.md": {
   "videos": [],
   "docs": [
    [
     "Martin Fowler — What do you mean by event-driven?",
     "https://martinfowler.com/articles/201701-event-driven.html"
    ],
    [
     "Confluent — Event-driven architecture",
     "https://www.confluent.io/learn/event-driven-architecture/"
    ],
    [
     "microservices.io — Event sourcing",
     "https://microservices.io/patterns/data/event-sourcing.html"
    ],
    [
     "AlgoMaster — Change data capture (CDC)",
     "https://algomaster.io/learn/system-design/change-data-capture-cdc"
    ]
   ]
  },
  "monolith-vs-microservices-vs-serverless.md": {
   "videos": [],
   "docs": [
    [
     "Martin Fowler — Microservices",
     "https://martinfowler.com/articles/microservices.html"
    ],
    [
     "Martin Fowler — MonolithFirst",
     "https://martinfowler.com/bliki/MonolithFirst.html"
    ],
    [
     "AlgoMaster — Serverless architecture",
     "https://blog.algomaster.io/p/2edeb23b-cfa5-4b24-845e-3f6f7a39d162"
    ],
    [
     "microservices.io — Microservice architecture pattern",
     "https://microservices.io/patterns/microservices.html"
    ]
   ]
  },
  "microservices-patterns.md": {
   "videos": [],
   "docs": [
    [
     "microservices.io — Pattern catalogue",
     "https://microservices.io/patterns/index.html"
    ],
    [
     "microservices.io — Database per service",
     "https://microservices.io/patterns/data/database-per-service.html"
    ],
    [
     "Martin Fowler — CQRS",
     "https://martinfowler.com/bliki/CQRS.html"
    ],
    [
     "Martin Fowler — Strangler fig application",
     "https://martinfowler.com/bliki/StranglerFigApplication.html"
    ]
   ]
  },
  "clean-layered-hexagonal-architecture.md": {
   "videos": [],
   "docs": [
    [
     "Uncle Bob — The clean architecture",
     "https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html"
    ],
    [
     "Alistair Cockburn — Hexagonal architecture",
     "https://alistair.cockburn.us/hexagonal-architecture/"
    ],
    [
     "Martin Fowler — PresentationDomainDataLayering",
     "https://martinfowler.com/bliki/PresentationDomainDataLayering.html"
    ]
   ]
  },
  "circuit-breakers-bulkheads-timeouts.md": {
   "videos": [],
   "docs": [
    [
     "Martin Fowler — Circuit breaker",
     "https://martinfowler.com/bliki/CircuitBreaker.html"
    ],
    [
     "AWS Builders' Library — Timeouts, retries and backoff with jitter",
     "https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/"
    ],
    [
     "microservices.io — Circuit breaker pattern",
     "https://microservices.io/patterns/reliability/circuit-breaker.html"
    ],
    [
     "Google SRE Book — Addressing cascading failures",
     "https://sre.google/sre-book/addressing-cascading-failures/"
    ]
   ]
  },
  "backpressure-throttling-load-protection.md": {
   "videos": [],
   "docs": [
    [
     "Apply back pressure when overloaded (Mechanical Sympathy)",
     "http://mechanical-sympathy.blogspot.com/2012/05/apply-back-pressure-when-overloaded.html"
    ],
    [
     "AWS Builders' Library — Using load shedding to avoid overload",
     "https://aws.amazon.com/builders-library/using-load-shedding-to-avoid-overload/"
    ],
    [
     "Google SRE Book — Handling overload",
     "https://sre.google/sre-book/handling-overload/"
    ]
   ]
  },
  "graceful-degradation-load-shedding.md": {
   "videos": [],
   "docs": [
    [
     "Google SRE Book — Handling overload",
     "https://sre.google/sre-book/handling-overload/"
    ],
    [
     "AWS Builders' Library — Avoiding fallback in distributed systems",
     "https://aws.amazon.com/builders-library/avoiding-fallback-in-distributed-systems/"
    ],
    [
     "AWS Builders' Library — Workload isolation using shuffle sharding",
     "https://aws.amazon.com/builders-library/workload-isolation-using-shuffle-sharding/"
    ]
   ]
  },
  "distributed-locking-idempotency-safe-retries.md": {
   "videos": [
    [
     "v7x75aN9liM",
     "Distributed locks — system design basics",
     "Tech Dummies - Narendra Lakshmana Gowda"
    ]
   ],
   "docs": [
    [
     "Kleppmann — How to do distributed locking",
     "https://martin.kleppmann.com/2016/02/08/how-to-do-distributed-locking.html"
    ],
    [
     "Redis — Distributed locks (Redlock)",
     "https://redis.io/docs/latest/develop/clients/patterns/distributed-locks/"
    ],
    [
     "Stripe — Designing robust and predictable APIs with idempotency",
     "https://stripe.com/blog/idempotency"
    ]
   ]
  },
  "consensus-algorithms-raft-paxos.md": {
   "videos": [],
   "docs": [
    [
     "The Secret Lives of Data — Raft, visualised",
     "https://thesecretlivesofdata.com/raft/"
    ],
    [
     "Raft — the consensus algorithm (official site)",
     "https://raft.github.io/"
    ],
    [
     "Paxos: the part-time parliament (paper)",
     "https://lamport.azurewebsites.net/pubs/lamport-paxos.pdf"
    ],
    [
     "Google SRE Book — Managing critical state: distributed consensus",
     "https://sre.google/sre-book/managing-critical-state/"
    ]
   ]
  },
  "leader-election-heartbeats-failure-detection.md": {
   "videos": [],
   "docs": [
    [
     "AlgoMaster — Heartbeats in distributed systems",
     "https://blog.algomaster.io/p/heartbeats-in-distributed-systems"
    ],
    [
     "ZooKeeper: wait-free coordination (paper)",
     "https://www.usenix.org/legacy/event/usenix10/tech/full_papers/Hunt.pdf"
    ],
    [
     "The Chubby lock service (paper)",
     "https://static.googleusercontent.com/media/research.google.com/en//archive/chubby-osdi06.pdf"
    ]
   ]
  },
  "distributed-transactions-sagas.md": {
   "videos": [],
   "docs": [
    [
     "microservices.io — Saga pattern",
     "https://microservices.io/patterns/data/saga.html"
    ],
    [
     "Airbnb — Avoiding double payments in a distributed payments system",
     "https://medium.com/airbnb-engineering/avoiding-double-payments-in-a-distributed-payments-system-2981f6b070bb"
    ],
    [
     "Two-phase commit protocol",
     "https://en.wikipedia.org/wiki/Two-phase_commit_protocol"
    ]
   ]
  },
  "search-indexing-ranking-typeahead.md": {
   "videos": [
    [
     "CeGtqouT8eA",
     "How Google searches one document among billions quickly",
     "Tech Dummies - Narendra Lakshmana Gowda"
    ]
   ],
   "docs": [
    [
     "Elasticsearch — Inverted index and relevance",
     "https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html"
    ],
    [
     "Introduction to Information Retrieval (free book)",
     "https://nlp.stanford.edu/IR-book/information-retrieval-book.html"
    ],
    [
     "Redis — Sorted sets (for top-K and typeahead)",
     "https://redis.io/docs/latest/develop/data-types/sorted-sets/"
    ]
   ]
  },
  "metrics-dashboards-alerting.md": {
   "videos": [
    [
     "kIcq1_pBQSY",
     "Design an analytics platform (metrics & logging) — mock interview",
     "Exponent"
    ]
   ],
   "docs": [
    [
     "Google SRE Book — Monitoring distributed systems",
     "https://sre.google/sre-book/monitoring-distributed-systems/"
    ],
    [
     "Prometheus — Instrumentation best practices",
     "https://prometheus.io/docs/practices/instrumentation/"
    ],
    [
     "Prometheus — Alerting best practices",
     "https://prometheus.io/docs/practices/alerting/"
    ]
   ]
  },
  "logging-distributed-tracing.md": {
   "videos": [],
   "docs": [
    [
     "OpenTelemetry — Observability primer",
     "https://opentelemetry.io/docs/concepts/observability-primer/"
    ],
    [
     "Dapper, a large-scale distributed systems tracing infrastructure (paper)",
     "https://static.googleusercontent.com/media/research.google.com/en//archive/papers/dapper-2010-1.pdf"
    ],
    [
     "Dynatrace — What is distributed tracing?",
     "https://www.dynatrace.com/news/blog/what-is-distributed-tracing/"
    ]
   ]
  },
  "slos-error-budgets-golden-signals.md": {
   "videos": [],
   "docs": [
    [
     "Google SRE Book — Service level objectives",
     "https://sre.google/sre-book/service-level-objectives/"
    ],
    [
     "Google SRE Workbook — Implementing SLOs",
     "https://sre.google/workbook/implementing-slos/"
    ],
    [
     "Google SRE Book — Monitoring: the four golden signals",
     "https://sre.google/sre-book/monitoring-distributed-systems/"
    ]
   ]
  },
  "testing-chaos-safe-deployment.md": {
   "videos": [],
   "docs": [
    [
     "Principles of chaos engineering",
     "https://principlesofchaos.org/"
    ],
    [
     "Martin Fowler — The practical test pyramid",
     "https://martinfowler.com/articles/practical-test-pyramid.html"
    ],
    [
     "Martin Fowler — Blue-green deployment",
     "https://martinfowler.com/bliki/BlueGreenDeployment.html"
    ],
    [
     "Google SRE Book — Release engineering",
     "https://sre.google/sre-book/release-engineering/"
    ]
   ]
  },
  "authentication-authorization.md": {
   "videos": [
    [
     "uj_4vxm9u90",
     "Design a simple authentication system — interview prep",
     "Interview Pen"
    ]
   ],
   "docs": [
    [
     "OAuth 2.0 — official site",
     "https://oauth.net/2/"
    ],
    [
     "JWT — Introduction",
     "https://jwt.io/introduction"
    ],
    [
     "OWASP — Authentication cheat sheet",
     "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html"
    ],
    [
     "Auth0 — Authentication and authorization flows",
     "https://auth0.com/docs/get-started/authentication-and-authorization-flow"
    ]
   ]
  },
  "owasp-top-10-api-security.md": {
   "videos": [],
   "docs": [
    [
     "OWASP API Security Top 10 (2023)",
     "https://owasp.org/API-Security/editions/2023/en/0x11-t10/"
    ],
    [
     "OWASP Top 10",
     "https://owasp.org/www-project-top-ten/"
    ],
    [
     "API security checklist",
     "https://github.com/shieldfy/API-Security-Checklist"
    ]
   ]
  },
  "threat-modeling-abuse-cases.md": {
   "videos": [],
   "docs": [
    [
     "OWASP — Threat modeling cheat sheet",
     "https://cheatsheetseries.owasp.org/cheatsheets/Threat_Modeling_Cheat_Sheet.html"
    ],
    [
     "Microsoft — STRIDE threat model",
     "https://learn.microsoft.com/en-us/azure/security/develop/threat-modeling-tool-threats"
    ],
    [
     "OWASP — Abuse case cheat sheet",
     "https://cheatsheetseries.owasp.org/cheatsheets/Abuse_Case_Cheat_Sheet.html"
    ]
   ]
  },
  "cost-estimation-build-vs-buy-trade-offs.md": {
   "videos": [],
   "docs": [
    [
     "AWS Well-Architected — Cost optimization pillar",
     "https://docs.aws.amazon.com/wellarchitected/latest/cost-optimization-pillar/welcome.html"
    ],
    [
     "AWS pricing calculator",
     "https://calculator.aws/"
    ],
    [
     "AlgoMaster — Top 15 system design trade-offs",
     "https://blog.algomaster.io/p/system-design-top-15-trade-offs"
    ]
   ]
  },
  "hld-vs-lld-boundaries.md": {
   "videos": [],
   "docs": [
    [
     "Hello Interview — System design in a hurry",
     "https://www.hellointerview.com/learn/system-design/in-a-hurry/introduction"
    ],
    [
     "Martin Fowler — Software architecture guide",
     "https://martinfowler.com/architecture/"
    ],
    [
     "Refactoring Guru — Design patterns catalogue",
     "https://refactoring.guru/design-patterns/catalog"
    ]
   ]
  },
  "object-oriented-foundations.md": {
   "videos": [],
   "docs": [
    [
     "Refactoring Guru — OOP basics",
     "https://refactoring.guru/design-patterns/what-is-pattern"
    ],
    [
     "Java design patterns — principles",
     "https://java-design-patterns.com/principles/"
    ],
    [
     "SOLID principles explained",
     "https://en.wikipedia.org/wiki/SOLID"
    ]
   ]
  },
  "design-principles.md": {
   "videos": [],
   "docs": [
    [
     "Java design patterns — principles",
     "https://java-design-patterns.com/principles/"
    ],
    [
     "Uncle Bob — The principles of OOD",
     "http://butunclebob.com/ArticleS.UncleBob.PrinciplesOfOod"
    ],
    [
     "Refactoring Guru — Design principles",
     "https://refactoring.guru/design-patterns/what-is-pattern"
    ]
   ]
  },
  "uml-interaction-modeling.md": {
   "videos": [],
   "docs": [
    [
     "UML class diagrams reference",
     "https://www.uml-diagrams.org/class-diagrams-overview.html"
    ],
    [
     "PlantUML — Sequence diagram syntax",
     "https://plantuml.com/sequence-diagram"
    ],
    [
     "Mermaid — Class diagram syntax",
     "https://mermaid.js.org/syntax/classDiagram.html"
    ]
   ]
  },
  "design-patterns-for-lld.md": {
   "videos": [],
   "docs": [
    [
     "Refactoring Guru — Design patterns catalogue",
     "https://refactoring.guru/design-patterns/catalog"
    ],
    [
     "Java design patterns — full catalogue",
     "https://java-design-patterns.com/patterns/"
    ],
    [
     "SourceMaking — Design patterns",
     "https://sourcemaking.com/design_patterns"
    ]
   ]
  },
  "machine-coding-lld-case-studies.md": {
   "videos": [
    [
     "NtMvNh0WFVM",
     "Amazon system design interview: design a parking garage",
     "Exponent"
    ],
    [
     "D0kDMUgo27c",
     "System design mock interview: design a vending machine",
     "Exponent"
    ]
   ],
   "docs": [
    [
     "Refactoring Guru — Design patterns catalogue",
     "https://refactoring.guru/design-patterns/catalog"
    ],
    [
     "Awesome low-level design (GitHub)",
     "https://github.com/ashishps1/awesome-low-level-design"
    ]
   ]
  },
  "foundational-designs.md": {
   "videos": [],
   "docs": [
    [
     "AlgoMaster — Design a URL shortener",
     "https://algomaster.io/learn/system-design-interviews/design-url-shortener"
    ],
    [
     "AlgoMaster — Design a load balancer",
     "https://algomaster.io/learn/system-design-interviews/design-load-balancer"
    ],
    [
     "AlgoMaster — Design a distributed job scheduler",
     "https://blog.algomaster.io/p/design-a-distributed-job-scheduler"
    ]
   ]
  },
  "core-interview-designs.md": {
   "videos": [],
   "docs": [
    [
     "AlgoMaster — Design WhatsApp",
     "https://algomaster.io/learn/system-design-interviews/design-whatsapp"
    ],
    [
     "AlgoMaster — Design Instagram",
     "https://algomaster.io/learn/system-design-interviews/design-instagram"
    ],
    [
     "AlgoMaster — Design a notification service",
     "https://algomaster.io/learn/system-design-interviews/design-notification-service"
    ]
   ]
  },
  "advanced-senior-level-designs.md": {
   "videos": [],
   "docs": [
    [
     "Discord — How Discord stores trillions of messages",
     "https://discord.com/blog/how-discord-stores-trillions-of-messages"
    ],
    [
     "Slack — Real-time messaging",
     "https://slack.engineering/real-time-messaging/"
    ],
    [
     "Spanner: Google's globally distributed database (paper)",
     "https://static.googleusercontent.com/media/research.google.com/en//archive/spanner-osdi2012.pdf"
    ]
   ]
  }
 },
 "concepts": {
  "foundational-designs/url-shortener-tinyurl-bit-ly-hash-base62-collision-handling-analytics": {
   "videos": [
    [
     "xFeWVugaouk",
     "Design a URL Shortener (TinyURL, Bit.ly)",
     "Jordan has no life"
    ]
   ],
   "docs": [
    [
     "AlgoMaster — Design a URL shortener",
     "https://algomaster.io/learn/system-design-interviews/design-url-shortener"
    ],
    [
     "System Design Primer — Design Pastebin / TinyURL",
     "https://github.com/donnemartin/system-design-primer/blob/master/solutions/system_design/pastebin/README.md"
    ]
   ]
  },
  "foundational-designs/distributed-cache-redis-cluster-consistent-hashing-eviction-replication": {
   "videos": [
    [
     "iuqZvajTOyA",
     "System Design Interview — Distributed Cache",
     "System Design Interview"
    ]
   ],
   "docs": [
    [
     "Redis — Cluster specification",
     "https://redis.io/docs/latest/operate/oss_and_stack/reference/cluster-spec/"
    ],
    [
     "AlgoMaster — Distributed caching",
     "https://blog.algomaster.io/p/distributed-caching"
    ]
   ]
  },
  "foundational-designs/key-value-store-lsm-tree-compaction-range-queries": {
   "videos": [
    [
     "rnZmdmlR-2M",
     "System Design: distributed database — key-value store",
     "Tushar Roy - Coding Made Simple"
    ]
   ],
   "docs": [
    [
     "Dynamo: Amazon's highly available key-value store (paper)",
     "https://www.allthingsdistributed.com/files/amazon-dynamo-sosp2007.pdf"
    ],
    [
     "The Log-Structured Merge-Tree (paper)",
     "https://www.cs.umb.edu/~poneil/lsmtree.pdf"
    ]
   ]
  },
  "foundational-designs/content-delivery-network-pull-vs-push-origin-shield-cache-invalidation": {
   "videos": [
    [
     "8zX0rue2Hic",
     "System Design: Content Delivery Networks (simplified)",
     "Gaurav Sen"
    ]
   ],
   "docs": [
    [
     "Cloudflare — What is a CDN?",
     "https://www.cloudflare.com/learning/cdn/what-is-a-cdn/"
    ],
    [
     "Push vs pull CDNs",
     "https://www.geeksforgeeks.org/system-design/pull-cdn-vs-push-cdn/"
    ]
   ]
  },
  "foundational-designs/rate-limiter-distributed-token-bucket-in-redis-per-user-limits": {
   "videos": [
    [
     "mhUQe4BKZXs",
     "Rate limiting system design — token bucket, leaky bucket, sliding logs",
     "Tech Dummies - Narendra Lakshmana Gowda"
    ]
   ],
   "docs": [
    [
     "Stripe — Scaling your API with rate limiters",
     "https://stripe.com/blog/rate-limiters"
    ],
    [
     "AlgoMaster — Rate limiting algorithms explained with code",
     "https://blog.algomaster.io/p/rate-limiting-algorithms-explained-with-code"
    ]
   ]
  },
  "foundational-designs/distributed-job-scheduler-priority-queues-at-least-once-execution-dedup": {
   "videos": [],
   "docs": [
    [
     "AlgoMaster — Design a distributed job scheduler",
     "https://blog.algomaster.io/p/design-a-distributed-job-scheduler"
    ],
    [
     "Google SRE Book — Distributed periodic scheduling with Cron",
     "https://sre.google/sre-book/distributed-periodic-scheduling/"
    ]
   ]
  },
  "core-interview-designs/chat-whatsapp-slack-websockets-message-ordering-presence-fan-out": {
   "videos": [
    [
     "cr6p0n0N-VA",
     "Design WhatsApp: system design interview with an ex-Meta senior manager",
     "Hello Interview"
    ]
   ],
   "docs": [
    [
     "AlgoMaster — Design WhatsApp",
     "https://algomaster.io/learn/system-design-interviews/design-whatsapp"
    ],
    [
     "Slack — Real-time messaging",
     "https://slack.engineering/real-time-messaging/"
    ],
    [
     "Discord — How Discord stores trillions of messages",
     "https://discord.com/blog/how-discord-stores-trillions-of-messages"
    ]
   ]
  },
  "core-interview-designs/twitter-x-fan-out-on-write-vs-read-hybrid-for-celebrities": {
   "videos": [
    [
     "wYk0xPP_P_8",
     "Twitter system design — architecture and interview questions",
     "Tech Dummies - Narendra Lakshmana Gowda"
    ]
   ],
   "docs": [
    [
     "System Design Primer — Design Twitter timeline and search",
     "https://github.com/donnemartin/system-design-primer/blob/master/solutions/system_design/twitter/README.md"
    ]
   ]
  },
  "core-interview-designs/youtube-netflix-upload-pipeline-transcoding-adaptive-bitrate-streaming-cdn": {
   "videos": [
    [
     "jPKTo1iGQiE",
     "Design YouTube — system design interview",
     "NeetCode"
    ],
    [
     "psQzyFfsUGU",
     "Netflix system design — software architecture",
     "Tech Dummies - Narendra Lakshmana Gowda"
    ]
   ],
   "docs": [
    [
     "Netflix — Building in-video search",
     "https://netflixtechblog.com/building-in-video-search-936766f0017c"
    ]
   ]
  },
  "core-interview-designs/instagram-photo-sharing-media-upload-feed-generation-s3-cdn": {
   "videos": [
    [
     "VJpfO6KdyWE",
     "System design mock interview: design Instagram",
     "Exponent"
    ]
   ],
   "docs": [
    [
     "AlgoMaster — Design Instagram",
     "https://algomaster.io/learn/system-design-interviews/design-instagram"
    ],
    [
     "Canva — Scaling media uploads from zero to 50M per day",
     "https://www.canva.dev/blog/engineering/from-zero-to-50-million-uploads-per-day-scaling-media-at-canva/"
    ]
   ]
  },
  "core-interview-designs/notification-system-multi-channel-push-email-sms-queues-templates-dedup": {
   "videos": [
    [
     "CUwt9_l0DOg",
     "Notification service system design for billions of users",
     "codeKarle"
    ]
   ],
   "docs": [
    [
     "AlgoMaster — Design a notification service",
     "https://algomaster.io/learn/system-design-interviews/design-notification-service"
    ],
    [
     "AWS — SQS dead-letter queues",
     "https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html"
    ]
   ]
  },
  "core-interview-designs/ticketmaster-seat-booking-inventory-locks-payment-timeout-distributed-txns": {
   "videos": [
    [
     "lBAwJgoO3Ek",
     "BookMyShow / Fandango system design — online ticket booking",
     "Tech Dummies - Narendra Lakshmana Gowda"
    ]
   ],
   "docs": [
    [
     "microservices.io — Saga pattern",
     "https://microservices.io/patterns/data/saga.html"
    ],
    [
     "Kleppmann — How to do distributed locking",
     "https://martin.kleppmann.com/2016/02/08/how-to-do-distributed-locking.html"
    ]
   ]
  },
  "core-interview-designs/tinder-matching-geospatial-indexing-swiping-at-scale-recommendations": {
   "videos": [
    [
     "tndzLznxq40",
     "System design: Tinder as a microservice architecture",
     "Gaurav Sen"
    ]
   ],
   "docs": [
    [
     "Redis — Geospatial indexes",
     "https://redis.io/docs/latest/develop/data-types/geospatial/"
    ]
   ]
  },
  "core-interview-designs/tiktok-short-video-ml-powered-feed-cdn-video-encoding-pipeline": {
   "videos": [
    [
     "Z-0g_aJL5Fw",
     "System design mock interview: design TikTok (ft. Google TPM)",
     "Exponent"
    ]
   ],
   "docs": [
    [
     "Netflix — Building in-video search",
     "https://netflixtechblog.com/building-in-video-search-936766f0017c"
    ]
   ]
  },
  "core-interview-designs/airbnb-booking-double-booking-prevention-calendar-availability-search": {
   "videos": [
    [
     "YyOXt2MEkv4",
     "Airbnb / Booking.com system design interview question",
     "codeKarle"
    ]
   ],
   "docs": [
    [
     "Airbnb — Avoiding double payments in a distributed payments system",
     "https://medium.com/airbnb-engineering/avoiding-double-payments-in-a-distributed-payments-system-2981f6b070bb"
    ]
   ]
  },
  "core-interview-designs/payment-system-idempotency-double-entry-bookkeeping-audit-logs-pci-dss": {
   "videos": [
    [
     "olfaBgJrUBI",
     "Design a payment system — system design interview",
     "Code with Lucian"
    ],
    [
     "QpLy0_c_RXk",
     "UPI system design mock interview",
     "Gaurav Sen"
    ]
   ],
   "docs": [
    [
     "Stripe — Designing APIs with idempotency",
     "https://stripe.com/blog/idempotency"
    ],
    [
     "Stripe — Payment APIs, the first 10 years",
     "https://stripe.com/blog/payment-api-design"
    ]
   ]
  },
  "core-interview-designs/distributed-message-queue-kafka-design-ordering-partitions-consumer-groups": {
   "videos": [
    [
     "iJLL-KPqBpM",
     "System Design Interview — distributed message queue",
     "System Design Interview"
    ]
   ],
   "docs": [
    [
     "Kafka — Design (official docs)",
     "https://kafka.apache.org/documentation/#design"
    ],
    [
     "Kafka: a distributed messaging system for log processing (paper)",
     "https://notes.stephenholiday.com/Kafka.pdf"
    ]
   ]
  },
  "core-interview-designs/reddit-hn-voting-ranking-comment-threads-subreddit-feeds": {
   "videos": [
    [
     "KYExYE_9nIY",
     "Design Reddit: system design mock interview",
     "Exponent"
    ]
   ],
   "docs": [
    [
     "Hacker News ranking algorithm explained",
     "https://medium.com/hacking-and-gonzo/how-hacker-news-ranking-algorithm-works-1d9b0cf2c08d"
    ]
   ]
  },
  "core-interview-designs/autocomplete-typeahead-trie-top-k-redis-sorted-sets-prefix-cache": {
   "videos": [
    [
     "xrYTjaK5QVM",
     "Architecture for auto suggestions / type ahead (Amazon question)",
     "Tech Dummies - Narendra Lakshmana Gowda"
    ]
   ],
   "docs": [
    [
     "Redis — Sorted sets for top-K and typeahead",
     "https://redis.io/docs/latest/develop/data-types/sorted-sets/"
    ],
    [
     "Elasticsearch — Search-as-you-type",
     "https://www.elastic.co/guide/en/elasticsearch/reference/current/search-as-you-type.html"
    ]
   ]
  },
  "advanced-senior-level-designs/uber-rideshare-geospatial-indexing-quad-tree-geohash-matching-real-time-location": {
   "videos": [
    [
     "umWABit-wbk",
     "Uber / Ola system design — architecture",
     "Tech Dummies - Narendra Lakshmana Gowda"
    ]
   ],
   "docs": [
    [
     "Uber — H3: hexagonal hierarchical spatial index",
     "https://www.uber.com/en-US/blog/h3/"
    ]
   ]
  },
  "advanced-senior-level-designs/google-search-crawling-indexing-ranking-pagerank-serving": {
   "videos": [
    [
     "CeGtqouT8eA",
     "How Google searches one document among billions quickly",
     "Tech Dummies - Narendra Lakshmana Gowda"
    ]
   ],
   "docs": [
    [
     "The anatomy of a large-scale hypertextual web search engine (paper)",
     "http://infolab.stanford.edu/~backrub/google.html"
    ],
    [
     "Introduction to Information Retrieval (free book)",
     "https://nlp.stanford.edu/IR-book/information-retrieval-book.html"
    ]
   ]
  },
  "advanced-senior-level-designs/google-drive-dropbox-chunked-upload-dedup-hashing-sync-conflict-resolution": {
   "videos": [
    [
     "U0xTu6E2CT8",
     "Dropbox / Google Drive system design — file share and upload",
     "Tech Dummies - Narendra Lakshmana Gowda"
    ]
   ],
   "docs": [
    [
     "The Google File System (paper)",
     "https://static.googleusercontent.com/media/research.google.com/en//archive/gfs-sosp2003.pdf"
    ]
   ]
  },
  "advanced-senior-level-designs/google-maps-tile-generation-routing-dijkstra-at-scale-real-time-traffic": {
   "videos": [
    [
     "jk3yvVfNvds",
     "Google Maps system design interview question",
     "codeKarle"
    ]
   ],
   "docs": [
    [
     "Uber — H3 spatial index",
     "https://www.uber.com/en-US/blog/h3/"
    ]
   ]
  },
  "advanced-senior-level-designs/google-docs-collaborative-editing-ot-operational-transform-or-crdts-conflict-resolution": {
   "videos": [
    [
     "2auwirNBvGg",
     "Google Docs system design — operational transformation",
     "Tech Dummies - Narendra Lakshmana Gowda"
    ]
   ],
   "docs": [
    [
     "Kleppmann — CRDTs: the hard parts",
     "https://martin.kleppmann.com/2020/07/06/crdt-hard-parts-hydra.html"
    ],
    [
     "Operational transformation",
     "https://en.wikipedia.org/wiki/Operational_transformation"
    ]
   ]
  },
  "advanced-senior-level-designs/stock-exchange-ultra-low-latency-order-matching-engine-fifo-fairness": {
   "videos": [
    [
     "dGYfpO3WJ1o",
     "High throughput stock exchange",
     "Jordan has no life"
    ]
   ],
   "docs": [
    [
     "LMAX — The LMAX architecture (Martin Fowler)",
     "https://martinfowler.com/articles/lmax.html"
    ],
    [
     "Order matching system",
     "https://en.wikipedia.org/wiki/Order_matching_system"
    ]
   ]
  },
  "advanced-senior-level-designs/facebook-news-feed-social-graph-ranking-fan-out-strategies-at-3b-users": {
   "videos": [
    [
     "9-hjBGxuiEs",
     "Facebook / Instagram system design interview question",
     "codeKarle"
    ]
   ],
   "docs": [
    [
     "Facebook — Scaling Memcache at Facebook (paper)",
     "https://www.usenix.org/system/files/conference/nsdi13/nsdi13-final170_update.pdf"
    ]
   ]
  },
  "advanced-senior-level-designs/distributed-locking-service-like-chubby-consensus-lease-renewal-callbacks": {
   "videos": [
    [
     "v7x75aN9liM",
     "Distributed locks — system design basics",
     "Tech Dummies - Narendra Lakshmana Gowda"
    ]
   ],
   "docs": [
    [
     "The Chubby lock service (paper)",
     "https://static.googleusercontent.com/media/research.google.com/en//archive/chubby-osdi06.pdf"
    ],
    [
     "ZooKeeper: wait-free coordination (paper)",
     "https://www.usenix.org/legacy/event/usenix10/tech/full_papers/Hunt.pdf"
    ]
   ]
  },
  "machine-coding-lld-case-studies/parking-lot-design": {
   "videos": [
    [
     "NtMvNh0WFVM",
     "Amazon system design interview: design a parking garage",
     "Exponent"
    ]
   ],
   "docs": [
    [
     "Awesome low-level design — parking lot",
     "https://github.com/ashishps1/awesome-low-level-design"
    ]
   ]
  },
  "machine-coding-lld-case-studies/bookmyshow-ticket-booking-lld": {
   "videos": [
    [
     "lBAwJgoO3Ek",
     "BookMyShow / Fandango system design",
     "Tech Dummies - Narendra Lakshmana Gowda"
    ]
   ],
   "docs": [
    [
     "Awesome low-level design",
     "https://github.com/ashishps1/awesome-low-level-design"
    ]
   ]
  }
 }
};
