# Original plain-English problem statements (written for this site, not copied from LeetCode).
# lc-number → what the problem asks, in 1–2 beginner-friendly sentences.
# The LeetCode icon on each page links to the formal statement with exact constraints.

STATEMENTS = {
1: "Given an array of integers and a target, return the indices of the two numbers that add up to the target (exactly one such pair exists).",
2: "Two non-empty linked lists store non-negative integers with digits in reverse order. Add the two numbers and return the sum as a linked list in the same format.",
3: "Given a string, find the length of the longest substring that contains no repeated character.",
4: "Given two sorted arrays, return the median of all their elements combined, in O(log(m+n)) time.",
5: "Given a string, return its longest substring that reads the same forwards and backwards.",
6: "Write a string in a zigzag over a given number of rows, then read it row by row and return the result.",
8: "Convert a string to a 32-bit signed integer the way atoi does: skip leading spaces, read an optional sign, read digits until a non-digit, and clamp to the 32-bit range.",
9: "Determine whether an integer reads the same forwards and backwards, without converting it to a string.",
10: "Implement regular-expression matching over the full input string where '.' matches any single character and '*' means zero or more of the preceding element.",
11: "Vertical lines of given heights stand on the x-axis. Choose two of them to form a container with the x-axis; return the maximum water it can hold.",
12: "Convert an integer (1 to 3999) into its Roman numeral representation.",
13: "Convert a Roman numeral string into its integer value, honoring subtractive pairs like IV and CM.",
14: "Given an array of strings, return the longest prefix shared by all of them (empty string if none).",
15: "Find all unique triplets in an array that sum to zero; the result must contain no duplicate triplets.",
16: "Given an array and a target, return the sum of the three numbers whose sum is closest to the target.",
17: "Given a string of digits 2–9, return every possible letter combination the digits could represent on a phone keypad.",
18: "Find all unique quadruplets in an array that sum to a given target, with no duplicate quadruplets.",
19: "Remove the n-th node from the end of a linked list and return the head — ideally in one pass.",
20: "Given a string of the brackets ()[]{}, decide whether every opener is closed by the matching bracket type in the correct order.",
21: "Merge two sorted linked lists into one sorted linked list by splicing their nodes together.",
22: "Given n, generate every string of n pairs of parentheses that is well-formed.",
23: "Merge k sorted linked lists into one sorted linked list.",
24: "Swap every two adjacent nodes of a linked list (rewire nodes, don't just swap values) and return the head.",
25: "Reverse the nodes of a linked list k at a time; any final group shorter than k stays in original order.",
26: "Remove duplicates from a sorted array in place so each value appears once; return the count of unique elements at the front.",
27: "Remove every occurrence of a given value from an array in place and return how many elements remain.",
28: "Return the index of the first occurrence of a needle string inside a haystack string, or -1 if absent.",
31: "Rearrange an array of numbers into the lexicographically next greater permutation in place; if none exists, sort ascending.",
32: "Given a string of '(' and ')', return the length of the longest well-formed (valid) substring.",
33: "A sorted array was rotated at an unknown pivot. Find the index of a target value in O(log n), or -1.",
34: "In a sorted array with duplicates, find the first and last index of a target value in O(log n); return [-1,-1] if absent.",
35: "Given a sorted array and a target, return the index where the target is found or where it would be inserted to keep order.",
37: "Fill a partially completed 9×9 Sudoku grid so every row, column, and 3×3 box contains the digits 1–9 exactly once.",
38: "Build the count-and-say sequence: each term describes the previous one aloud (e.g. '21' → 'one 2, one 1' → '1211'); return the n-th term.",
39: "Given distinct candidate numbers and a target, list all unique combinations (numbers reusable any times) that sum to the target.",
40: "Given candidates that may repeat and a target, list all unique combinations summing to the target where each candidate is used at most once.",
41: "Given an unsorted integer array, return the smallest positive integer that is missing, in O(n) time and O(1) extra space.",
42: "Given bar heights of an elevation map, compute how much rainwater the valleys between bars can trap.",
43: "Multiply two non-negative integers given as strings and return the product as a string, without big-integer libraries.",
44: "Wildcard matching over the whole string: '?' matches any one character and '*' matches any sequence (including empty).",
45: "Each array value is your maximum jump length from that index. Return the minimum number of jumps to reach the last index.",
46: "Return all permutations of an array of distinct numbers.",
47: "Return all unique permutations of an array that may contain duplicate numbers.",
48: "Rotate an n×n matrix 90 degrees clockwise, in place.",
49: "Group a list of words so that words that are anagrams of each other end up in the same group.",
50: "Implement pow(x, n) — x raised to the integer power n, handling negative exponents — efficiently.",
51: "Place n queens on an n×n board so none attack each other; return all distinct board layouts.",
53: "Find the contiguous subarray with the largest sum and return that sum.",
54: "Return all elements of an m×n matrix in spiral order, clockwise from the top-left.",
55: "Each value is your maximum jump length from that index. Decide whether you can reach the last index from the first.",
56: "Merge all overlapping intervals in a list and return the non-overlapping result.",
57: "Insert a new interval into a sorted list of non-overlapping intervals, merging where needed.",
60: "Among all permutations of 1..n in sorted order, return the k-th one directly (without generating them all).",
61: "Rotate a linked list to the right by k places.",
62: "Count the paths a robot can take from the top-left to the bottom-right of an m×n grid moving only right or down.",
63: "Same right/down robot walk, but some grid cells contain obstacles that cannot be entered; count the paths.",
64: "Find the path from top-left to bottom-right of a grid of non-negative numbers (moving right or down) minimizing the sum of visited cells.",
66: "An array of digits represents a large integer; add one to it and return the resulting digit array.",
68: "Greedily pack words into lines of exactly maxWidth characters, distributing spaces as evenly as possible (left-justify the last line).",
69: "Compute the integer square root of a non-negative integer (the floor of √x) without using built-in power functions.",
70: "You climb a staircase taking 1 or 2 steps at a time; count the distinct ways to reach step n.",
71: "Simplify an absolute Unix file path: resolve '.', '..', and repeated slashes into the canonical path.",
72: "Given two words, return the minimum number of single-character insertions, deletions, or replacements to turn one into the other.",
73: "If any cell of a matrix is 0, set its whole row and column to 0 — in place, ideally with O(1) extra space.",
74: "Search a target in a matrix whose rows are sorted and where each row starts after the previous row ends, in O(log(m·n)).",
75: "Sort an array containing only 0s, 1s, and 2s in place, ideally in a single pass without a counting sort.",
76: "Find the smallest window (substring) of s that contains every character of t (with multiplicity).",
77: "Return all combinations of k numbers chosen from 1..n.",
78: "Return every possible subset (the power set) of an array of distinct integers.",
79: "Given a letter grid and a word, decide whether the word can be traced through adjacent cells without reusing a cell.",
80: "Remove duplicates from a sorted array in place so each value appears at most twice; return the new length.",
81: "Search a target in a rotated sorted array that may contain duplicates; return whether it exists.",
82: "From a sorted linked list, delete every value that appears more than once, keeping only values that occur exactly once.",
83: "From a sorted linked list, remove the extra copies so each value appears exactly once.",
84: "Given bar heights of a histogram, return the area of the largest rectangle that fits entirely inside it.",
85: "In a binary matrix, find the area of the largest rectangle containing only 1s.",
86: "Partition a linked list around a value x so all nodes < x come before all nodes ≥ x, preserving relative order within each part.",
87: "Decide whether one string is a 'scramble' of another, where scrambling recursively splits a string in two and may swap the halves.",
88: "Merge a sorted array of n elements into a sorted array of m elements (which has room at its end) in place, producing one sorted array.",
90: "Return every subset of an array that may contain duplicates, without producing duplicate subsets.",
91: "A message of digits was encoded with A=1..Z=26; count how many ways it can be decoded (watch the zeros).",
92: "Reverse the nodes of a linked list from position left to position right, in one pass.",
93: "Insert dots into a digit string to form every possible valid IPv4 address (four parts, 0–255, no leading zeros).",
94: "Return the inorder traversal (left, node, right) of a binary tree's values.",
95: "Generate all structurally unique binary search trees that store the values 1..n.",
96: "Count how many structurally unique binary search trees can store values 1..n.",
97: "Decide whether string s3 can be formed by interleaving s1 and s2 while keeping each string's internal order.",
98: "Decide whether a binary tree is a valid binary search tree (every node greater than all of its left subtree and less than all of its right).",
99: "Exactly two nodes of a BST had their values swapped by mistake; find and swap them back without changing the structure.",
100: "Decide whether two binary trees are exactly the same in structure and values.",
101: "Decide whether a binary tree is a mirror of itself around its center.",
102: "Return the values of a binary tree level by level, top to bottom, as a list of lists.",
103: "Return the level-order traversal of a binary tree, but alternate the direction of each level (left-to-right, then right-to-left).",
104: "Return the maximum depth of a binary tree — the number of nodes on the longest root-to-leaf path.",
105: "Rebuild a binary tree from its preorder and inorder traversals (all values distinct).",
106: "Rebuild a binary tree from its inorder and postorder traversals (all values distinct).",
108: "Convert a sorted array into a height-balanced binary search tree.",
110: "Decide whether a binary tree is height-balanced: at every node, the two subtree heights differ by at most one.",
112: "Decide whether a binary tree has a root-to-leaf path whose values sum to a given target.",
113: "Return all root-to-leaf paths of a binary tree whose values sum to a given target.",
114: "Flatten a binary tree into a right-leaning 'linked list' in preorder, in place.",
115: "Count how many distinct subsequences of string s equal string t.",
116: "In a perfect binary tree, point every node's next pointer to the node immediately to its right on the same level (or null).",
117: "Same next-pointer wiring, but the tree can be any shape — ideally with O(1) extra space.",
118: "Generate the first numRows rows of Pascal's triangle, where each number is the sum of the two above it.",
119: "Return just the k-th row of Pascal's triangle, ideally using O(k) extra space.",
120: "Given a triangle of numbers, find the minimum path sum from top to bottom, moving to an adjacent index each row down.",
121: "Given daily stock prices, choose one day to buy and a later day to sell to maximize profit (0 if no profit possible).",
122: "With unlimited buy-sell transactions (sell before buying again), return the maximum total profit from a price series.",
123: "Return the maximum profit from a price series using at most two buy-sell transactions.",
124: "Return the maximum sum of any path in a binary tree; a path connects nodes parent-to-child and may not fork (it can pass through a node's two children only at its highest point).",
125: "Decide whether a string is a palindrome when you keep only letters and digits and ignore case.",
126: "Given start and end words and a dictionary, return ALL shortest transformation sequences that change one letter at a time through dictionary words.",
127: "Given start and end words and a dictionary, return the length of the shortest sequence of one-letter changes (each intermediate word must be in the dictionary).",
128: "Given an unsorted array, return the length of the longest run of consecutive integer values, in O(n).",
129: "Each root-to-leaf path spells a number digit by digit; return the sum of all those numbers.",
130: "In a grid of X and O, flip every O region that is completely surrounded by X (regions touching the border survive).",
131: "Split a string into pieces so every piece is a palindrome; return all such partitions.",
132: "Return the minimum number of cuts needed to split a string so every piece is a palindrome.",
133: "Given a reference to a node in a connected undirected graph, return a deep copy of the whole graph.",
134: "Gas stations on a circle each give gas[i] and cost cost[i] to reach the next; return the unique starting station from which you can complete the loop, or -1.",
135: "Children in a line have ratings; give each at least one candy so higher-rated kids get more than their neighbors, minimizing total candy.",
136: "Every number in the array appears exactly twice except one; find that one in O(n) time and O(1) space.",
137: "Every number appears exactly three times except one; find that one in O(n) time and O(1) extra space.",
138: "Deep-copy a linked list whose nodes carry an extra random pointer to any node (or null).",
139: "Decide whether a string can be segmented into a sequence of words from a given dictionary (words reusable).",
140: "Return every sentence you can form by segmenting a string into dictionary words.",
141: "Decide whether a linked list contains a cycle, using O(1) memory.",
142: "If a linked list has a cycle, return the node where the cycle begins; otherwise null — in O(1) memory.",
143: "Reorder a list L0→L1→…→Ln into L0→Ln→L1→Ln-1→… by rewiring nodes in place.",
145: "Return the postorder traversal (left, right, node) of a binary tree's values.",
146: "Design an LRU cache with get and put in O(1) average time; when capacity is exceeded, evict the least recently used key.",
148: "Sort a linked list in O(n log n) time (constant extra space is the follow-up).",
149: "Given points on a plane, return the maximum number of points that lie on one straight line.",
150: "Evaluate an arithmetic expression in Reverse Polish (postfix) notation with + - * / (integer division truncates toward zero).",
151: "Reverse the order of words in a string, cleaning up any extra spaces.",
152: "Find the contiguous subarray with the largest product and return that product.",
153: "A sorted array of distinct values was rotated; find its minimum element in O(log n).",
155: "Design a stack that supports push, pop, top, and retrieving the minimum element, all in O(1).",
160: "Two singly linked lists may merge at some node; return that intersection node (by identity) or null, in O(1) memory.",
162: "Find any peak element (strictly greater than both neighbors) in an array in O(log n).",
164: "Given an unsorted array, return the maximum gap between consecutive elements in sorted order, in linear time.",
167: "In a 1-indexed sorted array, find the two numbers that add to a target and return their indices, using O(1) space.",
168: "Convert a positive integer to its Excel column title (1→A, 26→Z, 27→AA, …).",
171: "Convert an Excel column title to its number (A→1, Z→26, AA→27, …).",
173: "Build an iterator over a BST that returns values in ascending order with next() and hasNext() in O(1) average and O(h) memory.",
174: "A knight walks from the top-left to the princess at bottom-right of a dungeon grid of gains/losses (moving right/down); return the minimum starting health so his health never drops to 0.",
179: "Arrange a list of non-negative integers so their concatenation forms the largest possible number (as a string).",
187: "Return every 10-letter DNA substring that appears more than once in the given sequence.",
188: "Return the maximum stock-trading profit using at most k buy-sell transactions.",
189: "Rotate an array to the right by k steps, in place with O(1) extra space.",
190: "Reverse the bits of a 32-bit unsigned integer.",
191: "Count how many bits are set to 1 in the binary representation of an integer.",
198: "Houses in a row hold money, but robbing two adjacent houses trips the alarm; return the maximum you can rob.",
199: "Return the values you would see looking at a binary tree from the right side, top to bottom.",
200: "Count the islands in a grid of '1' (land) and '0' (water); land connects horizontally and vertically.",
201: "Return the bitwise AND of all numbers in the range [left, right] inclusive.",
202: "A number is 'happy' if repeatedly summing the squares of its digits reaches 1; decide whether n is happy (detect the loop otherwise).",
204: "Count the prime numbers strictly less than n.",
206: "Reverse a singly linked list.",
207: "Given course prerequisite pairs, decide whether all courses can be finished (i.e., the prerequisite graph has no cycle).",
208: "Implement a trie (prefix tree) with insert, exact-word search, and startsWith prefix search.",
209: "Return the length of the shortest contiguous subarray whose sum is at least a given target (0 if none).",
210: "Given prerequisites, return any valid order to take all courses, or an empty list if impossible.",
211: "Design a structure that adds words and searches them where '.' in the query matches any single letter.",
212: "Given a letter grid and a word list, return every word that can be traced through adjacent cells without reusing a cell.",
213: "House Robber on a circle: first and last houses are adjacent; return the maximum loot.",
214: "Return the shortest palindrome obtainable by adding characters in front of the given string.",
215: "Return the k-th largest element in an unsorted array (not the k-th distinct).",
216: "Find all combinations of k distinct digits 1–9 that add up to n.",
218: "Given building rectangles on a skyline, return the key points that outline their combined silhouette.",
219: "Decide whether the array has two equal values at indices at most k apart.",
221: "In a binary matrix, find the area of the largest square containing only 1s.",
222: "Count the nodes of a complete binary tree in better than O(n) time.",
223: "Given two axis-aligned rectangles, return the total area they cover (sum minus overlap).",
224: "Evaluate a string arithmetic expression containing + - parentheses and spaces (a basic calculator).",
225: "Implement a LIFO stack using only queue operations.",
226: "Invert a binary tree: swap the left and right children of every node.",
227: "Evaluate a string expression with + - * / (no parentheses); division truncates toward zero.",
230: "Return the k-th smallest value in a binary search tree.",
231: "Decide whether an integer is a power of two, ideally without loops.",
232: "Implement a FIFO queue using only stack operations, with amortized O(1) per operation.",
233: "Count how many times the digit 1 appears in all numbers from 1 to n.",
234: "Decide whether a linked list is a palindrome in O(n) time and O(1) space.",
235: "In a binary search tree, return the lowest common ancestor of two given nodes.",
236: "In a general binary tree, return the lowest common ancestor of two given nodes.",
238: "Return an array where each position holds the product of every other element, without using division, in O(n).",
239: "A window of size k slides across an array; return the maximum inside the window at each position, in O(n).",
240: "Search a target in a matrix where each row and each column is sorted ascending.",
241: "Given an expression of numbers and operators, return every result obtainable by fully parenthesizing it differently.",
242: "Decide whether one string is an anagram of another.",
249: "Group strings so that strings which become each other by shifting every letter the same amount (wrapping z→a) share a group.",
251: "Implement an iterator that flattens a 2-D vector, exposing next() and hasNext().",
252: "Given meeting intervals, decide whether one person can attend them all (no overlaps).",
253: "Given meeting intervals, return the minimum number of conference rooms needed.",
256: "Paint a row of houses with 3 colors so adjacent houses differ, minimizing total cost given each house's per-color price.",
257: "Return all root-to-leaf paths of a binary tree as strings.",
259: "Count the triplets whose sum is strictly less than a target.",
260: "Exactly two values appear once and everything else twice; find those two in O(n) time and O(1) space.",
261: "Given n nodes and an edge list, decide whether they form a valid tree (connected and acyclic).",
263: "Decide whether a number's only prime factors are 2, 3, and 5.",
264: "Return the n-th 'ugly number' — the n-th positive integer whose prime factors are limited to 2, 3, and 5.",
265: "Paint houses with k colors, adjacent houses differing, minimizing cost — in O(n·k).",
268: "An array holds n distinct numbers from 0..n; return the one number missing from the range.",
269: "Given a list of words sorted by an unknown alphabet, recover a valid letter ordering of that alphabet (or report contradiction).",
271: "Design encode/decode so any list of strings becomes one string and back, safely handling any characters.",
273: "Convert a non-negative integer into its English words ('12345' → 'Twelve Thousand Three Hundred Forty Five').",
274: "Given citation counts, return the researcher's h-index: the largest h with at least h papers cited h or more times.",
275: "Compute the h-index when citations are already sorted ascending, in O(log n).",
278: "Versions after the first bad one are all bad; using an isBadVersion API, find the first bad version with minimal calls.",
279: "Return the fewest perfect square numbers that sum to n.",
281: "Implement an iterator that alternates between two lists, continuing with the longer one when the shorter runs out.",
282: "Insert +, -, or * (or nothing, concatenating digits) between digits of a string so the expression evaluates to a target; return all such expressions.",
283: "Move every 0 in an array to the end while keeping the relative order of the non-zero elements, in place.",
284: "Wrap an existing iterator so it also supports peek() — looking at the next element without consuming it.",
285: "Return the node that comes immediately after a given node in a BST's inorder order (or null).",
286: "In a grid of gates (0), walls, and empty rooms (INF), fill each room with the distance to its nearest gate.",
287: "An array of n+1 integers holds values 1..n, so one value repeats; find it without modifying the array and in O(1) space.",
295: "Design a structure that accepts a stream of numbers and can return the median of everything seen so far at any time.",
297: "Design serialize/deserialize: turn a binary tree into a string and rebuild the identical tree from it.",
300: "Return the length of the longest strictly increasing subsequence of an array (not necessarily contiguous).",
301: "Remove the minimum number of parentheses to make a string valid; return all distinct results.",
303: "Precompute over an immutable array so sumRange(i, j) queries answer in O(1).",
304: "Precompute over an immutable matrix so any rectangle-sum query answers in O(1).",
305: "Land appears in a sea grid one cell at a time; after each addition report the current number of islands.",
307: "Support both updating one element and querying a range sum on an array, each in O(log n).",
308: "Support updating one cell and querying any rectangle sum of a matrix, both efficiently.",
309: "Max stock profit with unlimited transactions, but after each sell you must skip one day (cooldown).",
310: "For a tree given as an edge list, return the root(s) that minimize the tree's height (there are at most two).",
312: "Bursting a balloon earns left·self·right coins (adjacent survivors); pop all balloons in the order that maximizes coins.",
314: "Return a binary tree's values column by column (vertical order), left column to right, top to bottom within a column.",
315: "For each element, count how many elements to its right are smaller than it.",
316: "Remove duplicate letters from a string so each letter appears once and the result is the smallest possible in dictionary order.",
320: "Generate every abbreviation of a word where any non-overlapping runs of letters may be replaced by their lengths.",
322: "Given coin denominations and an amount, return the fewest coins needed to make the amount exactly (or -1).",
323: "Given n nodes and undirected edges, count the connected components.",
324: "Reorder an array into the wiggle pattern a < b > c < d… where every second element is a local maximum.",
325: "Return the length of the longest subarray whose elements sum exactly to k.",
327: "Count the range sums S(i,j) that fall inside [lower, upper], in O(n log n).",
328: "Regroup a linked list so odd-positioned nodes come first, then even-positioned, preserving relative order, in O(1) space.",
332: "Given airline tickets, reconstruct the full itinerary starting at JFK, choosing the lexicographically smallest route that uses every ticket once.",
335: "A path moves counterclockwise with given segment lengths; decide whether it ever crosses itself.",
336: "From a list of unique words, return all index pairs whose concatenation forms a palindrome.",
337: "Houses form a binary tree; robbing two directly linked houses trips the alarm — return the maximum loot.",
338: "For every i from 0 to n, output how many 1-bits i has, ideally in O(n) total.",
340: "Return the length of the longest substring that contains at most k distinct characters.",
341: "Flatten a nested list of integers (integers or further nested lists) into an iterator with next()/hasNext().",
342: "Decide whether an integer is a power of four, without loops.",
344: "Reverse a character array in place.",
345: "Reverse only the vowels of a string, leaving other characters in place.",
346: "Design a class that returns the moving average of the last k values of a stream.",
347: "Return the k most frequent elements of an array.",
348: "Design tic-tac-toe on an n×n board where move(row, col, player) reports a winner in O(1) per move.",
349: "Return the unique values common to two arrays.",
352: "Numbers arrive one at a time; at any point report the stream summarized as a sorted list of disjoint intervals.",
353: "Design the classic Snake game: the snake moves, grows on food, and dies on hitting a wall or itself.",
354: "Count the longest chain of envelopes that nest (each strictly larger in both width and height).",
355: "Design a mini-Twitter: post tweets, follow/unfollow, and fetch the 10 most recent tweets across a user's feed.",
357: "Count numbers from 0 to 10^n with all distinct digits.",
359: "Design a logger that prints a message only if that exact message wasn't printed in the last 10 seconds.",
362: "Design a hit counter that records hits and reports how many occurred in the past 5 minutes.",
366: "Repeatedly remove all leaves of a binary tree, collecting each wave of leaves until the tree is empty.",
369: "A linked list stores a number most-significant digit first; add one to it.",
370: "Apply many (start, end, value) range additions to a zero array and return the final array.",
371: "Compute the sum of two integers without using + or - operators (bit manipulation).",
372: "Compute a^b mod 1337 where b is given as an array of digits (a very large exponent).",
373: "From two sorted arrays, return the k pairs (one element from each) with the smallest sums.",
374: "Guess a number in 1..n using an API that says higher/lower/correct, with as few guesses as possible.",
376: "Return the length of the longest subsequence whose consecutive differences strictly alternate between positive and negative.",
377: "Count sequences of numbers (order matters, reuse allowed) drawn from an array that sum to a target.",
378: "Return the k-th smallest element of a matrix whose rows and columns are sorted ascending.",
379: "Design a phone directory that hands out unused numbers, checks availability, and recycles released numbers.",
380: "Design a set supporting insert, delete, and getRandom (uniform over current elements), each in O(1) average.",
381: "Same O(1) insert/delete/getRandom design, but duplicates are allowed and getRandom must reflect multiplicities.",
382: "Given a linked list of unknown length, return a uniformly random node's value using O(1) extra space (reservoir sampling).",
384: "Design shuffle() returning a uniformly random permutation of an array, and reset() restoring the original.",
389: "String t is s shuffled plus one extra letter; find the added letter.",
392: "Decide whether s is a subsequence of t (s's characters appear in t in order, not necessarily adjacent).",
393: "Validate whether an integer array encodes a legal UTF-8 byte sequence.",
394: "Decode strings like 3[a2[c]] where k[str] means repeat str k times; return the expanded string.",
398: "Given an array with duplicates and a target, return a uniformly random index whose value equals the target.",
399: "Given equations a/b = value, answer division queries between variables (or -1 if unconnected).",
402: "Remove k digits from a number string so the remaining number is the smallest possible.",
406: "People are (height, count-of-taller-or-equal-in-front); reconstruct the original queue order.",
407: "Given a 2-D elevation map, compute the volume of rainwater it can trap (3-D trapping).",
410: "Split an array into k contiguous parts minimizing the largest part-sum.",
416: "Decide whether an array can be split into two subsets with equal sums.",
417: "In a height grid, water flows to lower-or-equal neighbors; return cells from which water can reach both the top-left (Pacific) and bottom-right (Atlantic) borders.",
421: "Return the maximum XOR obtainable from any two numbers in an array, faster than O(n²).",
424: "You may change at most k characters of a string; return the longest substring of one repeated letter achievable.",
430: "Flatten a doubly linked list whose nodes may have child sublists into one level, preserving depth-first order.",
432: "Design a structure with inc(key), dec(key), getMaxKey(), getMinKey() — all O(1).",
433: "Return the minimum number of single-letter gene mutations from start to end, where every intermediate gene must be in the bank.",
435: "Return the minimum number of intervals to remove so the rest don't overlap.",
436: "For each interval, find the interval whose start is the smallest that is ≥ its end (its 'right' interval), or -1.",
437: "Count downward paths in a binary tree whose values sum to a target (paths needn't start at the root or end at leaves).",
438: "Return all start indices in s of substrings that are anagrams of p.",
442: "In an array where values lie in 1..n and appear once or twice, list the values appearing twice, in O(n) time and O(1) extra space.",
443: "Compress a char array in place: runs of a letter become the letter plus the run length (if >1); return the new length.",
444: "Decide whether one sequence is the unique shortest supersequence of a set of subsequences.",
448: "Values lie in 1..n; return every value in that range missing from the array, without extra space beyond the output.",
450: "Delete a value from a BST and return the (still valid) root — handle the two-children case.",
451: "Sort a string's characters by decreasing frequency.",
452: "Balloons occupy x-ranges; an arrow shot at x pops every balloon whose range contains x. Return the fewest arrows to pop all.",
455: "Each child has a greed factor, each cookie a size; maximize the number of children whose cookie is at least their greed.",
456: "Decide whether the array contains indices i<j<k forming the pattern nums[i] < nums[k] < nums[j].",
459: "Decide whether a string equals some substring of itself repeated multiple times.",
460: "Design an LFU cache: evict the least frequently used key (ties: least recently used), all operations O(1).",
472: "From a word list, return every word that is a concatenation of at least two other words from the list.",
473: "Decide whether matchsticks of given lengths can form a square using every stick exactly once.",
477: "Return the sum of Hamming distances (differing bit positions) over all pairs in an array.",
486: "Two players alternately take a number from either end of an array; decide whether player 1 can at least tie with optimal play.",
489: "Control a robot with move/turn/clean APIs in an unknown room; make it clean every reachable cell.",
493: "Count pairs i<j with nums[i] > 2·nums[j].",
494: "Assign + or - to every number so the expression sums to a target; count the ways.",
496: "For each element of a subset array, find its next greater element to the right in the full array (-1 if none).",
501: "Return the most frequent value(s) in a BST with duplicates, ideally O(1) extra space.",
502: "Choose at most k projects, each needing capital and yielding profit, reinvesting profits, to maximize final capital.",
503: "Next greater element in a circular array: for each element, the first larger value scanning forward with wraparound.",
506: "Given scores, assign ranks with Gold/Silver/Bronze medals for the top three and numbers below.",
509: "Return the n-th Fibonacci number.",
515: "Return the largest value in each row (level) of a binary tree.",
516: "Return the length of the longest palindromic subsequence of a string.",
518: "Count the combinations of coin denominations (order irrelevant, unlimited reuse) that make an amount.",
519: "Design flip() returning a uniformly random 0-cell of a matrix (then marking it 1) using few random calls.",
523: "Decide whether the array has a subarray of length ≥ 2 whose sum is a multiple of k.",
525: "Return the length of the longest subarray with an equal number of 0s and 1s.",
526: "Count permutations of 1..n where every position divides its value or vice versa.",
528: "Design pickIndex() returning index i with probability proportional to weights[i].",
530: "Return the minimum absolute difference between any two values in a BST.",
540: "Every element of a sorted array appears exactly twice except one; find it in O(log n).",
541: "Reverse the first k characters of every 2k-sized block of a string.",
542: "For every cell of a binary matrix, compute the distance to the nearest 0.",
543: "Return the diameter of a binary tree — the longest path between any two nodes, in edges.",
545: "Return the boundary of a binary tree counterclockwise: root, left edge, leaves, right edge reversed.",
546: "Remove boxes in groups of equal-colored consecutive boxes, earning k² per group of k; maximize total points.",
547: "Given an adjacency matrix of friendships, count the friend circles (connected components).",
556: "Return the smallest integer larger than n using exactly the same digits (or -1 if none fits in 32 bits).",
560: "Count the contiguous subarrays whose elements sum exactly to k.",
563: "Return a binary tree's total tilt — the sum over nodes of |left subtree sum − right subtree sum|.",
567: "Decide whether s2 contains any permutation of s1 as a substring.",
572: "Decide whether one binary tree appears as a subtree of another.",
583: "Return the minimum deletions (from either string) to make two strings equal.",
604: "Design an iterator over a compressed string like 'a2b3' that yields a, a, b, b, b.",
611: "Count the triplets in an array that could be the side lengths of a triangle.",
621: "Schedule tasks (each identical letter needs a cooldown of n slots between repeats); return the minimum total intervals including idles.",
622: "Design a circular queue with fixed capacity: enqueue, dequeue, front, rear, empty/full checks.",
632: "From k sorted lists, find the smallest range that includes at least one number from every list.",
636: "From start/end log lines of nested function calls, compute each function's exclusive execution time.",
641: "Design a circular double-ended queue with fixed capacity.",
642: "Design search autocomplete: given typed prefixes ('#' ends a sentence), return the top 3 historical sentences by frequency.",
643: "Return the maximum average of any contiguous subarray of length exactly k.",
647: "Count the palindromic substrings of a string (each occurrence counts).",
648: "Replace each word in a sentence with its shortest dictionary root that prefixes it (if any).",
652: "Return one node from every duplicated subtree structure in a binary tree.",
658: "Return the k elements of a sorted array closest to x, in ascending order.",
662: "Return the maximum width of any level of a binary tree, counting the gap positions between the level's endpoints.",
669: "Trim a BST so all values lie within [lo, hi], preserving the structure of what remains.",
673: "Count how many longest increasing subsequences an array has.",
677: "Design a map of string→value where sum(prefix) returns the total of values whose keys start with the prefix.",
678: "With '(' ')' and '*' (wildcard: '(' or ')' or empty), decide whether a string can be a valid parentheses string.",
680: "Decide whether a string can become a palindrome after deleting at most one character.",
684: "A tree gained one extra undirected edge; return the edge whose removal restores a tree (the last such edge in input order).",
685: "A rooted tree gained one extra directed edge; return the edge to remove so a valid rooted tree remains.",
686: "Return the minimum number of times to repeat string a so that b is a substring of it (-1 if never).",
687: "Return the length (in edges) of the longest path in a binary tree where every node on the path has the same value.",
695: "Return the area of the largest island (connected group of 1s) in a binary grid.",
698: "Decide whether an array can be partitioned into k subsets with equal sums.",
699: "Squares drop along a line Tetris-style; after each drop report the current tallest stack height.",
703: "Design a class that accepts streaming numbers and always reports the k-th largest so far.",
704: "Classic binary search: find a target's index in a sorted array, or -1, in O(log n).",
705: "Implement a HashSet from scratch: add, remove, contains — no built-in hash structures.",
706: "Implement a HashMap from scratch: put, get, remove — no built-in hash structures.",
707: "Implement a linked list from scratch: get, addAtHead, addAtTail, addAtIndex, deleteAtIndex.",
708: "Insert a value into a sorted circular linked list (which may be empty or all-equal) keeping it sorted.",
710: "Design pick() returning a uniform random integer in [0, n) that avoids a given blacklist, using few random calls.",
713: "Count the contiguous subarrays (of positive numbers) whose product is strictly less than k.",
714: "Max stock profit with unlimited transactions but a fixed fee paid per transaction.",
715: "Design a structure that adds, removes, and queries coverage of number ranges (interval set with add/remove/query).",
719: "Return the k-th smallest absolute difference among all pairs in an array.",
721: "Merge accounts that share any email; output each person's emails sorted under their name.",
724: "Return the leftmost index where the sum of elements to its left equals the sum to its right (-1 if none).",
729: "Design a calendar that books an event only if it doesn't double-book (overlap any existing event).",
731: "Design a calendar that allows double bookings but rejects any event causing a triple booking.",
732: "Design a calendar where book() returns the maximum overlap count (k-booking) after adding each event.",
733: "Starting from a pixel, recolor its entire connected same-color region with a new color (paint-bucket fill).",
735: "Asteroids move in a line (sign = direction); equal sizes destroy each other, smaller ones explode — return the surviving asteroids.",
737: "Given word-pair similarities (transitive), decide whether two sentences are similar word-by-word.",
739: "For each day's temperature, return how many days you wait until a warmer one (0 if never).",
740: "Taking a value earns its total but deletes all values one less and one greater; maximize points (House Robber over values).",
741: "Walk from (0,0) to (n-1,n-1) and back, collecting cherries (a cell's cherry counts once); return the maximum cherries for both trips combined.",
743: "A signal starts at node k in a weighted directed graph; return the time for all nodes to receive it (-1 if some never do).",
746: "Each stair has a cost; you may start at step 0 or 1 and climb 1–2 steps; reach the top with minimum total cost.",
752: "A 4-wheel lock starts at 0000; each move turns one wheel one notch, avoiding dead-end codes; return the fewest moves to the target.",
759: "Given every employee's sorted working intervals, return the common free-time intervals (finite gaps everyone shares).",
763: "Split a string into as many parts as possible so no letter appears in two parts; return the part sizes.",
767: "Rearrange a string so no two adjacent characters are equal (or return empty if impossible).",
772: "Evaluate an expression string with + - * / and parentheses (full basic calculator).",
773: "On a 2×3 board with tiles 1–5 and a blank, return the minimum slides to reach the solved layout (-1 if unreachable).",
774: "Add k gas stations along existing ones to minimize the maximum distance between adjacent stations; return that minimized distance.",
778: "Water rises over a height grid; return the earliest time you can swim from the top-left to the bottom-right (path cells ≤ time).",
785: "Decide whether a graph is bipartite: its nodes can be 2-colored so every edge joins different colors.",
787: "Return the cheapest flight price from src to dst using at most k intermediate stops (-1 if impossible).",
791: "Reorder string s so its characters follow the relative order given by string 'order' (unlisted chars anywhere).",
796: "Decide whether one string becomes another after some number of left rotations.",
802: "In a directed graph, return the nodes from which every possible walk eventually reaches a terminal node (never enters a cycle).",
827: "You may flip at most one 0 to 1 in a binary grid; return the largest island size achievable.",
836: "Decide whether two axis-aligned rectangles overlap with positive area.",
841: "Rooms hold keys to other rooms; starting with room 0 unlocked, decide whether every room can be visited.",
844: "Compare two strings typed into text editors where '#' means backspace; decide whether they end up equal (O(1) space follow-up).",
846: "Decide whether an array of cards can be split into groups of k consecutive values.",
847: "Return the length of the shortest walk that visits every node of a small graph (revisits allowed) — state = (node, visited-mask).",
852: "An array increases then decreases (a mountain); find the peak index in O(log n).",
853: "Cars at positions drive toward a target at given speeds; faster cars stuck behind slower ones form fleets — count the fleets that arrive.",
857: "Hire exactly k workers, paying everyone the same wage-to-quality ratio and at least their minimum wage; minimize total cost.",
860: "Customers pay for $5 lemonade with $5, $10, or $20 bills; with no starting change, decide whether you can always give correct change.",
862: "Return the length of the shortest (possibly negative-valued) subarray with sum at least k, in O(n) (monotonic deque over prefix sums).",
863: "Return all node values at distance k from a target node in a binary tree (distance runs through parents too).",
864: "In a grid with keys and matching locks, return the fewest steps to collect every key — BFS over (position, keys-held-mask).",
875: "Koko eats bananas at speed k per hour, one pile per hour; find the slowest k that finishes all piles within h hours.",
876: "Return the middle node of a linked list (second middle if even length).",
877: "Two players alternately take a pile from either end of an even-length row (total is odd); decide whether the first player wins with optimal play.",
881: "Each boat carries at most two people under a weight limit; return the fewest boats to carry everyone.",
885: "Walk outward from a start cell in a growing clockwise spiral over an R×C grid; return the coordinates in visit order.",
886: "Split people into two groups given 'dislike' pairs that must be separated; decide whether it's possible (graph bipartiteness).",
895: "Design a stack where pop returns the most frequent element (ties: the one closest to the top).",
900: "Iterate over a run-length encoded sequence: next(n) consumes n elements and returns the last one consumed (-1 past the end).",
901: "Design a class where each new stock price returns its span: how many consecutive prices up to today are ≤ today's.",
904: "With only two baskets, each holding one fruit type, return the longest stretch of trees you can pick (longest subarray with ≤ 2 distinct values).",
905: "Reorder an array so all even numbers come before all odd numbers.",
907: "Return the sum of the minimum of every contiguous subarray, modulo 1e9+7.",
909: "On a boustrophedon-numbered board with snakes and ladders, return the fewest die rolls to reach the last square.",
918: "Find the maximum subarray sum where the subarray may wrap around the end of the circular array.",
921: "Return the minimum number of '(' or ')' insertions to make a parentheses string valid.",
922: "Reorder an array (half even values, half odd) so every even index holds an even number and every odd index an odd number.",
925: "Decide whether 'typed' could result from 'name' with some characters accidentally long-pressed (repeated).",
930: "Count the subarrays of a binary array that sum exactly to a goal.",
931: "Falling through a square matrix choosing down / down-left / down-right each row, minimize the path sum.",
934: "A grid holds exactly two islands; return the fewest 0s to flip to connect them (DFS one island, BFS outward).",
938: "Sum every BST value within [lo, hi], pruning branches outside the range.",
943: "Find the shortest string containing every string of a list as a substring (TSP-style bitmask DP over overlaps).",
947: "Stones sit on grid points; you may remove a stone sharing a row or column with a surviving stone. Maximize removals (n − components).",
952: "Connect numbers that share a common factor > 1; return the size of the largest connected component (union by prime factors).",
959: "Slashes divide each cell of a grid into triangles; count the enclosed regions (union-find on subdivided cells).",
962: "Return the widest pair (i, j) with i < j and nums[i] ≤ nums[j].",
973: "Return the k points closest to the origin.",
974: "Count the subarrays whose sum is divisible by k.",
977: "Given a sorted array (possibly negative), return the squares of its elements in sorted order in O(n).",
981: "Design a key-value store where set stamps a timestamp and get(key, t) returns the value set at the latest time ≤ t.",
986: "Given two sorted lists of disjoint intervals, return all their pairwise intersections.",
987: "Vertical order traversal with strict tie rules: by column, then row, then value.",
994: "Each minute rotten oranges rot their fresh 4-neighbors; return the minutes until no fresh orange remains (-1 if some never rot).",
988: "Each root-to-leaf path (read leaf→root) spells a word of letters a-z; return the lexicographically smallest one.",
990: "Given equations of the forms a==b and a!=b, decide whether any assignment of variables satisfies them all (union equals, then check not-equals).",
992: "Count the subarrays containing exactly k distinct values (atMost(k) − atMost(k−1)).",
995: "Every flip inverts a fixed-length k block; return the minimum flips so the binary array becomes all 1s (-1 if impossible).",
1000: "Merge k adjacent stone piles at a time, paying their total; return the minimum cost to merge everything into one pile (-1 if impossible).",
1004: "You may flip at most k zeros to ones; return the longest run of 1s achievable (longest window with ≤ k zeros).",
1011: "Ship packages in order within d days; find the minimum ship capacity that makes the deadline (binary search on capacity).",
1012: "Count the numbers up to n that contain at least one repeated digit.",
1014: "Maximize values[i] + values[j] + i − j over sightseeing pairs i < j (carry the best values[i]+i so far).",
1019: "For each node of a linked list, report the first strictly larger value that appears later in the list (0 if none).",
1020: "Count the land cells that cannot walk off the grid boundary (flood from the border, count what's left).",
1027: "Return the length of the longest arithmetic subsequence (constant difference) of an array.",
1029: "Fly 2n people to two cities with per-person prices; exactly n per city, minimize total cost (sort by price difference).",
1032: "Design a stream reader that reports, after each character, whether some suffix of the stream matches a dictionary word (suffix trie of reversed words).",
1044: "Return the longest substring that appears at least twice in a string (binary search length + rolling hash).",
1046: "Repeatedly smash the two heaviest stones (equal → both vanish; else the difference survives); return the last stone's weight (0 if none).",
1059: "Decide whether every path from a source node in a directed graph eventually reaches the given destination (no cycles or dead ends elsewhere).",
1071: "Return the largest string that divides both input strings (both are that string repeated).",
1079: "Count the distinct non-empty sequences you can stamp using a set of letter tiles (each tile once).",
1091: "Return the shortest path length from the top-left to bottom-right of a binary grid moving in 8 directions over 0-cells (-1 if blocked).",
1094: "A shuttle with fixed capacity drives one way; given trips (passengers, from, to), decide whether it ever overflows (difference array).",
1095: "Find a target's index in a mountain array (increases then decreases) with a limited number of reads (three binary searches).",
1101: "Friendship events arrive with timestamps; return the earliest time everyone is (transitively) connected (union-find until one component).",
1109: "Apply flight bookings (first, last, seats) as range additions and return seats per flight (difference array).",
1110: "Delete the given values from a binary tree; return the roots of the resulting forest.",
1122: "Sort arr1 so its elements follow the order given by arr2; leftovers go at the end ascending (counting sort).",
1123: "Return the lowest common ancestor of all the deepest leaves of a binary tree.",
1135: "Connect n cities at minimum total cost given possible connections (minimum spanning tree; -1 if disconnected).",
1136: "Courses have prerequisite pairs; return the minimum number of semesters to finish all (longest path in DAG; -1 on cycle).",
1137: "Tribonacci: T(n) = T(n-1) + T(n-2) + T(n-3) with T(0..2) = 0,1,1; return T(n).",
1140: "Stone Game II: each turn a player takes the first X piles (1 ≤ X ≤ 2M), M becomes max(M, X); maximize player 1's stones.",
1143: "Return the length of the longest subsequence common to two strings.",
1146: "Design an array supporting set, snap (snapshot), and get(index, snap_id) — value at a past snapshot (per-index history + bisect).",
1161: "Return the level of a binary tree with the maximum sum of node values (smallest such level on ties).",
1162: "Return the largest distance from any water cell to its nearest land cell (multi-source BFS from all land; -1 if degenerate).",
1167: "Connect sticks by paying the sum of the two joined each time; return the minimum total cost (always join the two smallest — heap).",
1187: "Make arr1 strictly increasing by replacing elements with elements of arr2; return the minimum replacements (-1 if impossible) (DP + binary search).",
1192: "Return every 'critical connection' of a network — edges whose removal disconnects it (bridge-finding DFS).",
1202: "You may swap characters at given index pairs any number of times; return the lexicographically smallest string (sort within union-find components).",
1233: "Remove every folder that lies inside another folder in the list; return what remains (sort, or trie of path segments).",
1248: "Count the subarrays containing exactly k odd numbers ('nice' subarrays).",
1249: "Delete the minimum number of parentheses so the string becomes valid; return one result.",
1254: "Count the islands of 0s that never touch the grid border ('closed' islands).",
1277: "Count the square submatrices of all 1s in a binary matrix (DP: largest square ending at each cell, summed).",
1283: "Find the smallest divisor d so that the sum of ceil(x/d) over the array stays within a threshold (binary search on d).",
1288: "Remove intervals fully covered by another interval; return how many remain (sort by start asc, end desc).",
1293: "Shortest path from corner to corner of a grid when you may remove up to k obstacles (BFS over (cell, removals-left)).",
1310: "Answer XOR-of-range queries on an array using prefix XORs.",
1312: "Return the minimum insertions to make a string a palindrome (n − longest palindromic subsequence).",
1316: "Count the distinct substrings that are some string written twice in a row (echo substrings; rolling hash).",
1318: "Return the minimum bit flips in a and/or b so that a OR b equals c (per-bit case analysis).",
1319: "Given network cables between computers, return the minimum re-plugs to connect everything (components − 1 if enough cables; else -1).",
1334: "Find the city with the fewest reachable neighbors within a distance threshold (Floyd-Warshall; largest id on ties).",
1348: "Design tweet-frequency queries: record tweets by time and answer per-minute/hour/day counts in a time range.",
1349: "Seat the maximum number of students in a broken-seat classroom so no one can cheat off a neighbor (row-by-row bitmask DP).",
1352: "Design a stream where add appends a number and getProduct(k) returns the product of the last k (prefix products, reset on zero).",
1368: "Grid cells point a direction; walking with the arrows is free, changing a cell's arrow costs 1. Reach the bottom-right at minimum cost (0-1 BFS / Dijkstra).",
1372: "Return the longest zigzag path in a binary tree (alternate left/right child steps).",
1373: "Return the maximum sum over all subtrees that are valid BSTs (postorder returning (min, max, sum, isBST)).",
1381: "Design a stack with push, pop, and increment(k, val) — add val to the bottom k elements — all O(1) (lazy increments).",
1383: "Pick at most k engineers maximizing (sum of speeds) × (minimum efficiency) — sort by efficiency, min-heap of speeds.",
1392: "Return the longest proper prefix of a string that is also its suffix (the KMP failure function's last value).",
1396: "Design a metro card system: record checkins/checkouts and answer average travel time between station pairs.",
1429: "Design a stream that returns the first number that has appeared exactly once so far (queue + counts, lazy cleanup).",
1434: "Count the ways to assign n people distinct hats from their preference lists (bitmask DP over people, iterate hats).",
1438: "Return the longest subarray where max − min ≤ limit (window + two monotonic deques).",
1448: "Count 'good' nodes — nodes whose value is ≥ every value on the path from the root to them.",
1462: "Given course prerequisites, answer queries 'is a a prerequisite of b?' (transitive closure via Floyd or BFS per node).",
1463: "Two robots start at the top corners of a cherry grid and move down; maximize total cherries (DP over (row, col1, col2)).",
1466: "Roads are directed; return the minimum edges to flip so every city can reach city 0 (treat edges as bidirectional, count wrong-way on DFS from 0).",
1472: "Design browser history: visit clears forward history; back(steps) and forward(steps) move along it.",
1473: "Paint remaining unpainted houses with m colors to form exactly 'target' color blocks at minimum cost (DP over house, color, blocks).",
1475: "For each shop price, subtract the next smaller-or-equal price to its right (monotonic stack discount).",
1480: "Return the running sum of an array (prefix sums, the warm-up version).",
1482: "Make m bouquets needing k adjacent bloomed flowers each; find the earliest day possible (binary search over days).",
1489: "Classify each MST edge as critical (in every MST) or pseudo-critical (in some MST) — Kruskal with forced inclusion/exclusion.",
1493: "Delete exactly one element; return the longest subarray of 1s afterwards (window with ≤ 1 zero, length − 1).",
1494: "Finish all courses with prerequisites taking at most k per semester; return the minimum semesters (bitmask DP over completed sets).",
1514: "Return the most probable path between two nodes when each edge has a success probability (Dijkstra maximizing product).",
1539: "Return the k-th positive integer missing from a sorted array (binary search on missing-count = arr[i] − i − 1).",
1547: "Cut a stick at given positions; each cut costs the current segment's length. Order the cuts to minimize total cost (interval DP).",
1552: "Place m balls in baskets at given positions maximizing the minimum distance between any two balls (binary search the distance).",
1584: "Connect all points at minimum total Manhattan-distance cost (MST — Prim's fits dense complete graphs).",
1631: "Find a path from corner to corner minimizing the maximum height difference along it (binary search + BFS, or Dijkstra on effort).",
1642: "Climb buildings using b bricks and l ladders (ladders cover any jump, bricks the difference); go as far as possible (heap of jumps: ladders for the largest).",
1655: "Distribute an inventory of repeated numbers to customers, each demanding a quantity of one value; decide feasibility (bitmask over orders per value).",
1658: "Remove elements from the ends summing exactly x; minimize removals (longest middle window with sum total − x).",
1671: "Return the minimum removals so the array becomes a strict mountain (LIS from the left + LDS from the right, combined at peaks).",
1673: "Return the most competitive (lexicographically smallest) subsequence of length k (monotonic stack with a removal budget).",
1696: "Jump forward up to k steps, scoring each landing value; maximize the score reaching the end (DP + sliding-window max).",
1707: "For each query (x, m), return the maximum x XOR element among array values ≤ m (offline sort + bit trie).",
1756: "Design a queue where fetching the k-th item also moves it to the back (most recently used).",
1760: "Split balls in bags with limited operations to minimize the largest bag (binary search the answer).",
1765: "Water cells are height 0; assign land heights so neighbors differ by at most 1 and the peak is maximized (multi-source BFS from water).",
1792: "Add extra students to classes to maximize average pass ratio; each student goes where the ratio gains most (heap by marginal gain).",
1804: "A trie that also counts how many inserted words equal, and how many start with, a query string.",
1825: "Design MKAverage: over the last m stream values, drop the k smallest and k largest and report the mean of the rest (three balanced buckets).",
1834: "Simulate a single-threaded CPU choosing, among available tasks, the shortest processing time first; return execution order.",
1838: "Raising elements costs 1 per unit; with budget k, return the highest achievable frequency of any value (sort + window whose raise cost ≤ k).",
1845: "Design a seat manager handing out the smallest free seat number and accepting returns (min-heap of freed seats).",
1851: "For each query point, return the length of the smallest interval containing it (-1 if none) — offline sort + heap.",
1854: "Given birth/death years, return the earliest year with the most people alive (difference array over years).",
1857: "Return the largest count of a single node color along any path in a DAG (-1 if it has a cycle) — topological order + per-color DP.",
1863: "Return the sum of XOR totals over every subset of the array (each bit present in half the subsets: OR × 2^(n-1)).",
1882: "Assign tasks to servers: free servers by (weight, index), busy ones by release time; simulate with two heaps.",
1899: "You may merge triplets element-wise by max; decide whether the exact target triplet is formable (use only triplets ≤ target everywhere).",
1905: "Count islands of grid2 whose every cell is also land in grid1 (DFS with an AND flag).",
1942: "Friends arrive/leave; each takes the smallest free chair — return the chair number the targetFriend gets (two heaps over events).",
1944: "For each person in a queue, count how many people to their right they can see (monotonic decreasing stack).",
1963: "Return the minimum swaps to balance a string of n/2 '[' and n/2 ']' (track unmatched closers; ceil(unmatched/2)).",
1976: "Count the distinct shortest paths from node 0 to node n-1 in a weighted graph, mod 1e9+7 (Dijkstra + path counting).",
2013: "Design a structure that adds points and counts axis-aligned squares completable with a query point (dict of point counts, iterate diagonal partners).",
2018: "Decide whether a word can be placed in a crossword row/column slot, in either direction, respecting blocked cells and existing letters.",
2034: "A stream of (timestamp, price) updates (corrections allowed); report latest, maximum, and minimum current prices (dict + lazy heaps).",
2045: "Return the SECOND minimum time to travel from node 1 to n when traffic lights alternate green/red at every node (BFS tracking two best arrival times).",
2050: "Courses with durations and prerequisites, unlimited parallelism; return the minimum total time (longest weighted path in DAG).",
2064: "Distribute product quantities to n stores, one product type per store, minimizing the largest store load (binary search the answer).",
2095: "Delete the middle node of a linked list (fast/slow pointers) and return the head.",
2096: "Return the shortest walking directions (U for up, L/R for down-steps) between two nodes of a binary tree (LCA + path diff).",
2097: "Arrange given (start, end) pairs so each pair begins where the previous one ended, using all pairs (Eulerian path over values).",
2101: "Detonating a bomb triggers every bomb within its radius; return the most bombs one detonation can set off (directed reach, DFS from each).",
2104: "Return the sum over all subarrays of (max − min) — two monotonic-stack passes (sum of maxes minus sum of mins).",
2115: "Recipes need ingredients (which may be other recipes); given supplies, return every cookable recipe (topological sort).",
2185: "Count the words in a list that start with a given prefix.",
2203: "Find the minimum-weight subgraph where two sources can both reach a destination (three Dijkstras: from src1, src2, and reversed from dest).",
2226: "Split candy piles into sub-piles (no merging) so k children get equal amounts; maximize that amount (binary search).",
2290: "Reach the bottom-right of a grid removing as few obstacles as possible (0-1 BFS: obstacle = cost 1 edge).",
2296: "Design a text editor with cursor: addText, deleteText, cursorLeft, cursorRight — two stacks around the cursor.",
2326: "Fill an m×n matrix in spiral order with a linked list's values (-1 padding).",
2336: "Design a set pre-filled with all positive integers: popSmallest and addBack(num) (heap + set for returned numbers, counter for the frontier).",
2337: "'L' pieces may only move left and 'R' only right through blanks; decide whether the start string can reach the target (matched pieces with compatible positions).",
2360: "Every node has at most one outgoing edge; return the length of the longest cycle (timestamped walk per component).",
2392: "Build a k×k matrix containing 1..k² obeying row-order and column-order constraints (two topological sorts).",
2402: "Meetings queue for n rooms, taking the lowest free room (or waiting for the earliest); return the room that hosts the most meetings (two heaps).",
2406: "Partition intervals into the fewest groups so no group has overlaps (sweep line peak = answer).",
2407: "Longest strictly increasing subsequence where adjacent chosen values differ by at most k (DP over values with a max-segment-tree).",
2416: "For every word, sum the counts of all its prefixes across the list (trie with per-node counters).",
2458: "For each query, return the tree's height after removing the subtree rooted at that node (precompute per-depth top-two heights).",
2461: "Return the maximum sum among subarrays of length k whose elements are all distinct (window + counts).",
2487: "Remove every node that has a strictly greater value somewhere to its right; return the list (reverse + running max, or monotonic stack).",
2516: "Take characters only from the two ends so you collect at least k of each of a, b, c; minimize characters taken (longest valid middle window).",
2558: "Each second take the richest pile and replace it with floor(sqrt) of itself, k times; return the remaining total (max-heap).",
2577: "Move through a grid where cell (r,c) opens at time grid[r][c]; waiting allowed by stepping back and forth; return the earliest arrival (Dijkstra, parity fix).",
2698: "Sum every i in 1..n whose square's decimal digits can be split into parts summing to i (digit-partition backtracking).",
2707: "Given a string and a dictionary, minimize the characters left uncovered when you carve out non-overlapping dictionary words (DP + trie).",
2719: "Count integers in [num1, num2] whose digit sum lies in [min_sum, max_sum], mod 1e9+7 (digit DP).",
2762: "Count subarrays where max − min ≤ 2 ('continuous' subarrays) — window with monotonic deques.",
2779: "Each element may move by ±k once; return the largest possible count of equal elements (overlapping-interval sweep / sort + window).",
2812: "Return the safest path corner to corner: maximize the minimum distance to any thief (multi-source BFS for danger + binary search or Dijkstra).",
2938: "Return the minimum adjacent swaps to move every '1' (black ball) to the right of every '0' (each 1 crosses the 0s after it; sum zeros-passed).",
2981: "Return the longest single-letter substring length that appears at least three times (count runs per letter; -1 if none).",
2985: "Stream of orders: report the compressed mean of the last k order values (running window sum).",
3008: "Find indices where pattern a occurs within distance k of an occurrence of pattern b (KMP both, two-pointer over match lists).",
3026: "Return the maximum subarray sum where the subarray's endpoints differ by exactly k in value (prefix-min per needed value, dict).",
3254: "For every window of size k, output its 'power': the last element if the window is consecutive ascending, else -1 (run lengths of consecutiveness).",
3318: "For each k-long window, sum the top x values counting by frequency (ties by value) — the 'x-sum' (two multisets / sorted containers).",
3346: "With numOperations single-use adjustments of at most ±k, maximize how many elements can be made equal (sweep candidate targets with prefix counts).",
3347: "The harder variant of 3346 with larger bounds: same target-sweep idea with efficient counting (sorted array + binary search).",
}
