# Per-problem content.
# INSIGHTS: lc-number → one-line key idea (shown on the light version of the page).
# DEEP: lc-number (or (pattern_index, lc) for pattern-specific pages) → full HTML body.
#       Deepening sessions move problems from INSIGHTS-only into DEEP. See MASTER_PROMPT.md.

DEEP = {}

# Per-pattern deep tutorials live in their own content_deep_pNN.py files and are
# merged here keyed by (pattern_index, lc) so a problem that appears under several
# patterns only shows its deep tutorial on the pattern it was written for.
import content_deep_p01
DEEP.update({(1, lc): body for lc, body in content_deep_p01.DEEP.items()})
import content_deep_p02
DEEP.update({(2, lc): body for lc, body in content_deep_p02.DEEP.items()})
import content_deep_p03
DEEP.update({(3, lc): body for lc, body in content_deep_p03.DEEP.items()})
import content_deep_p04
DEEP.update({(4, lc): body for lc, body in content_deep_p04.DEEP.items()})
import content_deep_p05
DEEP.update({(5, lc): body for lc, body in content_deep_p05.DEEP.items()})
import content_deep_p06
DEEP.update({(6, lc): body for lc, body in content_deep_p06.DEEP.items()})

INSIGHTS = {
1:   "Store each value's index in a dict as you scan; for each x, ask in O(1) whether target − x was already seen.",
11:  "Start at both ends; the shorter wall limits the area, so moving the shorter pointer inward is the only move that can help.",
15:  "Sort, fix one number, then run converging two-pointers for the remaining pair; skip duplicates at every level.",
26:  "Write-pointer: copy each element forward only when it differs from the last kept one.",
27:  "Write-pointer: keep an element by writing it at the write index; the front of the array becomes the answer.",
42:  "Water above a bar = min(max height to its left, max to its right) − bar; two pointers carry those maxima inward.",
125: "Two pointers from the ends, skipping non-alphanumerics; compare lowercased characters.",
167: "Sorted input makes converging pointers exact: sum too small → move left up; too big → move right down.",
283: "Write-pointer compacts the non-zeros in order, then fill the tail with zeros.",
344: "Converging pointers swapping in place until they cross.",
5:   "Every palindrome has a center: expand around all 2n−1 centers, tracking the longest.",
48:  "Rotate 90° = transpose (swap across the diagonal) then reverse each row.",
54:  "Maintain four boundaries; walk top→right→bottom→left, shrinking after each side; re-check bounds mid-loop.",
73:  "Use row 0 and column 0 as the marker arrays for 'this row/col must be zeroed' — O(1) extra space.",
238: "answer[i] = (product of everything left of i) × (product right of i); two sweeps, no division.",
2:   "Walk both lists digit by digit carrying the carry; a dummy head collects result nodes.",
19:  "Advance a lead pointer n steps first; then move lead and lag together — lag lands just before the target.",
21:  "Dummy head + one pointer per list; splice the smaller node each step; append the leftover tail.",
23:  "A min-heap of each list's current head pops the global smallest in O(log k) per node.",
25:  "Reverse in k-sized chunks: count k nodes, reverse them, reconnect; leave a short tail untouched.",
83:  "One pass: if cur.val == cur.next.val, bypass next.",
92:  "Walk to the node before position left, then head-insert each following node until right.",
138: "Interleave copies with originals (A→A'→B→B'), wire random pointers via node.random.next, then unzip.",
141: "Fast moves 2, slow moves 1: they meet iff a cycle exists — no extra memory.",
142: "After fast and slow meet, restart one pointer at head; moving both by 1 they meet at the cycle entrance.",
143: "Find middle (fast/slow) + reverse second half + merge alternately: three primitives glued.",
160: "Walk two pointers, each switching to the other list at its end — they equalize path lengths and meet at the intersection.",
206: "Walk once, flipping each .next to point backwards; keep prev/cur, save next before overwriting.",
234: "Middle + reverse second half + compare halves = O(1) space palindrome check.",
876: "Fast/slow: when fast hits the end, slow is the middle.",
94:  "Inorder: left, node, right — recursively or with an explicit stack pushing left spines.",
98:  "Pass down (lo, hi) bounds; every node must fit its inherited range — child-only checks miss grandparent violations.",
100: "Two trees are the same iff roots match and both subtree pairs are the same (recursion).",
101: "Mirror check: compare left.left with right.right and left.right with right.left.",
102: "BFS; freeze len(queue) each round so each iteration processes exactly one level.",
103: "Level-order BFS; reverse alternate levels (or append to a deque from alternating ends).",
104: "Height = 1 + max(height(left), height(right)); None returns 0.",
105: "Preorder's first element is the root; find it in inorder to split left/right subtrees; recurse with index math.",
110: "Postorder returning height, or −1 as a 'not balanced' poison value that bubbles up.",
124: "At each node: best downward gain per child (clamped at 0); path through node = val + leftGain + rightGain updates the global.",
199: "BFS levels, take the last node of each level (or DFS right-first, first node per depth).",
226: "Swap children at every node — one-line recursion.",
230: "Inorder traversal of a BST yields sorted order; stop at the k-th visit.",
235: "Walk from root: both values smaller → go left; both bigger → go right; else this node splits them = LCA.",
236: "Postorder: a node returning non-null from both sides is the LCA; otherwise forward the non-null side.",
297: "Preorder with explicit null markers serializes uniquely; deserialize by consuming tokens with an iterator.",
543: "Diameter through a node = leftHeight + rightHeight; return 1 + max to the parent, update global with the sum.",
572: "At each node of s, check isSameTree(node, t); or serialize both with null markers and substring-match.",
3:   "Variable window + last-seen map: on repeat, jump left past the previous occurrence.",
76:  "Variable window + need/have counts: expand right until valid, then shrink left while still valid, tracking the min.",
209: "Grow right adding to sum; while sum ≥ target, record length and shrink left — shortest valid window.",
239: "Monotonic deque of indices, front = window max; pop smaller from the back, expire out-of-window from the front.",
424: "Window is valid while (size − count of most frequent char) ≤ k; max count never needs to decrease.",
438: "Fixed window of len(p): maintain a count diff and a 'matched letters' counter for O(1) checks per slide.",
567: "Same as 438 but return true on the first fully matched window.",
20:  "Push openers; each closer must match the popped opener; valid iff stack ends empty.",
22:  "Backtrack building the string: may add '(' while any remain; may add ')' only if it won't outnumber '('.",
32:  "Stack of indices with a base marker: push '(' indices, pop on ')', longest = i − stack[-1].",
84:  "Monotonic increasing stack: when a shorter bar arrives, pop and settle each taller bar's max rectangle (its width spans between stack neighbors).",
150: "Stack of operands; on operator, pop two, apply, push result (mind operand order and truncation toward zero).",
155: "Store (value, min_so_far) pairs so getMin is a peek at the top.",
224: "Stack saves (result, sign) at each '('; on ')' pop and combine.",
232: "Two stacks: amortized O(1) — dump the in-stack into the out-stack only when the out-stack is empty.",
394: "Stack of (repeat_count, string_so_far); on ']' pop and append repeated segment.",
496: "Monotonic decreasing stack over nums2; when x arrives, everything popped has x as its next greater.",
739: "Monotonic stack of indices of unresolved (colder) days; a warmer day resolves them; answer is the index distance.",
215: "Min-heap capped at size k (O(n log k)), or quickselect for O(n) average.",
295: "Two heaps: max-heap lower half, min-heap upper half, rebalanced so sizes differ ≤ 1; median from the tops.",
347: "Count with a dict, then heapq.nlargest(k, counts, key=count) — or bucket-by-frequency for O(n).",
373: "Heap seeded with (a[i]+b[0], i, 0); popping (i,j) pushes (i, j+1) — a k-way merge over rows.",
621: "Most frequent task dominates: slots = (max_count−1)×(n+1) + tasks_tying_max; answer = max(that, len(tasks)).",
703: "Keep a min-heap of the k largest seen; its root IS the k-th largest at all times.",
33:  "One half of a rotated array is always sorted — check which, decide if target lies in it, discard the other.",
34:  "Two lower-bound searches: first index ≥ target, and first index ≥ target+1, minus one.",
35:  "Textbook lower bound: smallest index where nums[i] ≥ target.",
69:  "Binary search the largest x with x² ≤ n.",
74:  "Treat the matrix as one sorted array: index → (i // cols, i % cols).",
81:  "Like 33, but equal endpoints hide which half is sorted — shrink both ends by one when nums[lo]==nums[mid]==nums[hi].",
153: "Compare mid with right end: mid > right means the minimum is right of mid; else it's mid or left.",
162: "If nums[mid] < nums[mid+1] a peak lies right; else left — slope-following always finds one.",
278: "Lower bound over the isBadVersion predicate — first True.",
704: "The canonical binary search — practice the lo < hi lower-bound shape until automatic.",
875: "Binary search the eating speed: feasible(k) is monotone — hours(k) = Σ ceil(pile/k) ≤ h.",
1011:"Binary search the ship capacity between max(weights) and sum(weights); feasibility = days needed ≤ D.",
4:   "Partition both arrays so left halves' sizes sum to half; binary search the cut in the shorter array.",
127: "BFS over words where neighbors differ by one letter; generate neighbors by mutating 26 letters per position.",
130: "Invert the problem: DFS from border O's marks the safe ones; flip everything unmarked.",
133: "BFS/DFS with a dict old-node → clone; create the clone on first sight, wire neighbors as you traverse.",
200: "Scan all cells; each unvisited land cell starts one DFS/BFS flood — count the starts.",
207: "Cycle detection: Kahn's topological sort finishes all nodes iff no cycle.",
210: "Kahn's algorithm; the pop order IS a valid course order.",
417: "Reverse-flow: DFS from each ocean's border inland (uphill); answer = cells reached by both.",
684: "Union-Find: the first edge whose endpoints are already connected is the redundant one.",
695: "Island DFS returning its size; track the max.",
733: "Flood fill = DFS/BFS recoloring from the start pixel (guard: new color == old color → no-op).",
994: "Multi-source BFS from all rotten oranges at once; rounds = minutes; leftover fresh ⇒ −1.",
45:  "Greedy BFS-like layers: within the current reach, compute the farthest next reach; each layer = one jump.",
55:  "Sweep tracking the farthest reachable index; if i exceeds it, you're stuck.",
134: "If total gas ≥ total cost an answer exists; restart the candidate at i+1 whenever the running tank goes negative.",
435: "Sort by end time; greedily keep intervals that start after the last kept end; removals = rest.",
452: "Sort by end; shoot at the current balloon's end; every balloon starting before that arrow's x is popped free.",
763: "Record each letter's last index; extend the current partition to the max last-index seen; cut when i reaches it.",
846: "Sort; repeatedly take the smallest card and greedily grab its consecutive run (Counter bookkeeping).",
860: "Always break a $20 with 10+5 rather than 5+5+5 — keep flexible small bills.",
17:  "Backtrack over digit → letters mapping, one digit per depth.",
39:  "Combination backtracking passing i (not i+1) — reuse allowed; prune when remaining < candidate.",
40:  "Sort; skip equal siblings at the same depth (i > start and c[i]==c[i−1]) to kill duplicate combinations.",
46:  "Permutation backtracking with a used set (or in-place swapping).",
51:  "Backtrack row by row; track attacked columns and both diagonals (r−c, r+c) in sets.",
78:  "At each element: branch include/exclude; or iterate — every existing subset spawns a copy plus the new element.",
79:  "DFS from each cell matching the word one char per step; mark the cell in-path, unmark on backtrack.",
90:  "Sort; standard subset backtracking, skipping equal siblings at the same tree level.",
131: "Backtrack over cut positions; only recurse when the prefix is a palindrome (precompute or check on the fly).",
212: "Build a trie of all words; DFS the grid walking the trie in lockstep, pruning dead branches — finds all words in one search.",
216: "Combination backtracking with both a count limit and a sum target; prune aggressively.",
10:  "2-D DP over prefixes; '*' either matches empty (drop pattern pair) or consumes a char when preceding element matches.",
53:  "Kadane: best ending here = x + max(0, best ending at previous); global max of those.",
62:  "dp[r][c] = dp[r−1][c] + dp[r][c−1]; or closed form C(m+n−2, m−1).",
70:  "Fibonacci in disguise: ways(n) = ways(n−1) + ways(n−2); two rolling variables suffice.",
72:  "dp[i][j] = edit distance of prefixes; match is free diagonal, else 1 + min(insert, delete, replace).",
91:  "dp over positions: one-digit decode if 1-9, two-digit if 10-26; zeros make branches die.",
121: "Track min price so far; best profit = max over days of (price − minSoFar).",
139: "dp[i] = any dp[j] where s[j:i] is in the dict; dp[0] = True.",
152: "Track BOTH max and min product ending here (negatives flip them); swap on negative x.",
198: "dp[i] = max(dp[i−1], dp[i−2] + nums[i]) — rob or skip; two variables.",
213: "Circular = max(rob houses 0..n−2, rob houses 1..n−1) — two linear passes.",
221: "dp[r][c] = side of largest square ending at (r,c) = 1 + min(top, left, diag) when cell is 1.",
300: "Patience: tails[k] = smallest tail of an increasing subsequence of length k+1; bisect each element in — O(n log n).",
322: "Unbounded knapsack: dp[amount] = 1 + min(dp[amount − coin]) over coins; 0 base, inf = unreachable.",
416: "Subset-sum to total/2: 0/1 knapsack over a boolean dp, capacity loop descending.",
518: "Count combinations: loop COINS outer, amounts inner ascending — order matters vs 377 (permutations).",
1143:"dp[i][j] = LCS of prefixes: match → 1 + diag; else max(skip either).",
14:  "Sort helps: only the first and last string can differ most — common prefix of those two.",
28:  "Naive windows fine here, or KMP for the O(n+m) answer.",
49:  "Group by canonical key: tuple(sorted(word)) or the 26-count tuple.",
151: "split() handles all whitespace; reverse the word list; join with single spaces.",
242: "Counter(s) == Counter(t) — or a 26-slot array diff.",
8:   "State machine: skip spaces, optional sign, consume digits, clamp to 32-bit range.",
13:  "Sum symbol values; subtract twice when a smaller symbol precedes a larger (IV = −1 + 5 + ...).",
136: "XOR everything: pairs cancel, the singleton survives.",
137: "Count each bit position mod 3; the surviving bits form the answer.",
190: "Build the result bit by bit: shift result left, or-in n's last bit, shift n right — 32 rounds.",
191: "n &= n−1 clears the lowest set bit; count iterations.",
268: "XOR all indices 0..n and all values — everything pairs off except the missing number.",
338: "dp: bits(i) = bits(i >> 1) + (i & 1).",
371: "Sum without +: XOR is the carry-less sum, AND<<1 is the carry; loop until carry dies (mask for 32-bit in Python).",
146: "Dict → doubly-linked-list nodes: dict finds, list orders; move-to-front on every access, evict tail.",
208: "Nested dicts, one level per character, with an end-of-word flag.",
211: "Trie search where '.' recursively tries every child.",
225: "Simulate a stack with one queue by rotating after each push.",
284: "Buffer one element ahead; peek serves the buffer, next consumes it.",
341: "Stack of (list, index) frames; hasNext digs to the next real element.",
355: "Per-user tweet lists + heap-merge of followees' recent tweets.",
380: "List + dict of value→index; delete = swap victim with last, pop — O(1) everything.",
528: "Prefix sums of weights + bisect on a uniform random in [0, total).",
707: "Design: singly linked list with a dummy head and a size counter.",
303: "Precompute prefix sums; range sum = prefix[j+1] − prefix[i].",
304: "2-D prefix with inclusion–exclusion: sum = P[r2+1][c2+1] − P[r1][c2+1] − P[r2+1][c1] + P[r1][c1].",
523: "Prefix sums mod k in a dict: equal remainders ⇒ the gap between them is divisible by k (watch index distance ≥ 2).",
525: "Map 0→−1; equal running sums bracket a balanced subarray; store first index of each sum.",
560: "seen[0]=1; each step count += seen[cur−k], then record cur.",
307: "Fenwick/segment tree: point update and range query both O(log n).",
315: "Walk right-to-left, BIT over value ranks: 'how many smaller already inserted?'",
56:  "Sort by start; extend the last merged block while starts overlap its end.",
57:  "Three phases: copy intervals ending before, merge all overlapping into one, copy the rest.",
252: "Sort; any start before the previous end ⇒ can't attend.",
253: "Sweep line (+1/−1 events) peak, or min-heap of end times sized = rooms.",
986: "Two pointers over both sorted lists; intersect [max starts, min ends]; advance whichever ends first.",
7:   "Peel digits with divmod, build reversed; check the 32-bit clamp before returning.",
9:   "Reverse only half the number and compare halves — no string needed.",
50:  "Fast power: square the base, halve the exponent; negative n → invert.",
66:  "Add from the right; carry propagates; all-nines grows the array.",
202: "Cycle detection on the digit-square-sum sequence (set or Floyd).",
204: "Sieve of Eratosthenes, marking from i².",
233: "Digit DP / per-position counting of 1s contributed by each digit place.",
263: "Repeatedly divide out 2, 3, 5; ugly iff 1 remains.",
1071:"gcd of the strings: if s+t == t+s, the answer is the prefix of length gcd(len s, len t).",
382: "Reservoir sampling: keep node i with probability 1/i while walking the list.",
384: "Fisher-Yates: swap i with a uniform j ≤ i, from the back.",
398: "Reservoir sampling among indices equal to the target.",
470: "Rejection sampling: build uniform 1..49 from two rand7 calls, reject > 40, mod down to 1..10.",
}
