# -*- coding: utf-8 -*-
import json, sys, io, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from part1 import L1
from part2 import L2
from part3 import C

ROOT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'System_Design_Tutorial')
t = open(os.path.join(ROOT, 'topics.js'), encoding='utf-8').read()
topics = json.loads(t[t.index('['):t.rindex(']')+1])

files, anchors = set(), set()
for sec in topics:
    for sub in sec.get('subsections', []):
        files.add(sub['file'])
        for c in sub['concepts']:
            anchors.add(sub['id'] + '/' + c['anchor'])

lessons = {}
lessons.update(L1); lessons.update(L2)

bad_files = [k for k in lessons if k not in files]
missing   = [f for f in files if f not in lessons]
bad_anchor= [k for k in C if k not in anchors]
print("lesson keys:", len(lessons), "| not a real lesson file:", bad_files)
print("lessons with no entry:", missing)
print("concept keys:", len(C), "| not a real concept:", bad_anchor)

urls = []
for d in list(lessons.values()) + list(C.values()):
    for v in d['videos']: urls.append('https://www.youtube.com/watch?v=' + v[0])
    for doc in d['docs']: urls.append(doc[1])
print("total links:", len(urls), "| distinct:", len(set(urls)))
vids = sorted({v[0] for d in list(lessons.values()) + list(C.values()) for v in d['videos']})
print("distinct videos:", len(vids))
open('video_ids.txt','w').write("\n".join(vids))
docs = sorted({doc[1] for d in list(lessons.values()) + list(C.values()) for doc in d['docs']})
open('doc_urls.txt','w').write("\n".join(docs))
print("distinct docs:", len(docs))

if bad_files or bad_anchor or missing:
    sys.exit("KEY MISMATCH — fix before writing")

out = {"lessons": lessons, "concepts": C}
js = ("/* Curated resources for the System Design roadmap.\n"
      "   Every video id below was verified against YouTube's oEmbed API: the title and\n"
      "   channel are the ones YouTube returned. Generated by tools/build_sd_resources.py. */\n"
      "window.sdResources = " + json.dumps(out, ensure_ascii=False, indent=1) + ";\n")
open(os.path.join(ROOT, 'resources.js'), 'w', encoding='utf-8').write(js)
print("wrote resources.js:", len(js), "bytes")
