#!/usr/bin/env python3
"""
Enriches behavioral.html with staff-level, multi-approach STAR responses
showcasing technical trade-off evaluation, quantitative impact, and deep self-reflection.
Preserves all IDs, counts, and structural markup for 100% test compatibility.
"""
import re, os, tempfile

BH_HTML_PATH = os.path.join(os.path.dirname(__file__), "..", "behavioral.html")

SECTION_2_ENRICHMENTS = {
    # 2.1 Customer Obsession
    "2.1.1": "<b>Situation:</b> Product team demanded shipping a complex checkout upsell feature right before Black Friday to hit quarterly revenue goals, but load testing showed it added 280ms p99 latency to payment processing. <b>Task:</b> Reconcile short-term revenue pressure with checkout reliability and customer trust. <b>Action:</b> Evaluated synchronous execution vs asynchronous deferred rendering vs feature gating; proposed an asynchronous edge-cached widget with an automated latency circuit-breaker that sheds upsell calls if p99 exceeds 50ms. <b>Result:</b> Zero checkout drop-offs during peak 40k RPS traffic; upsell captured $1.4M additional GMV without degrading core purchasing experience.",
    "2.1.2": "<b>Situation:</b> A tier-1 enterprise merchant experienced intermittent webhook dropouts causing failed inventory syncs; standard support dismissed it as intermittent client-side network jitter. <b>Task:</b> Identify root cause and restore customer faith in our platform SLAs. <b>Action:</b> Dived deep into TCP packet captures and proxy logs; uncovered an edge-case TCP window exhaustion on the customer's legacy gateway during burst notifications. Personally authored an adaptive backoff client adapter and implemented an SQS dead-letter replay queue for them. <b>Result:</b> Prevented churn of an $850k ARR account; customer praised our engineering partnership in a public case study.",
    "2.1.3": "<b>Situation:</b> User forum telemetry and support tickets revealed developers hated our 3-step OAuth flow for CLI tools, leading to 22% auth abandonment. <b>Task:</b> Overhaul developer onboarding without compromising security. <b>Action:</b> Evaluated full session tokens vs device code flow (RFC 8628); led implementation of RFC 8628 Device Authorization with short-lived scoped polling tokens, pairing with automated PKCE verification. <b>Result:</b> Auth drop-off plunged from 22% to under 1.5%; developer time-to-first-API-call dropped from 14 minutes to 90 seconds.",

    # 2.2 Ownership
    "2.2.1": "<b>Situation:</b> Our team owned recommendation ranking, but an upstream ETL ingestion pipeline owned by another org frequently stalled, injecting 6-hour stale data into our models. <b>Task:</b> Resolve data freshness without waiting for the upstream team's 2-quarter backlog. <b>Action:</b> Refused to say 'not my job'; audited the upstream PySpark batch job, identified skewed partition shuffling, refactored it into an incremental micro-batch streaming pipeline on AWS Kinesis, and set up end-to-end data freshness CloudWatch alarms. <b>Result:</b> Ingestion latency dropped from 6 hours to 4 minutes; recommendation CTR improved by 8.4% org-wide.",
    "2.2.2": "<b>Situation:</b> Inherited a mission-critical billing microservice with zero integration tests, 4,000-line monolithic handlers, and undocumented tribal knowledge after senior engineers departed. <b>Task:</b> Stabilize the service and eliminate recurring weekend outage pages. <b>Action:</b> Prioritized a phased strangler fig refactor: first instrumented distributed tracing (OpenTelemetry) and structured logging; established a regression test suite covering 94% of billing paths; decoupled external payment gateways behind clear domain interfaces with idempotent retry keys. <b>Result:</b> Reduced on-call alerts by 78%; zero missed customer billing events over the next 18 months.",
    "2.2.3": "<b>Situation:</b> Pressure to ship a major enterprise feature in Q3 by hardcoding multi-tenant database routing logic directly inside the API gateway. <b>Task:</b> Prevent crippling architectural technical debt while managing executive launch expectations. <b>Action:</b> Presented a trade-off matrix to leadership showing that hardcoding saved 3 weeks now but would require a 6-month migration when onboarding tenant #50. Proposed a 2-week extension to implement an extensible metadata-driven dynamic routing layer. <b>Result:</b> Feature launched cleanly 14 days later; seamless scaling from 12 to 240 enterprise tenants without a single line of routing code changes.",

    # 2.3 Invent and Simplify
    "2.3.1": "<b>Situation:</b> Production deployments across 35 microservices required a 42-step manual wiki checklist, taking 3 hours and causing 2-3 human-error rollbacks per month. <b>Task:</b> Drastically simplify the release cycle and increase engineering velocity. <b>Action:</b> Invented an automated GitOps canary orchestration CLI: integrated ephemeral staging environments, automated database schema compatibility checks, automated canary traffic splitting via Envoy (1% -> 10% -> 100%), and metric-based automated rollback on error spikes. <b>Result:</b> Deployment time collapsed from 3 hours to 12 minutes; release frequency surged from bi-weekly to 8 deploys daily with zero manual rollbacks.",
    "2.3.2": "<b>Situation:</b> A legacy fraud detection system used 18 chained regex rules and nested if-else heuristics, making latency unpredictable (400ms-2s) and debugging impossible. <b>Task:</b> Simplify the fraud decision engine for sub-50ms p99 SLA. <b>Action:</b> Re-architected the rule engine using a deterministic Finite State Machine (FSM) compiled into bitmask operations, decoupling feature extraction from rule evaluation into parallel workers. <b>Result:</b> P99 latency dropped from 1,200ms to 24ms (50x speedup); reduced code footprint from 14,000 lines of spaghetti to 950 cleanly tested lines.",
    "2.3.3": "<b>Situation:</b> Team had maintained a complex self-hosted distributed Redis cluster solely for distributing user session tokens, requiring 15 hours/month of maintenance, failover drills, and shard balancing. <b>Task:</b> Challenge the legacy architecture and eliminate operational overhead. <b>Action:</b> Demonstrated that 99% of session lookups only needed cryptographically verified user claims; championed replacing the entire stateful Redis session fleet with asymmetric stateless JWTs (Ed25519) paired with a lightweight DynamoDB blocklist for revoked tokens. <b>Result:</b> Decommissioned 24 Redis nodes, saving $42k/year in AWS infrastructure; eliminated session lookup latency entirely.",

    # 2.4 Are Right, A Lot
    "2.4.1": "<b>Situation:</b> Production outage at 2 AM: distributed search cluster nodes were dropping out of consensus, causing search failures; logs showed mixed signals between disk I/O bottlenecks and JVM garbage collection thrashing. <b>Task:</b> Diagnose and restore cluster availability rapidly despite conflicting metrics. <b>Action:</b> Formulated hypothesis that unindexed wild-card queries were triggering full heap allocations, inducing stop-the-world GC pauses that caused Raft heartbeat timeouts; rejected team proposal to reboot all nodes (which would cause cold-cache collapse); instead isolated the traffic spike via ingress rate-limiting and applied a targeted query filter. <b>Result:</b> Cluster stabilized within 7 minutes with zero data loss; post-mortem root cause confirmed GC pause exceeded the 2.5s Raft election threshold.",
    "2.4.2": "<b>Situation:</b> Strongly advocated migrating our real-time notification engine from WebSocket connections to Server-Sent Events (SSE) based on simpler HTTP/2 multiplexing. <b>Task:</b> Acknowledge architectural oversights and adjust strategy when mobile client telemetry proved problematic. <b>Action:</b> Monitored rollout on Android/iOS; discovered aggressive mobile carrier TCP connection killing caused massive battery drain and reconnections on SSE. Vocally admitted my initial evaluation missed mobile power states, halted rollout, and pivoted to a hybrid architecture: WebSockets for mobile clients, SSE for desktop web. <b>Result:</b> Cut mobile battery consumption by 32%; earned team trust by putting data above ego.",
    "2.4.3": "<b>Situation:</b> Planned to shard our PostgreSQL database by `user_id`, confident that user-level isolation was the optimal partitioning strategy. <b>Task:</b> Re-evaluate when business analysis showed 40% of future platform growth would come from multi-user corporate organizations. <b>Action:</b> Analyzed query patterns and realized `user_id` sharding would force expensive cross-shard distributed joins for every organizational dashboard. Presented the revised data to the team, demonstrated how `org_id` composite sharding preserved colocation, and redesigned the sharding key. <b>Result:</b> Prevented catastrophic distributed query latency; corporate dashboards scaled smoothly to 50k concurrent users.",

    # 2.5 Learn and Be Curious
    "2.5.1": "<b>Situation:</b> Our Go backend services began suffering unexplained 40ms latency spikes in Kubernetes that internal profilers could not capture because the kernel was descheduling pods. <b>Task:</b> Uncover kernel-level bottlenecks without prior Linux kernel profiling experience. <b>Action:</b> Self-taught eBPF (Extended Berkeley Packet Filter) and BCC tools over a weekend; wrote a custom eBPF tracepoint probe (`runqlat`) to monitor Linux scheduler runqueue latency directly in the kernel; discovered CPU CFS quota throttling was starving threads despite low average CPU usage. <b>Result:</b> Disabled CFS bandwidth quotas in favor of CPU pinning, instantly erasing the 40ms tail latency spike; presented an internal eBPF workshop for 60+ engineers.",
    "2.5.2": "<b>Situation:</b> Generative AI emerged as a major enterprise capability, but our platform had zero LLM integration or retrieval expertise. <b>Task:</b> Build personal and team mastery in AI engineering to assess product feasibility. <b>Action:</b> Completed deep dives into Transformer architectures, embeddings, vector indexing (HNSW), and chunking strategies; built an open-source evaluation benchmark comparing hybrid search vs dense retrieval on internal documentation. <b>Result:</b> Authored the company's AI architecture whitepaper; prototype became the blueprint for our production RAG assistant that now handles 45k enterprise queries daily.",
    "2.5.3": "<b>Situation:</b> Our frontend team was blocked due to complex WebGL / WebAssembly rendering bugs in our analytics canvas, an area our backend team had never touched. <b>Task:</b> Step outside backend comfort zone to unblock a flagship product milestone. <b>Action:</b> Read the WebAssembly specification and WebGL shader pipelines; paired with frontend engineers to debug memory leaks in Rust-compiled Wasm modules; created a reusable memory pooling abstraction in C++/Wasm. <b>Result:</b> Unblocked the release 2 weeks ahead of the partner conference; bridged a long-standing knowledge silo between frontend and backend teams.",

    # 2.6 Hire and Develop the Best
    "2.6.1": "<b>Situation:</b> A junior engineer struggled with PR feedback, feeling overwhelmed by architectural design reviews and lacking confidence in technical discussions. <b>Task:</b> Coach and accelerate their progression into an independent, high-performing mid-level engineer. <b>Action:</b> Established weekly 1:1 architectural pairing sessions; taught them the 'Why' behind trade-offs (e.g. why we choose immutability, how cache invalidation works); broke down complex epics into incremental ownership milestones, then deliberately stepped back to let them lead design reviews. <b>Result:</b> Engineer successfully delivered our new billing webhook gateway independently and received promotion to SDE-2 within 10 months.",
    "2.6.2": "<b>Situation:</b> A brilliant senior engineer consistently delivered great code but alienated peers in design reviews with harsh, dismissive comments that shut down discussion. <b>Task:</b> Deliver difficult behavioral feedback to protect team psychological safety without demotivating a top performer. <b>Action:</b> Held a private, candid conversation; separated their technical acumen from their communication impact, citing specific examples where junior engineers withheld valuable ideas out of fear; coached them on 'inquisitive feedback' (asking 'What happens if X fails?' instead of saying 'This will fail'). <b>Result:</b> The engineer adapted their style, began actively mentoring junior team members, and was later praised in 360 reviews as a collaborative technical leader.",
    "2.6.3": "<b>Situation:</b> An engineer consistently missed committed sprint milestones over 4 months, frequently submitting untested PRs that caused production regressions despite multiple coaching sessions. <b>Task:</b> Manage underperformance rigorously and compassionately to protect team delivery and morale. <b>Action:</b> Set up a clear, objective 60-day Performance Improvement Plan (PIP) with weekly measurable milestones, explicit code quality criteria, and paired mentorship; when objective criteria were not met at the 45-day review, coordinated respectfully with HR and the engineer for a smooth transition out. <b>Result:</b> Maintained team velocity and trust; re-hired a strong replacement who boosted sprint delivery by 35%.",

    # 2.7 Insist on the Highest Standards
    "2.7.1": "<b>Situation:</b> Under extreme deadline pressure to launch a new payment integration, a partner vendor provided an SDK that lacked idempotency handling and dropped SSL verification on retries. <b>Task:</b> Refuse to compromise security and reliability standards despite intense management launch pressure. <b>Action:</b> Rejected the vendor SDK; explained to executive leadership the existential risk of duplicate charges and MITM vulnerabilities; led a 72-hour sprint to write a clean, native client using mutual TLS, exponential backoff with jitter, and client-generated idempotency keys. <b>Result:</b> Launched on schedule with zero security vulnerabilities and handled $12M in transactions on day one with 100% financial reconciliation.",
    "2.7.2": "<b>Situation:</b> Monorepo unit test coverage had degraded to 42%, CI builds took 45 minutes, and engineers routinely merged flaky test bypasses to hit sprint deadlines. <b>Task:</b> Cultivate a culture of uncompromising engineering excellence across 40 developers. <b>Action:</b> Instituted automated test hygiene: built a parallelized CI test runner (reducing build times from 45 min to 6 min), added strict code coverage gates (minimum 80% diff coverage), and set up an automated quarantine bot for flaky tests that alerted owners immediately. <b>Result:</b> Production incident frequency dropped by 64% over two quarters; team velocity doubled due to reliable CI feedback.",
    "2.7.3": "<b>Situation:</b> Product leadership wanted to push an unfinished mobile update to production before an investor demo, bypassing our canary validation phase. <b>Task:</b> Protect production customer experience and uphold release gates. <b>Action:</b> Firmly pushed back using hard crash-rate telemetry from internal dogfood builds (showing a 3.2% crash rate on older Android devices); offered a collaborative alternative: prepared a dedicated staging environment with mock data for the executive demo while the engineering team resolved the memory leak. <b>Result:</b> Demo was a huge success; production release rolled out safely 3 days later with a 99.98% crash-free session rate.",

    # 2.8 Think Big
    "2.8.1": "<b>Situation:</b> Four separate business units were independently building bespoke search solutions (Elasticsearch, Solr, Algolia), duplicating $600k/year in infrastructure and engineering maintenance. <b>Task:</b> Envision and champion a bold, unified search platform for the entire enterprise. <b>Action:</b> Authored a 6-page PR/FAQ proposing an enterprise-wide Centralized Search Platform as a Service; designed a multi-tenant architecture with pluggable indexing pipelines, custom schema definitions, and automated RBAC; secured buy-in from 4 engineering directors by demonstrating a 60% operational cost reduction. <b>Result:</b> Platform scaled to serve 35 internal teams, indexing 2.5 billion documents at 85k QPS with $480k annual infrastructure savings.",
    "2.8.2": "<b>Situation:</b> Asked to build a simple batch script to export user activity logs to S3 for monthly compliance auditing. <b>Task:</b> Look beyond the immediate tactical ask to solve the broader data analytics bottleneck. <b>Action:</b> Realized that 6 other teams needed real-time event streaming for fraud, analytics, and personalization; expanded the scope to design a unified Kafka event backbone with Schema Registry and real-time Parquet conversion to an Apache Iceberg data lake. <b>Result:</b> Turned a throwaway compliance script into the enterprise data foundation that now powers company-wide business intelligence and real-time ML pipelines.",
    "2.8.3": "<b>Situation:</b> Company leadership believed our database infrastructure could never support expansion into the Asia-Pacific region without duplicating entire datacenters and engineering teams ($2M+ cost). <b>Task:</b> Challenge existing assumptions and propose a viable, highly scalable multi-region architecture. <b>Action:</b> Researched active-active distributed architectures; designed a hybrid multi-region blueprint using AWS Aurora Global Database for cross-region sub-second replication and CloudFront edge computing for localized read caching, confining cross-region calls strictly to mutations. <b>Result:</b> Enabled APAC launch in 4 months at less than 15% of the estimated budget, cutting APAC latency from 320ms to 28ms.",

    # 2.9 Bias for Action
    "2.9.1": "<b>Situation:</b> Critical zero-day vulnerability (Log4j / Log4Shell) announced globally; our inventory service was potentially exposed, but full dependency tree scanning would take 36 hours across 80 repos. <b>Task:</b> Act swiftly to protect customer infrastructure without waiting for complete information. <b>Action:</b> Recognized this as a two-way door emergency; immediately deployed a global WAF rule at the CloudFront edge blocking JNDI lookup strings (`${jndi:`) within 25 minutes of CVE publication; simultaneously rolled out a JVM environment variable mitigation (`-Dlog4j2.formatMsgNoLookups=true`) across all production clusters via automated configuration management. <b>Result:</b> Zero unauthorized exploitation attempts reached our internal services; bought the engineering team time to systematically patch dependencies without panic.",
    "2.9.2": "<b>Situation:</b> Platform was losing customers to a competitor offering AI-powered semantic search; traditional consensus would require a 6-month formal R&D evaluation. <b>Task:</b> Validate customer demand and technical feasibility quickly through a calculated risk. <b>Action:</b> Carved out a 48-hour hackathon prototype: used pgvector and pre-trained open-source embeddings, wrapped it behind a feature flag for 5% of beta users, and instrumented search satisfaction telemetry. <b>Result:</b> Prototype demonstrated an immediate 28% increase in search conversion; provided concrete empirical data to greenlight a full production rollout that was delivered in 6 weeks instead of 6 months.",
    "2.9.3": "<b>Situation:</b> Two engineering teams had been deadlocked in an analysis-paralysis architectural debate for 5 weeks regarding gRPC vs GraphQL for our internal service communication. <b>Task:</b> Break the deadlock and establish momentum. <b>Action:</b> Recognized this as an easily reversible decision; built a working end-to-end benchmark service testing both protocols across 10,000 payload permutations measuring serialization latency, developer ergonomics, and schema evolution; presented the quantitative benchmark results in a 30-minute team meeting. <b>Result:</b> Team reached unshakeable consensus within 15 minutes to adopt gRPC for service-to-service and GraphQL for web clients; unblocked 8 blocked roadmap items.",

    # 2.10 Frugality
    "2.10.1": "<b>Situation:</b> Cloud infrastructure bills were surging 30% month-over-month, threatening the engineering department's operating budget as AWS spend approached $220k/month. <b>Task:</b> Slashing cloud infrastructure costs by at least 25% without impacting SLAs or user latency. <b>Action:</b> Audited production resource utilization: discovered 60% of dev/staging instances ran 24/7 idle; migrated batch processing workloads to AWS EC2 Spot instances with automated fallback; implemented Karpenter dynamic auto-scaling in Kubernetes; transitioned cold S3 assets to Glacier Instant Retrieval. <b>Result:</b> Reduced monthly AWS spend from $220k to $138k (37% savings, over $980k annualized); received the internal engineering efficiency award.",
    "2.10.2": "<b>Situation:</b> Product required high-availability distributed tracing, but commercial vendor quotes (Datadog/New Relic) demanded $180k/year, which our startup could not afford. <b>Task:</b> Deliver full observability within a strict $1,000/month infrastructure budget. <b>Action:</b> Designed an open-source observability pipeline using OpenTelemetry collectors, Grafana Tempo for traces, Loki for logs, and Prometheus for metrics, hosted on existing Kubernetes cluster capacity backed by cheap S3 object storage. <b>Result:</b> Delivered complete distributed tracing across 28 microservices at a total infrastructure cost of $420/month, saving over $170k annually.",
    "2.10.3": "<b>Situation:</b> Database read replicas were maxed out during marketing flash sales; the initial proposed solution was upgrading to the largest RDS instance tier ($4,500/month extra). <b>Task:</b> Resolve database load spikes frugally using smart software design rather than throwing expensive hardware at the problem. <b>Action:</b> Profiled query logs; discovered 80% of read traffic hit 5 static product catalog queries; implemented a two-tier caching strategy: local in-process cache (Go `sync.Map` with 5-second TTL) backed by a Redis cluster with single-flight mutex request coalescing (preventing cache stampedes). <b>Result:</b> Database CPU dropped from 94% to 18% during peak sales; avoided the database upgrade entirely, saving $54k/year.",

    # 2.11 Earn Trust
    "2.11.1": "<b>Situation:</b> Joined a newly acquired engineering team that was highly skeptical of outside technical leadership, viewing architectural changes as micromanagement. <b>Task:</b> Earn the team's respect and build authentic collaborative trust. <b>Action:</b> Did not impose changes; spent the first 30 days listening, taking on difficult on-call shifts, fixing painful build tooling bugs that annoyed the developers daily, and pairing on their toughest debugging tickets; solicited feedback openly on my own PRs and publicly celebrated the team's existing technical achievements. <b>Result:</b> Team sentiment flipped from defensive to deeply collaborative; successfully migrated their architecture to our platform ahead of schedule with 100% engineer retention.",
    "2.11.2": "<b>Situation:</b> An errant database migration script authored by me accidentally acquired an exclusive table lock during a deployment, resulting in 11 minutes of API downtime for customer logins. <b>Task:</b> Take full ownership and rebuild customer and stakeholder trust transparently. <b>Action:</b> Did not shift blame to junior reviewers or staging divergence; immediately published an incident update to the status page; authored a completely blameless, deeply technical Post-Mortem explaining the exact PostgreSQL locking mechanism; implemented automated pre-merge lock analysis in CI to ensure no future migration can acquire table locks without timeout guards. <b>Result:</b> Customer Advisory Board praised our transparency; the post-mortem was adopted company-wide as the gold standard for incident retrospectives.",
    "2.11.3": "<b>Situation:</b> Two weeks before a contractual launch date with a Fortune 50 enterprise client, discovered a deep race condition in our payment reconciliation engine that would take 3 weeks to fix properly. <b>Task:</b> Deliver the difficult news to executive stakeholders without sugarcoating or causing panic. <b>Action:</b> Scheduled an immediate briefing with the VP of Sales and client technical leads; presented the exact defect, the business risk of financial discrepancy, and a concrete 2-phase recovery plan: launch core features on time with manual daily reconciliation, followed by full automated reconciliation 14 days later. <b>Result:</b> Client appreciated our integrity and accepted the phased timeline; zero financial discrepancies occurred and the client renewed for a multi-year $2.2M contract.",

    # 2.12 Dive Deep
    "2.12.1": "<b>Situation:</b> A distributed payment service intermittently threw 504 Gateway Timeouts on 0.05% of transactions; metrics showed normal CPU, memory, and database connection pools, confounding the on-call team for 3 weeks. <b>Task:</b> Isolate the elusive root cause of the micro-outages through rigorous technical investigation. <b>Action:</b> Refused to dismiss it as transient network noise; collected thread dumps and executed Linux `perf` and `strace` on impacted containers; correlated timestamps with TCP connection states and discovered that Linux ephemeral port exhaustion was occurring due to unclosed HTTP response bodies in a third-party analytics SDK, leaving sockets in TIME_WAIT. <b>Result:</b> Applied connection pooling and socket reuse (`SO_REUSEADDR`), completely eradicating the 504 timeouts (0.000% error rate across 80M daily transactions).",
    "2.12.2": "<b>Situation:</b> Financial reconciliation reports produced by a nightly batch job drifted by small rounding errors ($0.03 to $12.40), preventing accounting sign-off. <b>Task:</b> Trace the numerical discrepancy through millions of transactions across distributed microservices. <b>Action:</b> Audited the entire data pipeline end-to-end; inspected binary serialization formats and database column types; discovered that an intermediate Go service was casting high-precision financial numbers from 64-bit integers (cents) to IEEE 754 floating-point `float64` before sending to the reporting warehouse, introducing binary floating-point representation drift. <b>Result:</b> Refactored financial pipeline to use arbitrary-precision decimal strings (Fixed-point arithmetic); eliminated 100% of financial reconciliation discrepancies.",
    "2.12.3": "<b>Situation:</b> System dashboard showed overall API p99 latency was healthy at 120ms, but user NPS comments complained about sluggish loading. <b>Task:</b> Dive beyond high-level aggregate metrics to uncover the real user experience. <b>Action:</b> Segmented latency metrics by geography, tenant size, and network connection type; discovered that for users on high-latency mobile networks in Latin America, p99 latency was actually spiking to 4.8 seconds due to 14 sequential API waterfall roundtrips on initial app load. <b>Result:</b> Combined the 14 waterfall calls into a single GraphQL batch query and introduced an edge CDN response cache, dropping p99 latency in LATAM to 340ms and lifting mobile engagement by 22%.",

    # 2.13 Have Backbone; Disagree and Commit
    "2.13.1": "<b>Situation:</b> Engineering Director proposed migrating our primary relational PostgreSQL datastore to a NoSQL document database (MongoDB) to 'eliminate schema migrations and ship faster'. <b>Task:</b> Respectfully challenge the leadership decision with data and protect long-term data integrity. <b>Action:</b> Analyzed our domain model showing 70% of core transactions required multi-table ACID guarantees; prepared a quantitative technical whitepaper demonstrating that simulating transactions and referential integrity at the application layer in NoSQL would introduce data corruption bugs and double development effort; presented the findings in a 1-on-1 meeting with the Director. <b>Result:</b> Director agreed with the technical evidence and retained PostgreSQL, adopting automated migration tools (Liquibase) instead; saved the company from a disastrous 9-month botched database rewrite.",
    "2.13.2": "<b>Situation:</b> Product team insisted on removing rate-limiting on public API signup endpoints to reduce friction during a high-profile marketing campaign. <b>Task:</b> Push back firmly against a decision that jeopardized platform stability and security. <b>Action:</b> Stood my ground; demonstrated historical attack logs where automated credential-stuffing botnets overwhelmed the user authentication service; proposed a compromise: implemented invisible background behavioral bot scoring (Cloudflare Turnstile) and IP-reputation throttling, maintaining zero-friction for humans while strictly throttling bot clusters. <b>Result:</b> Marketing campaign proceeded smoothly with 40k valid signups, while the background protection successfully thwarted 280k automated bot creation attempts.",
    "2.13.3": "<b>Situation:</b> Strongly advocated for using Apache Kafka for an event-driven architecture, but after a thorough team vote, leadership chose AWS SQS + SNS to leverage existing team cloud familiarity. <b>Task:</b> Practice 'Disagree and Commit' with total dedication once the team decision was finalized. <b>Action:</b> Set aside personal architectural preference completely; immediately authored the official team best-practice guide for SQS/SNS message filtering, dead-letter queueing, and FIFO ordering; personally implemented the common wrapper library for exponential backoff retries. <b>Result:</b> SQS/SNS architecture launched successfully on schedule; team delivered the milestone with zero internal friction or resentment.",

    # 2.14 Deliver Results
    "2.14.1": "<b>Situation:</b> 6 weeks before our biggest contractual product launch of the year, our primary third-party payment partner abruptly revoked their sandbox API due to regulatory restructuring. <b>Task:</b> Deliver the launch on the original promised date despite the total loss of our core dependency. <b>Action:</b> Mobilized an emergency strike team; ruthlessly descoped non-critical P2 features; negotiated a rapid integration with an alternative payment provider (Stripe); worked in parallel tracks: frontend built mock-driven UI while backend implemented the new webhook adapter; conducted 24-hour continuous integration testing across timezones. <b>Result:</b> Shipped on the exact launch date, processing $4.2M in transactions in week one with 99.99% success rate.",
    "2.14.2": "<b>Situation:</b> The company had committed to achieving SOC2 Type II compliance in 90 days as a prerequisite for closing a $5M enterprise sales pipeline, but 42 technical security controls were completely unfulfilled. <b>Task:</b> Drive cross-team engineering execution to meet the strict 90-day deadline. <b>Action:</b> Created a burndown dashboard; broken down compliance controls into concrete developer tasks (MFA enforcement, KMS envelope encryption at rest, automated vulnerability scanning in CI/CD, immutable audit logging with AWS CloudTrail); ran daily 10-minute standups with lead engineers across 6 teams to eliminate roadblocks. <b>Result:</b> Passed the SOC2 audit with zero exceptions in 82 days, enabling the sales team to close the $5M enterprise contract on time.",
    "2.14.3": "<b>Situation:</b> During a high-visibility Prime Day shopping event, our order calculation service began crashing under 4x projected traffic due to severe database thread contention. <b>Task:</b> Mitigate live customer failure and deliver uninterrupted checkout processing under intense pressure. <b>Action:</b> Quickly diagnosed that non-essential discount recalculations were saturating database locks; rapidly authored and deployed a dynamic feature flag hotfix that cached discount rules in local memory for 60 seconds and shed background recommendation RPCs; monitored error rates recover to zero in real-time. <b>Result:</b> Maintained 100% order processing availability through the remainder of the peak shopping event, capturing $18M in daily GMV.",

    # 2.15 Strive to be Earth's Best Employer
    "2.15.1": "<b>Situation:</b> Female and underrepresented engineers in our department expressed in skip-level meetings that their technical contributions were frequently interrupted in architecture forums and overlooked for tech-lead assignments. <b>Task:</b> Champion diversity and inclusion to foster an equitable engineering environment where all voices are heard and valued. <b>Action:</b> Instituted structured, asynchronous Request-For-Comments (RFC) processes for all technical designs so every engineer could review and propose solutions without being talked over; established transparent tech-lead rotation criteria; created an internal sponsorship program pairing junior underrepresented engineers with principal architects. <b>Result:</b> Participation in design reviews increased across all levels; two sponsored engineers successfully delivered high-visibility flagship initiatives and were promoted; department inclusion index improved by 45%.",
    "2.15.2": "<b>Situation:</b> Rapid company scaling led to an intense 'hustle' culture where engineers felt pressured to review PRs and answer Slack messages late at night, creating chronic anxiety. <b>Task:</b> Redesign organizational working norms to promote work-life balance and mental health. <b>Action:</b> Coached managers and senior engineers to model healthy boundaries: scheduled messages instead of sending late-night pings, instituted 'Quiet Focus Thursdays' with zero meetings across the organization, and established clear SLAs for code reviews (during business hours only). <b>Result:</b> Internal employee satisfaction surveys showed a 38% increase in work-life balance satisfaction and an 18% boost in sprint story completion rates.",
    "2.15.3": "<b>Situation:</b> A mid-level engineer on our team was struggling with on-call anxiety and low confidence after a high-severity outage, considering moving away from systems engineering. <b>Task:</b> Support their psychological safety, rebuild their technical confidence, and accelerate their career growth. <b>Action:</b> Paired with them on post-incident remediation; co-authored comprehensive runbooks for complex failure modes; established weekly architecture pairing sessions; and sponsored them to lead the reliability redesign of our primary message consumer service. <b>Result:</b> Their confidence rebounded; they independently handled several subsequent on-call shifts smoothly, gave a tech talk on resilient queue processing, and earned promotion to senior engineer the following cycle.",

    # 2.16 Success and Scale Bring Broad Responsibility
    "2.16.1": "<b>Situation:</b> Our recommendation algorithm began prioritizing high-engagement clickbait content that amplified extreme viewpoints and algorithmic bias, alienating long-tail creators and users. <b>Task:</b> Balance user engagement metrics with societal responsibility and long-term ecosystem health. <b>Action:</b> Spearheaded an Ethical AI working group; modified recommendation loss functions to penalize sensationalist signals and reward factual credibility and creator diversity; introduced an algorithmic transparency panel explaining to users exactly why a piece of content was recommended. <b>Result:</b> Slight 1.5% drop in short-term daily clicks was offset by a 14% increase in 90-day user retention and a 28% increase in diverse creator retention.",
    "2.16.2": "<b>Situation:</b> Our cloud infrastructure grew to over 4,000 EC2 instances across 5 regions, generating a massive carbon footprint and wasted energy from underutilized servers. <b>Task:</b> Drive sustainability and environmental responsibility into our platform architecture. <b>Action:</b> Migrated workloads from x86 Intel instances to energy-efficient ARM-based AWS Graviton processors (which consume up to 60% less energy for the same performance); implemented aggressive automated pod downsizing during off-peak hours using Kubernetes Horizontal Pod Autoscaling. <b>Result:</b> Cut our cloud carbon footprint by an estimated 42% while simultaneously reducing compute costs by $310k/year.",
    "2.16.3": "<b>Situation:</b> A proposed marketing feature aimed to collect and monetize granular background geolocation data from mobile users, which was legally compliant under current privacy laws but deeply invasive. <b>Task:</b> Uphold user privacy and broad ethical responsibility as an engineering leader. <b>Action:</b> Spoke up during the product architecture review; demonstrated how collecting precision location created catastrophic data breach liability and eroded customer trust; proposed an alternative design using coarse city-level geo-hashing on the device itself without ever transmitting raw coordinates to our servers. <b>Result:</b> Executive team adopted the privacy-preserving design; protected 12M users' location privacy and established our company as an industry leader in ethical data stewardship."
}

# Section 3: General Question Categories
SECTION_3_ENRICHMENTS = {
    "3.1.1": "<b>Strategy:</b> Highlight technical leadership, architectural vision, delegating key components, removing cross-team blockers, and shielding the team during high-pressure releases. Quantify: team size, sprint velocity increase (+35%), zero missed milestones.",
    "3.1.2": "<b>Strategy:</b> Show how you used data, working prototypes, RFC documents, and empathy for partner team constraints rather than executive escalation to achieve architectural consensus.",
    "3.1.3": "<b>Strategy:</b> Frame around empathy and root-cause analysis (skill gap vs motivation gap). Pair-program on design docs, set objective short-term milestones, and celebrate early wins to rebuild confidence.",
    "3.2.1": "<b>Strategy:</b> Professional dispute over technical design (e.g. REST vs gRPC). Focus on objective benchmarks, listening attentively, disconfirming personal assumptions, and building mutual trust.",
    "3.2.2": "<b>Strategy:</b> Disagree and commit framework. Voice technical risks with data in private 1:1; propose a low-risk fallback; once the decision is made, commit 100% to flawless execution.",
    "3.2.3": "<b>Strategy:</b> Identify hidden risks (e.g. single point of failure, data corruption risk, compliance gap). Present a side-by-side trade-off matrix with clear alternative paths.",
    "3.3.1": "<b>Strategy:</b> Choose a real, non-trivial engineering failure (e.g. bad database migration, overlooked edge-case causing partial outage). Take 100% personal ownership; emphasize the blameless post-mortem and permanent automated systemic safeguards instituted.",
    "3.3.2": "<b>Strategy:</b> Focus on an architectural or estimation misjudgment. Explain what you didn't know then, how you corrected it, and how it fundamentally matured your engineering judgment.",
    "3.3.3": "<b>Strategy:</b> Demonstrate senior reflection: earlier stakeholder alignment, incremental canary rollouts instead of big-bang releases, or investing in observability before writing code.",
    "3.4.1": "<b>Strategy:</b> Demonstrate structuring chaos: decomposing vague executive asks into concrete customer personas, user journeys, measurable technical requirements, and incremental milestones.",
    "3.4.2": "<b>Strategy:</b> Proactively identified a latent production risk or developer productivity bottleneck (e.g. flaky CI tests, unmonitored dead-letter queue) and delivered an automated fix without waiting for permission.",
    "3.4.3": "<b>Strategy:</b> Two-way door decision-making (Jeff Bezos framework). Formulate hypothesis, bound blast radius with feature flags, establish clear rollback metrics, and act decisively.",
    "3.5.1": "<b>Strategy:</b> Detail scale, strict latency/throughput SLAs, concurrency complexity, and cross-system coordination. Clearly differentiate your personal contribution from the broader team's work.",
    "3.5.2": "<b>Strategy:</b> Pragmatic engineering: deliberate, well-documented technical debt with an explicit repayment timeline (e.g. shipping MVP with manual reconciliation, scheduled for automated refactor in sprint N+1).",
    "3.5.3": "<b>Strategy:</b> Scientific method: observe anomaly, form testable hypotheses, analyze thread dumps/eBPF/flame graphs, verify with metrics, and prevent recurrence with automated guards.",
    "3.6.1": "<b>Strategy:</b> Close the feedback loop: listen to customer friction, translate qualitative complaints into quantitative metrics, and prioritize architectural fixes that move customer NPS.",
    "3.6.2": "<b>Strategy:</b> Facilitate alignment: align disparate stakeholders (sales, legal, product, security) around a shared objective framework (RICE score or customer trust impact).",
    "3.6.3": "<b>Strategy:</b> 'No, but...': decline unreasonable scope or unsafe launch timelines respectfully by explaining the technical risk/trade-off and providing viable alternative options.",
    "3.7.1": "<b>Strategy:</b> Ruthless prioritization (cutting P2 scope to protect P0 quality), parallelizing workstreams, transparent burndown communication, and preventing team burnout.",
    "3.7.2": "<b>Strategy:</b> External vendor outage or unexpected architectural blocker handled through agility, fallback mock adapters, and intense cross-functional collaboration.",
    "3.7.3": "<b>Strategy:</b> Proactive communication: alert stakeholders early as soon as the variance is detected; present a revised recovery schedule with tradeoffs rather than hiding delays until the last minute.",
    "3.8.1": "<b>Strategy:</b> Present, Past, Future framework: current focus and high-impact accomplishments (30s) -> career trajectory and foundational technical background (30s) -> why this specific role matches your growth path (30s).",
    "3.8.2": "<b>Strategy:</b> Three pillars: 1. Specific product/engineering challenges they face that excite you, 2. Alignment with company mission/culture, 3. How your specific skills solve their current bottlenecks.",
    "3.8.3": "<b>Strategy:</b> Strength: paired with evidence and business impact. Weakness: real, technical or organizational, with an active, demonstrable system for continuous improvement.",
    "3.8.4": "<b>Strategy:</b> Focus on scope and mastery: growing technical depth, multiplying organizational engineering impact, driving architecture for larger systems, and mentoring next-generation engineers.",
    "3.8.5": "<b>Strategy:</b> Run TOWARDS growth, not away from trouble. Focus on seeking larger scale, deeper technical challenges, and greater alignment with long-term engineering ambitions."
}

# Section 4: Story Bank Essential Stories
SECTION_4_ENRICHMENTS = {
    "4.1.1": "<b>Blueprint:</b> Deep dive on scaling a distributed system under 10x traffic surge. Highlight bottleneck profiling (database lock contention), designing asynchronous SQS decoupling, implementing Redis caching with request coalescing, and achieving 99.99% availability during peak event.",
    "4.1.2": "<b>Blueprint:</b> Own an honest production outage caused by insufficient boundary validation in a payment microservice. Detail the immediate mitigation, authoring a transparent blameless post-mortem, and adding automated contract tests in CI.",
    "4.1.3": "<b>Blueprint:</b> Disagreement with a principal architect over event-driven architecture (Kafka vs SQS). Showcase compiling quantitative latency and operational cost benchmarks, presenting the data respectfully in 1:1, and committing 100% once the decision was locked.",
    "4.1.4": "<b>Blueprint:</b> Discovered a silent failure in data ingestion pipeline outside your team's charter. Stepped in to write an automated reconciliation watchdog and Prometheus alerts, saving $240k in delayed customer billing.",
    "4.1.5": "<b>Blueprint:</b> Solved an ambiguous latency regression in multi-region Kubernetes clusters. Formulated hypothesis, used eBPF runqueue analysis to pinpoint Linux CFS CPU throttling, and tuned container resource limits.",
    "4.1.6": "<b>Blueprint:</b> Mentored an SDE-1 struggling with system design reviews. Structured weekly whiteboarding sessions, taught trade-off evaluation, delegated a major API gateway project, and celebrated their promotion to SDE-2.",
    "4.1.7": "<b>Blueprint:</b> Resolved high churn among enterprise merchants suffering webhook timeouts. Profiled TCP socket states, diagnosed client gateway window exhaustion, built an adaptive client backoff SDK, and retained an $850k contract.",
    "4.1.8": "<b>Blueprint:</b> Replaced a fragile 42-step manual deployment checklist across 35 microservices with an automated GitOps canary pipeline with automated metric rollback, cutting deploy lead time from 3 hours to 12 minutes.",
    "4.1.9": "<b>Blueprint:</b> Pushed back against leadership pressure to bypass security review for a partner integration. Demonstrated the compliance and financial fraud risk, built an automated mock harness, and launched securely on time.",
    "4.1.10": "<b>Blueprint:</b> Delivered a high-throughput search engine under tight 6-week deadline with 2 engineers. Leveraged open-source pgvector and off-the-shelf embeddings instead of custom fine-tuning, hitting all p99 latency targets.",
    "4.1.11": "<b>Blueprint:</b> Advocated for GraphQL but team voted for gRPC. Embraced gRPC fully, authored team-wide Protobuf linting rules, built reusable client interceptors, and accelerated service-to-service velocity.",
    "4.1.12": "<b>Blueprint:</b> Architected an enterprise-wide multi-tenant event streaming platform adopted by 35 teams, handling 2.5B events daily at 85k QPS while slashing company-wide cloud infrastructure spend by $480k annually."
}

def enrich_behavioral_html():
    with open(BH_HTML_PATH, "r", encoding="utf-8") as f:
        content = f.read()

    count2 = 0
    count3 = 0
    count4 = 0

    # Section 2 replacer
    for cid, text in SECTION_2_ENRICHMENTS.items():
        pattern = re.compile(rf'(<li\b[^>]*data-cid="{re.escape(cid)}"[^>]*>[\s\S]*?<div class="cname">[\s\S]*?<\/div>)<div style="font-size:11.5px;color:var\(--text-faint\);margin-top:2px">([\s\S]*?)<\/div>', re.IGNORECASE)
        content, n = pattern.subn(rf'\1<div style="font-size:11.5px;color:var(--text-faint);margin-top:2px">{text}</div>', content)
        count2 += n

    # Section 3 replacer (injects or updates description div)
    for cid, text in SECTION_3_ENRICHMENTS.items():
        pattern_existing = re.compile(rf'(<li\b[^>]*data-cid="{re.escape(cid)}"[^>]*>[\s\S]*?<div class="cname">[\s\S]*?<\/div>)<div style="font-size:11.5px;color:var\(--text-faint\);margin-top:2px">([\s\S]*?)<\/div>', re.IGNORECASE)
        if pattern_existing.search(content):
            content, n = pattern_existing.subn(rf'\1<div style="font-size:11.5px;color:var(--text-faint);margin-top:2px">{text}</div>', content)
            count3 += n
        else:
            pattern_new = re.compile(rf'(<li\b[^>]*data-cid="{re.escape(cid)}"[^>]*>[\s\S]*?<div class="cname">[\s\S]*?<\/div>)(<\/div>)', re.IGNORECASE)
            content, n = pattern_new.subn(rf'\1<div style="font-size:11.5px;color:var(--text-faint);margin-top:2px">{text}</div>\2', content)
            count3 += n

    # Section 4 replacer
    for cid, text in SECTION_4_ENRICHMENTS.items():
        pattern = re.compile(rf'(<li\b[^>]*data-cid="{re.escape(cid)}"[^>]*>[\s\S]*?<div class="cname">[\s\S]*?<\/div>)<div style="font-size:11.5px;color:var\(--text-faint\);margin-top:2px">([\s\S]*?)<\/div>', re.IGNORECASE)
        content, n = pattern.subn(rf'\1<div style="font-size:11.5px;color:var(--text-faint);margin-top:2px">{text}</div>', content)
        count4 += n

    dir_name = os.path.dirname(BH_HTML_PATH)
    fd, temp_path = tempfile.mkstemp(dir=dir_name, text=True)
    with os.fdopen(fd, "w", encoding="utf-8") as tmp:
        tmp.write(content)
    os.replace(temp_path, BH_HTML_PATH)
    print(f"Enriched Section 2: {count2}, Section 3: {count3}, Section 4: {count4} concepts in behavioral.html!")

if __name__ == "__main__":
    enrich_behavioral_html()
