#!/usr/bin/env python3
"""
Enriches cs_fundamentals.html with detailed multi-approach explanations,
architectural trade-offs, and deep-dives into core mechanisms.
Preserves all IDs, counts, and structural markup for 100% test compatibility.
"""
import re, os, tempfile

CS_HTML_PATH = os.path.join(os.path.dirname(__file__), "..", "cs_fundamentals.html")

# Dictionary of enriched concept descriptions: cid -> enriched description text
ENRICHMENTS = {
    # Section 1.1 Processes & Threads
    "1.1.1": "Isolated address space with dedicated PCB (Process Control Block), page directory, virtual memory maps (text, data, BSS, heap, stack), file descriptor table, and credentials. Processes cannot access each other's memory without explicit IPC. Created via fork() utilizing Copy-on-Write (COW) page semantics.",
    "1.1.2": "Lightweight execution unit sharing the parent process's address space, heap, open file descriptors, and global variables, but possessing its own Thread Control Block (TCB), Program Counter (PC), CPU registers, and private stack (typically 1MB-8MB in OS threads vs ~2KB in Go goroutines). Tradeoff: extreme shared-memory speed vs concurrency bugs (race conditions, deadlocks).",
    "1.1.3": "Kernel mechanism storing the CPU register state, Program Counter, and stack pointer of a running thread into its PCB/TCB, reloading another thread's state, and switching page tables via CR3 register on x86. Direct cost ~1-2µs, but indirect cost is massive: L1/L2 CPU cache pollution, branch predictor invalidation, and TLB (Translation Lookaside Buffer) flushes.",
    "1.1.4": "Core OS lifecycle: Ready (queued in runqueue awaiting CPU allocation), Running (executing on a core), and Blocked/Waiting (sleeping for I/O completion, lock acquisition, or timer expiration). Transitions are mediated by kernel hardware timer interrupts and system calls.",
    "1.1.5": "The classic POSIX process lifecycle: fork() clones the calling process via Copy-on-Write (duplicating page tables marked read-only until written); execve() replaces the current process address space with a new executable binary; wait()/waitpid() suspends parent execution until child terminates and collects its exit status code.",
    "1.1.6": "Zombie process: child has completed execution (exit status stored in process table) but parent has not called wait() to reap it; consumes PID entries. Orphan process: parent terminates before child; kernel reparents the orphan to PID 1 (init/systemd), which periodically reaps terminating children.",

    # Section 1.2 CPU Scheduling
    "1.2.1": "FCFS (First-Come, First-Served): non-preemptive FIFO queue, suffers from the Convoy Effect (short tasks stall behind a long CPU-bound process). SJF (Shortest Job First): optimal average wait time, but requires clairvoyance of CPU burst durations. SRTF (Shortest Remaining Time First): preemptive SJF, preemption occurs if a new arrival has a shorter remaining burst.",
    "1.2.2": "Preemptive scheduling allocating a fixed CPU time quantum (slice, e.g., 10-100ms) per process in circular FIFO order. Trade-off: short quantum ensures snappy user interactivity but wastes CPU in context-switching overhead; long quantum degenerates into FCFS with sluggish response times.",
    "1.2.3": "Adaptive priority scheduling utilizing multiple distinct FIFO queues with decreasing priorities and increasing time slices. I/O-bound interactive processes remain in top-priority queues with small slices; CPU-intensive batch jobs are demoted to lower queues. Periodic priority boosting prevents starvation of low-priority jobs.",
    "1.2.4": "Default Linux scheduler modeling an ideal multi-tasking CPU using a self-balancing Red-Black Tree. Tracks each task's virtual runtime (vruntime = execution time normalized by task 'nice' priority weight). Always schedules the leftmost node (lowest vruntime). O(log N) insertion, O(1) selection of next task to run.",
    "1.2.5": "Preemptive multitasking: OS kernel enforces execution limits via hardware timer interrupts, forcefully context-switching non-cooperative threads (prevents starvation and hangs). Cooperative multitasking (e.g., Python asyncio, older Mac OS): processes must explicitly yield control (via sleep/await); a single rogue CPU loop hangs the entire system.",

    # Section 1.3 Memory Management
    "1.3.1": "Decouples process logical memory addresses from physical RAM addresses using hardware Memory Management Unit (MMU). Grants each process a uniform contiguous address space (e.g. 48-bit/256TB in x86-64), provides memory isolation, enables memory mapping (mmap), and permits transparent overcommit beyond physical RAM capacity via swap.",
    "1.3.2": "Divides address space into fixed-size chunks (typically 4KB, or 2MB/1GB HugePages). Multi-level page tables (e.g. 4-level PML4 on x86-64) map virtual page numbers (VPN) to physical page frame numbers (PFN). TLB (Translation Lookaside Buffer) acts as a high-speed hardware cache for translations; TLB misses incur high-latency multi-cycle memory walks.",
    "1.3.3": "Lazy memory allocation where pages are not loaded into physical RAM until touched. When a process accesses an unmapped virtual address, the MMU triggers a Page Fault interrupt. Minor fault: page resides in memory cache or shared pages (fast resolve). Major fault: page must be fetched from disk storage/swap (millisecond latency penalty).",
    "1.3.4": "Eviction policies when physical memory frames are exhausted. FIFO: simple, but suffers from Belady's Anomaly. Optimal (MIN): evicts page needed furthest in the future (theoretical ceiling). LRU: evicts least recently used page, high tracking overhead. Clock (Second Chance): circular list checking use bit. ARC (Adaptive Replacement Cache): dynamically self-tunes between recency and frequency.",
    "1.3.5": "Stack: contiguous LIFO memory region per thread, managed directly by CPU stack pointer register (RSP), zero allocation overhead, auto-freed on function return, prone to stack overflow on deep recursion. Heap: dynamically allocated memory (malloc/new), runtime lifetime, prone to fragmentation, memory leaks, and allocator contention.",
    "1.3.6": "User-space allocators bridging malloc()/free() with kernel brk()/mmap() syscalls. Employs freelists, segregated fits, and buddy allocators. Production allocators (jemalloc, TCMalloc) utilize per-thread arenas and thread-local caches to eliminate lock contention on multi-core concurrent allocations.",
    "1.3.7": "Automated runtime memory reclamation. Reference Counting: immediate reclamation, zero pause, but cannot collect cyclic graphs and incurs atomic counter overhead. Tracing GC (Mark-Sweep, Generational): divides heap into Eden/Young/Tenured based on generational hypothesis ('most objects die young'); modern collectors (ZGC, Go GC) perform concurrent marking to reduce Stop-the-World pauses under 1ms.",

    # Section 1.4 I/O & File Systems
    "1.4.1": "Inodes store file metadata (permissions, owner, timestamps, file size, block pointers/extents) independently of filenames. Directories are specialized files containing tables mapping string filenames to inode numbers. Hard links share the same inode; symbolic links point to another path string.",
    "1.4.2": "Crash-resilient file system architecture (ext4, NTFS, XFS). Writes file metadata (and optionally payload blocks) sequentially to a dedicated circular Write-Ahead Log (WAL) journal before updating physical disk blocks. Enables rapid post-crash recovery by replaying or rolling back unfinished journal transactions, eliminating slow fsck scans.",
    "1.4.3": "Blocking I/O: calling thread suspends in kernel wait queue until hardware data transfer completes (simple programming model, but requires 1:1 thread per connection). Non-blocking I/O (O_NONBLOCK): read/write syscalls return immediately with EAGAIN/EWOULDBLOCK if buffer is not ready, enabling single-threaded event loop multiplexing.",
    "1.4.4": "I/O Multiplexing primitives. select(): O(N) linear array scan, 1024 fd limit. poll(): O(N) scan without fd limit. epoll (Linux) & kqueue (BSD/macOS): O(1) event-driven notification using in-kernel Red-Black tree for interest registration and a ready-list linked list; supports Level-Triggered (poll-like) and Edge-Triggered (state change only). Modern Linux io_uring uses shared ring-buffers for zero-syscall async I/O.",
    "1.4.5": "Hardware mechanism allowing high-throughput network cards, NVMe controllers, and disk controllers to transfer raw data blocks directly to/from main system RAM via system bus without CPU intervention. Mitigates CPU interrupt storms via interrupt coalescing and ring buffers.",

    # Section 1.5 IPC
    "1.5.1": "Kernel-managed unidirectional FIFO byte-stream communication buffer (typically 64KB). Anonymous pipes: parent-child process communication via inherited file descriptors (created via pipe()). Named pipes (FIFOs, created via mkfifo): visible in file system namespace, allowing unrelated processes to communicate over standard file I/O operations.",
    "1.5.2": "Fastest IPC mechanism available on modern OS. Multiple processes map identical physical memory pages into their respective virtual address spaces via mmap() or shmget(). Zero-copy data exchange directly in RAM at memory bus speeds. Trade-off: requires external user-level synchronization (POSIX semaphores, mutexes) to avoid race conditions.",
    "1.5.3": "Kernel-persisted discrete message queues (POSIX mq_open, System V msgget). Allows processes to exchange structured, prioritized message packets asynchronously without maintaining an active concurrent connection. Senders write and exit; receivers retrieve highest-priority messages on demand.",
    "1.5.4": "Bidirectional IPC endpoint utilizing standard socket APIs (socket(AF_UNIX)) for processes running on the same host kernel. Bypasses the network stack, IP routing, checksum calculations, and packet framing, delivering over 2x throughput of localhost loopback TCP. Crucially supports passing open file descriptors between processes via SCM_RIGHTS.",
    "1.5.5": "Asynchronous software interrupts delivered by the kernel to a process to notify events. Handled via default action, ignore, or custom signal handler. Critical distinction: SIGTERM (15) requests graceful termination allowing cleanup; SIGKILL (9) and SIGSTOP (19) immediately freeze/kill the process at the kernel level and cannot be caught, blocked, or ignored.",

    # Section 2.1 OSI & TCP/IP Models
    "2.1.1": "Theoretical 7-layer networking stack: Physical (bits, signals), Data Link (MAC frames, Ethernet, switches), Network (IP packets, routing), Transport (TCP/UDP segments, ports), Session (RPC session maintenance), Presentation (data serialization, encryption/TLS), Application (HTTP, DNS, SSH, gRPC).",
    "2.1.2": "Practical 4-layer architecture powering the internet: Link/Network Access (Ethernet, Wi-Fi, ARP), Internet (IPv4, IPv6, ICMP, BGP routing), Transport (TCP, UDP, QUIC), Application (HTTP, DNS, TLS, SMTP). Consolidates OSI layers 5-7 into Application and layers 1-2 into Link.",
    "2.1.3": "Outbound transmission wraps data recursively with layer-specific headers (Application payload -> TCP header [ports, seq] -> IP header [source/dest IP, TTL] -> Ethernet frame [MAC addresses, CRC trailer]). Inbound reception decapsulates each header layer upon validation.",

    # Section 2.2 IP & Routing
    "2.2.1": "32-bit addresses providing ~4.29 billion global unique addresses. Exhausted in 2011. Mitigated by Classless Inter-Domain Routing (CIDR), Network Address Translation (NAT), and private address spaces (RFC 1918: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16).",
    "2.2.2": "128-bit address space (3.4 × 10^38 addresses), eliminating the need for NAT. Features mandatory IPsec support, simplified 40-byte fixed header (no header checksum for faster router processing), SLAAC (stateless address autoconfiguration), and multicast replacing broadcast.",
    "2.2.3": "CIDR notation (e.g. 192.168.1.0/24) specifies network prefix length. Subnet masks divide IP addresses into network portion (routing identifier) and host portion. Enables route aggregation (supernetting) to prevent global internet routing table explosion.",
    "2.2.4": "Network Address Translation: maps multiple private internal IP addresses to a single public IP address using ephemeral Layer 4 port mappings (NAPT/PAT). Modifies IP and TCP/UDP checksums in real-time. Impedes direct peer-to-peer connectivity, necessitating STUN, TURN, and ICE traversal protocols.",
    "2.2.5": "BGP (Border Gateway Protocol): path-vector exterior gateway protocol routing traffic between Autonomous Systems (AS) across the global internet using policy-based routing. OSPF (Open Shortest Path First): link-state interior gateway protocol utilizing Dijkstra's algorithm for fast intra-datacenter routing.",
    "2.2.6": "Internet Control Message Protocol (Layer 3 diagnostic protocol). Encapsulated in IP packets without transport ports. ping uses ICMP Echo Request (Type 8) and Echo Reply (Type 0). traceroute sends incrementing TTL packets, discovering hops when intermediate routers return ICMP Time Exceeded (Type 11).",

    # Section 2.3 TCP & UDP
    "2.3.1": "Full-duplex, connection-oriented, reliable byte-stream protocol. Guarantees in-order delivery via sequence numbers and cumulative ACKs, provides end-to-end reliability via retransmissions (RTO calculation based on SRTT), prevents buffer overflow via sliding window flow control, and protects the network via congestion control.",
    "2.3.2": "Connection establishment: Client sends SYN (seq=x); Server replies with SYN-ACK (seq=y, ack=x+1); Client sends ACK (ack=y+1). Mitigates SYN flood attacks using SYN Cookies (cryptographically encoding state into sequence number without allocating server TCB memory until ACK arrives). Termination uses a 4-way FIN/ACK handshake, concluding in TIME_WAIT state (2*MSL, typically 60s) to prevent lingering delayed packets from corrupting new connections.",
    "2.3.3": "Congestion window (cwnd) management. Slow Start: exponential growth doubling cwnd each RTT until ssthresh. Congestion Avoidance: AIMD linear additive increase. Fast Retransmit: 3 duplicate ACKs trigger instant retransmission without waiting for RTO timer. Algorithms: TCP Reno (loss-based, halving window), TCP Cubic (cubic polynomial curve, standard in Linux for high bandwidth-delay product networks), Google BBR (model-based: measures Bottleneck Bandwidth and min-RTT to operate at optimal pipe capacity without causing bufferbloat).",
    "2.3.4": "Minimalist connectionless transport protocol (8-byte header: Source Port, Dest Port, Length, Checksum). No handshakes, no acknowledgments, no ordering, no retransmissions, zero head-of-line blocking. Ideal for real-time multiplayer gaming, VoIP/video conferencing (RTP), DNS lookups, and modern custom protocols like QUIC.",
    "2.3.5": "UDP-based transport protocol standardized as the foundation for HTTP/3. Embeds TLS 1.3 encryption natively to eliminate connection latency (1-RTT or 0-RTT connection resumption). Multiplexes independent streams without transport-layer Head-of-Line blocking (loss on stream A does not stall stream B). Supports seamless Connection Migration across network changes (Wi-Fi to 5G) via 64-bit Connection IDs.",
    "2.3.6": "A network socket represents an OS IPC abstraction identified by a 5-tuple: (Source IP, Source Port, Dest IP, Dest Port, Protocol). Well-known ports (0-1023: HTTP 80, HTTPS 443, SSH 22, DNS 53), registered ports (1024-49151), and dynamic ephemeral ports (49152-65535).",

    # Section 2.4 HTTP & DNS
    "2.4.1": "Stateless client-server protocol. Request: HTTP Method (GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS), URI path, headers (Host, User-Agent, Content-Type, Authorization), and optional payload body. Response: Status Code (1xx Info, 2xx Success, 3xx Redirect, 4xx Client Error, 5xx Server Error), response headers, and payload.",
    "2.4.2": "HTTP/1.1: textual protocol, keep-alive persistent connections, pipelining suffered from severe Head-of-Line blocking. HTTP/2: binary framing layer, multiplexed bidirectional streams over a single TCP connection, HPACK header compression, server push (TCP HOL blocking persists on packet loss). HTTP/3: built on UDP/QUIC, eliminates TCP HOL blocking, integrates TLS 1.3 0-RTT, and enables instant connection migration.",
    "2.4.3": "Hierarchical name resolution: Browser Cache -> OS Resolver Cache (hosts file) -> Recursive DNS Resolver (ISP/Cloudflare 1.1.1.1/Google 8.8.8.8) -> Root Nameservers ('.') -> TLD Nameservers ('.com') -> Authoritative Nameservers ('example.com'). Recursive resolver caches responses adhering to TTL directives.",
    "2.4.4": "Core DNS zone records: A (maps hostname to IPv4 address), AAAA (maps to 128-bit IPv6 address), CNAME (canonical name alias pointing to another hostname, cannot coexist with other records at zone apex), ALIAS/ANAME (virtual CNAME resolved at apex by DNS server), MX (mail exchange records with priority weights), TXT (arbitrary text; critical for SPF, DKIM, and domain ownership verification).",
    "2.4.5": "Multi-tier caching hierarchy minimizing DNS lookup latency (which costs 20-120ms). Governed by Time-To-Live (TTL) field set by domain administrators. High TTL (86400s) maximizes cache hit rates and reduces resolver load; low TTL (60s) enables rapid failover during migrations or disaster recovery events.",

    # Section 2.5 TLS / Security
    "2.5.1": "Cryptographic transport layer security. TLS 1.2 requires 2 full round-trips (2-RTT) to negotiate cipher suites, exchange key parameters (RSA/Diffie-Hellman), and verify certificates. TLS 1.3 cuts handshake latency to 1-RTT (and 0-RTT Early Data for resumed sessions) by mandating Ephemeral Diffie-Hellman (PFS) and deprecating insecure legacy ciphers (RC4, 3DES, MD5, SHA-1).",
    "2.5.2": "Public Key Infrastructure: enables trust without prior communication. Servers present an X.509 certificate signed by an intermediate Certificate Authority (CA), forming a cryptographic chain of trust validated against Root CA certificates pre-installed in the client OS trust store. Mutual TLS (mTLS) enforces two-way verification where clients must also present certificates to authenticate microservices.",
    "2.5.3": "HSTS (HTTP Strict Transport Security): response header instructing browsers to automatically upgrade all insecure HTTP requests to HTTPS for a declared duration (e.g. max-age=31536000; includeSubDomains; preload), thwarting SSL-stripping attacks. OCSP Stapling: server periodically queries CA for signed revocation status and staples it directly to the TLS handshake, eliminating client-side OCSP blocking latency and privacy leaks.",

    # Section 3.1 SQL Basics
    "3.1.1": "Relational algebra set operations. INNER JOIN: returns rows with matching keys in both tables. LEFT/RIGHT OUTER JOIN: preserves all rows from left/right table, populating unmatched columns with NULL. FULL OUTER JOIN: preserves all rows from both tables. CROSS JOIN: Cartesian product (N × M rows). In query engines, implemented via Nested Loop Join (O(M×N), fast with index), Hash Join (O(M+N), builds in-memory hash table for large unindexed datasets), or Sort-Merge Join (O(M log M + N log N), optimal for pre-sorted inputs).",
    "3.1.2": "Data summarization operations. GROUP BY partitions rows sharing identical grouping keys. Aggregates (COUNT, SUM, AVG, MIN, MAX) compute scalar metrics per group. Critical interview distinction: WHERE filters individual rows before grouping occurs; HAVING filters aggregated groups after GROUP BY evaluation.",
    "3.1.3": "Computes aggregate-like calculations across a subset ('window') of rows while preserving individual row identities (unlike GROUP BY which collapses rows). Syntax: `OVER (PARTITION BY ... ORDER BY ...)`. Includes ranking (ROW_NUMBER(), RANK(), DENSE_RANK()), offset navigation (LAG(), LEAD()), and cumulative running totals (SUM() OVER (...)).",
    "3.1.4": "Common Table Expressions (WITH clause): defines temporary named result sets scoped to the execution of a single query, significantly improving SQL readability and modularity over deeply nested subqueries. Recursive CTEs enable traversal of hierarchical and graph structures (e.g. organizational charts, bill-of-materials, ancestor trees).",
    "3.1.5": "Non-correlated subqueries execute once, allowing optimizer substitution. Correlated subqueries reference outer query columns and evaluate repeatedly for every outer row (O(N×M) penalty if unindexed). Modern cost-based optimizers rewrite subqueries into equivalent JOINs or semi-joins (EXISTS/IN) to leverage index scans and hash joins.",

    # Section 3.2 Normalization
    "3.2.1": "Systematic database design reducing data redundancy and preventing update anomalies. 1NF: atomic column values, unique rows (primary key). 2NF: 1NF + no partial dependency (all non-key attributes fully dependent on whole candidate key). 3NF: 2NF + no transitive dependencies (non-key attributes depend only on the primary key). BCNF (Boyce-Codd): stricter 3NF where every determinant must be a candidate key.",
    "3.2.2": "Deliberate introduction of controlled redundancy into normalized schemas (e.g. precomputed totals, duplicate customer names in order tables) to eliminate expensive multi-table JOINs and reduce read latency in read-heavy applications. Trade-offs: increased storage footprint, higher write latency (write amplification), and severe risk of data inconsistency requiring distributed transactions or background reconciliation jobs.",

    # Section 3.3 Indexes
    "3.3.1": "Index data structures. B+ Tree: self-balancing search tree with high fanout (100-500) and low depth (3-4); stores records/pointers only in leaf nodes connected via doubly linked list, optimizing range scans and equality lookups. Hash Index: O(1) equality lookups, but completely incapable of range queries or sorting. GIN (Generalized Inverted Index): maps components (JSON keys, full-text words, array elements) to row pointers, essential for document and full-text search.",
    "3.3.2": "Clustered Index: dictates the physical ordering of table rows on disk; leaf pages contain the actual table data rows (only 1 clustered index permitted per table, typically the Primary Key). Non-Clustered (Secondary) Index: independent B+ tree structure whose leaf nodes contain index keys and a pointer/primary key to the physical data row; secondary queries require a secondary lookup ('bookmark lookup') unless all requested columns exist in the index ('Covering Index').",
    "3.3.3": "Multi-column index (e.g. index on (A, B, C)). Governed by the Leftmost Prefix Rule: queries can utilize the index for filtering if they constrain the leading column (A), (A, B), or (A, B, C). Queries filtering on (B) or (C) alone cannot navigate the tree root and result in a full index/table scan.",
    "3.3.4": "Cardinality: the count of distinct values in a column. Selectivity: the ratio of distinct values to total rows (`cardinality / total_rows`). High selectivity (~1.0, e.g. UUID, email, user_id) makes an index extremely efficient. Low selectivity (e.g. boolean flags, gender status) causes query optimizers to bypass the index in favor of a sequential table scan because random disk I/O from index lookups costs more than sequential reading.",
    "3.3.5": "Query profiling commands. EXPLAIN outputs the query execution plan generated by the cost-based optimizer (showing anticipated cost, estimated rows, and selected join/scan operators). EXPLAIN ANALYZE actually executes the query and reports real runtime execution times, actual row counts, memory/buffer usage, and disk spill metrics (identifying Seq Scans, nested loops, and temporary disk sorts).",

    # Section 3.4 Transactions & Isolation
    "3.4.1": "Atomicity: all operations in a transaction succeed together or rollback completely via Write-Ahead Log (WAL) or undo logs. Consistency: transactions transition database from one valid state to another, satisfying all schema constraints, foreign keys, and triggers. Isolation: concurrent transactions execute without interfering with one another. Durability: committed changes persist through crashes and power loss via fsync to non-volatile storage.",
    "3.4.2": "ANSI SQL Isolation Levels: Read Uncommitted (allows dirty reads, no read locks), Read Committed (prevents dirty reads, reads latest committed snapshot per statement), Repeatable Read (prevents non-repeatable reads, reads snapshot taken at transaction start), Serializable (highest isolation, guarantees concurrent execution is equivalent to some serial ordering).",
    "3.4.3": "Concurrency anomalies. Dirty Read: reading uncommitted data written by a concurrent transaction that later rolls back. Non-repeatable (Fuzzy) Read: re-reading the same row returns modified column values committed by another transaction. Phantom Read: re-executing a range query returns newly inserted/deleted rows matching the predicate. Write Skew: concurrent transactions read overlapping data, make disjoint modifications, and commit invalid state violating cross-row constraints.",
    "3.4.4": "Multi-Version Concurrency Control: concurrent transactions see point-in-time consistent snapshots without blocking writers, and writers do not block readers. Implemented via row versioning: PostgreSQL appends new tuple versions with `xmin`/`xmax` transaction IDs and reclaims dead tuples via VACUUM; MySQL InnoDB modifies rows in-place in clustered index pages and stores previous versions in an Undo Log rollback segment.",
    "3.4.5": "Locking mechanisms: Shared Locks (S-locks, read locks, multiple concurrent holders) and Exclusive Locks (X-locks, write locks, single holder). Deadlock occurs when two or more transactions hold locks the other needs in a circular wait dependency (e.g., T1 holds A, waits for B; T2 holds B, waits for A). Resolved by engine via Deadlock Detection (wait-for graph cycle hunting and aborting the cheapest victim transaction) or Deadlock Prevention (wait-die or wound-wait timestamp schemes).",
    "3.4.6": "Optimistic Concurrency Control (OCC): transactions execute reads and writes without acquiring locks under the assumption that conflicts are rare. Upon commit, the transaction validates whether data changed during its execution (typically by verifying a `version` integer column or timestamp). If conflicted, the transaction aborts and retries. Superior throughput for read-heavy, low-contention workloads.",

    # Section 3.5 NoSQL types
    "3.5.1": "Stores semi-structured data as JSON/BSON documents with dynamic, flexible schemas (MongoDB, Couchbase). Allows embedding child entities (e.g. order items inside order document) to enable atomic single-document reads without joins. Ideal for catalogs, content management, and rapidly evolving domain models.",
    "3.5.2": "High-performance data store associating opaque or structured data values with unique string keys (Redis, Memcached, DynamoDB). In-memory engines deliver sub-millisecond latencies using single-threaded event loops (Redis) and specialized in-memory data structures (Hashes, Sorted Sets, Bitmaps, HyperLogLogs). Employs persistence strategies: RDB snapshots and AOF (Append-Only File) journals.",
    "3.5.3": "Distributed column-family architecture derived from Google Bigtable (Apache Cassandra, ScyllaDB). Organizes data by Partition Key (hashed via consistent hashing to locate replica nodes) and Clustering Key (determines physical on-disk sort order within the partition). Powered by LSM-Trees; excels at high-throughput write-intensive workloads, time-series data, and petabyte-scale horizontal scaling with tunable consistency (QUORUM).",
    "3.5.4": "Graph database modeling complex, highly interconnected networks as explicit Nodes, Directed Edges (Relationships), and Properties (Neo4j, AWS Neptune). Implements Index-Free Adjacency where each node acts as a micro-index with direct memory pointers to adjacent neighbors, providing O(1) relationship traversal times independent of total graph size. Essential for social networks, fraud detection, and recommendation engines.",

    # Section 4.1 Concurrency vs Parallelism
    "4.1.1": "Concurrency is about structure: dealing with lots of things at once by decomposing a program into independent execution units (threads, coroutines, event loops) that can be interleaved on a single core or executed across multiple cores. Focuses on responsiveness, coordination, and non-blocking I/O.",
    "4.1.2": "Parallelism is about execution: physically doing lots of things at the exact same instant by utilizing multiple CPU hardware cores, SIMD vector units, or distributed nodes. Requires hardware support and focuses strictly on computational throughput and latency reduction for compute-heavy workloads.",
    "4.1.3": "Theoretical formula bounding maximum speedup $S = \\frac{1}{(1-p) + \\frac{p}{N}}$, where $p$ is the parallelizable fraction of the task and $N$ is the number of processor cores. Demonstrates that even with infinite cores ($N \\to \\infty$), maximum speedup is strictly capped by the serial fraction $\\frac{1}{1-p}$ (e.g., if 5% of code is sequential, max theoretical speedup is 20x). Contrasted with Gustafson's Law for scaling problem sizes.",

    # Section 4.2 Synchronization Primitives
    "4.2.1": "Mutual Exclusion lock: guarantees that only a single thread can execute inside a designated critical section at any given moment. Blocking mutexes (e.g. `pthread_mutex`) place contending threads into an OS sleep queue via the Linux `futex` syscall. Critical trade-off: prevents race conditions but incurs context switch overhead (~1-2µs) when contention occurs.",
    "4.2.2": "Signaling mechanism maintaining an internal integer counter protected by atomics. Counting Semaphore: initialized to $N$ permits, allowing up to $N$ concurrent threads into a resource pool (e.g. database connection pool, rate limiter). Binary Semaphore: permit count 0 or 1, similar to a mutex but differs fundamentally: a semaphore has no concept of ownership (thread A can post/release a semaphore acquired by thread B).",
    "4.2.3": "Signaling primitive enabling threads to suspend execution (sleep) until notified that a specific application state condition has become true (paired with an associated mutex). Always requires checking the condition inside a `while` loop (never `if`) to guard against Spurious Wakeups (waking without explicit signal) and race conditions before lock reacquisition.",
    "4.2.4": "Spinlock: contending threads repeatedly execute a tight CPU polling loop ('spin') testing an atomic flag instead of yielding the CPU. Optimal only when the critical section is extremely brief (< context switch latency ~1µs) and on multi-core systems; disastrous on single-core or long-running sections as it burns 100% CPU.",
    "4.2.5": "Reader-Writer Lock (Shared-Exclusive lock): allows unlimited simultaneous reader threads (Shared lock) or exactly one writer thread (Exclusive lock). Drastically boosts read throughput in read-heavy workloads (e.g., routing tables, config caches). Must be carefully designed to prevent Writer Starvation (continuous incoming readers blocking a pending writer) using fair queueing or write-preference policies.",
    "4.2.6": "Thread-safe memory barriers. Barrier: synchronizes a fixed group of $N$ threads at a designated execution milestone; all threads block until the last thread reaches the barrier, whereupon all are released simultaneously (reusable, e.g. `CyclicBarrier`). Latch: one-time countdown trigger (`CountDownLatch`); threads wait until the counter reaches zero.",
    "4.2.7": "Execution architecture decoupling task submission from execution. Maintains an in-memory task queue and a fixed/dynamic pool of worker threads to avoid the prohibitive cost of spawning and tearing down OS threads for every task. Work-Stealing Pools (e.g. Go runtime M:N scheduler, Java ForkJoinPool): each worker thread maintains a double-ended queue (deque); idle workers steal tasks from the tail of busy workers' queues to ensure load balancing.",

    # Section 4.3 Classic Concurrency Problems
    "4.3.1": "Producer threads append items into a fixed-capacity bounded buffer; consumer threads extract items. Must coordinate access to prevent race conditions on buffer state and handle boundary constraints: producers must block when buffer is full (`not_full` condition), consumers must block when buffer is empty (`not_empty` condition). Implemented via mutex + 2 condition variables or 2 counting semaphores.",
    "4.3.2": "Coordinates access to shared data accessed by multiple readers and writers. Formulations: First Readers-Writers (favors readers, risks writer starvation), Second Readers-Writers (favors writers, prevents starvation), Third Readers-Writers (fair FIFO queueing using a turnstile semaphore ensuring no thread is starved).",
    "4.3.3": "Classic resource contention problem by Dijkstra: 5 philosophers sit at a table with 5 forks; each requires 2 adjacent forks to eat. Naive approach (each picks left fork, waits for right) results in immediate circular deadlock. Solutions: Resource Hierarchy (number forks 1..5, always acquire lowest-numbered fork first), Arbitrator/Waiter (mutex restricting at most 4 philosophers to table), or Chandy/Misra distributed solution.",
    "4.3.4": "Permanent stall where two or more threads cannot proceed because each is waiting for a resource held by another. Four Coffman Conditions must hold simultaneously: 1. Mutual Exclusion, 2. Hold and Wait, 3. No Preemption, 4. Circular Wait. Eliminating any single condition prevents deadlock (most commonly breaking Circular Wait via strict total ordering of lock acquisition).",
    "4.3.5": "Livelock: active threads continuously change state in response to each other without making any forward progress (like two polite people in a hallway repeatedly stepping to the same side). Starvation: a runnable thread is perpetually denied access to a shared resource or CPU time due to unfair scheduling or biased lock acquisition algorithms.",

    # Section 4.4 Lock-Free & Atomics
    "4.4.1": "Hardware CPU instructions executing read-modify-write operations uninterruptedly at the memory bus level without locking: `test-and-set`, `fetch-and-add`, and Compare-And-Swap (`CMPXCHG` on x86). CAS compares a memory location against an expected value; if equal, it updates to the new value in a single atomic cycle and returns success.",
    "4.4.2": "Subtle concurrency defect in CAS-based lock-free data structures: Thread 1 reads value A from location X. Thread 2 preempts, modifies X from A to B, then modifies X back to A. Thread 1 resumes, executes CAS expecting A, and succeeds—unaware that the underlying structure or pointer references mutated in the interim. Mitigated using Tagged Pointers (associating a 64-bit monotonic version/counter with the pointer) or Hazard Pointers / RCU.",
    "4.4.3": "Formal specification defining how memory reads and writes interact across threads and processor cores. Compilers and out-of-order CPUs reorder instructions for performance. Memory Barriers (Fences) restrict reordering: Acquire semantics (subsequent reads/writes cannot move before this operation), Release semantics (prior reads/writes cannot move after this operation), and Sequential Consistency (globally agreed total order across all threads, highest performance cost).",
    "4.4.4": "Hardware protocol maintaining identical memory views across CPU L1/L2/L3 caches. MESI protocol categorizes cache lines (typically 64 bytes) into 4 states: Modified, Exclusive, Shared, Invalid. False Sharing occurs when independent threads modify unrelated variables residing on the same 64-byte cache line, causing constant invalidation and bus traffic; eliminated via 64-byte memory alignment/padding.",

    # Section 5.1-5.3 Security
    "5.1.1": "Symmetric: identical secret key for encryption and decryption (AES-256, ChaCha20); fast, gigabytes/sec throughput via AES-NI CPU instructions. Asymmetric: public key encrypts, private key decrypts (RSA-3072, ECC Curve25519/ECDSA); computationally expensive, utilized for key exchange (ECDH) and digital signatures.",
    "5.1.2": "Cryptographic Hash: one-way, deterministic, collision-resistant mapping to fixed digest (SHA-256, SHA-3, BLAKE3); used for integrity verification and HMAC signatures. Password Hashing: deliberately computationally expensive and memory-hard algorithms (Argon2id, bcrypt, scrypt) with unique salts to defeat brute-force dictionary attacks, rainbow tables, and GPU/ASIC cracking.",
    "5.1.3": "Hash-based Message Authentication Code: combines a secret key with a cryptographic hash function (HMAC-SHA256). Guarantees both data integrity and authenticity (proves the message was created by a party holding the secret key and was not tampered with in transit). Foundation for API request signing (AWS SigV4) and JWT signatures.",
    "5.2.1": "Authentication (AuthN): verifying identity ('Who are you?', validated via passwords, biometrics, MFA, WebAuthn/Passkeys). Authorization (AuthZ): verifying permissions ('What are you allowed to do?', validated via Role-Based Access Control RBAC or Attribute-Based Access Control ABAC).",
    "5.2.2": "Compact, URL-safe self-contained token format: `Header.Payload.Signature`. Stateless: servers verify the cryptographic signature (HMAC-SHA256 or RSA/ECDSA public key) without querying a database or session store. Trade-offs: cannot be easily revoked before expiration; requires short TTLs (15 min) paired with refresh tokens or distributed token revocation blocklists.",
    "5.2.3": "OAuth 2.0: industry-standard authorization delegation framework allowing third-party applications to obtain limited access to an HTTP service (using Authorization Code Flow with PKCE for security). OpenID Connect (OIDC): thin identity layer on top of OAuth 2.0, providing standard ID Tokens (JWT) for federated user authentication across systems.",
    "5.2.4": "Session-based: server maintains stateful session store (Redis, DB) and issues an opaque session ID cookie; instant revocation, but requires centralized session store lookups on every request. Token-based: client transmits signed stateless JWT in Authorization header; scales horizontally across microservices, but token revocation is non-trivial.",
    "5.3.1": "OWASP Top 1: untrusted input directly interpolated into SQL interpreter commands, allowing attackers to bypass authentication or extract entire databases. Remediation: mandatory use of Parameterized Queries (Prepared Statements) where the SQL query structure is compiled and user input is treated strictly as literal parameter data, never executable code.",
    "5.3.2": "Injection of malicious client-side JavaScript executed within a victim's browser context. Stored XSS (persisted in DB), Reflected XSS (mirrored in immediate request URL/input), DOM XSS (vulnerable client JavaScript manipulation). Remediation: Context-aware HTML entity escaping, Content Security Policy (CSP) headers, and modern frameworks (React) that auto-escape JSX values.",
    "5.3.3": "Tricks an authenticated user's browser into executing unwanted actions on a trusted web application using existing session cookies. Remediation: Set `SameSite=Strict` or `SameSite=Lax` on session cookies, and validate cryptographically random Anti-CSRF Tokens (synchronizer token pattern) on all state-mutating requests (POST/PUT/DELETE).",
    "5.3.4": "Browser security mechanism restricting scripts on one origin (protocol + domain + port) from interacting with resources on another origin. Cross-Origin Resource Sharing (CORS) relaxes this via server-controlled HTTP response headers (`Access-Control-Allow-Origin`, `Access-Control-Allow-Methods`, `Access-Control-Allow-Headers`) validated via browser preflight `OPTIONS` requests.",

    # Section 6.1-6.3 Architecture
    "6.1.1": "Physical latency hierarchy: CPU Registers (~0.5ns, 1 cycle) -> L1 Cache (~1ns, 4 cycles, 32-64KB per core) -> L2 Cache (~4ns, 14 cycles, 512KB-1MB per core) -> L3 Cache (~10-20ns, 40-75 cycles, 16-64MB shared) -> Main Memory DRAM (~60-100ns, 200 cycles) -> NVMe SSD (~50-100µs) -> Magnetic Disk / Network Call (~1-100ms). Designing cache-friendly algorithms (spatial/temporal locality) delivers orders of magnitude speedups.",
    "6.1.2": "Spatial Locality: accessing a memory address makes nearby addresses likely to be accessed soon (exploited by fetching entire 64-byte cache lines and hardware prefetchers; e.g. contiguous array scans vs fragmented linked lists). Temporal Locality: accessing a memory address makes the same address likely to be accessed again soon (exploited by keeping hot variables in L1/L2 caches).",
    "6.1.3": "CPU hardware and OS coordination keeping cache lines synchronized across multi-socket NUMA (Non-Uniform Memory Access) systems. Uses cache line invalidation broadcasts over bus interconnects (Intel UPI, AMD Infinity Fabric). Accessing memory attached to a remote CPU socket incurs a 2-3x latency penalty compared to local socket memory.",
    "6.2.1": "Fundamental CPU execution cycle. Fetch (load instruction from memory pointed to by Instruction Pointer RIP into Instruction Register) -> Decode (interpret opcode and operand specifiers via micro-op decoders) -> Execute (perform arithmetic/logic operation via ALU or FPU) -> Memory Access (load/store operands to L1 data cache) -> Writeback (write result back to register file).",
    "6.2.2": "Instruction Pipelining: overlaps execution stages across multiple instructions simultaneously (like an assembly line). Hazards: Structural (resource conflicts), Data (Read-After-Write RAW dependencies requiring operand forwarding), and Control (conditional branches). Branch Predictor guesses branch directions to keep the pipeline full; a branch misprediction flushes the entire pipeline, wasting 15-20 CPU cycles.",
    "6.2.3": "Superscalar execution: CPU dynamically reorders instructions to execute independent instructions in parallel across multiple execution units (ALUs, vector units) using reservation stations, Reorder Buffers (ROB), and register renaming, while guaranteeing that instruction results retire in original program order to maintain architectural correctness.",
    "6.3.1": "64-bit general-purpose CPU registers: RAX (accumulator, function return values), RBX (callee-saved base), RCX (counter, 4th function argument), RDX (data, 3rd argument), RSI (source index, 2nd argument), RDI (destination index, 1st argument), RSP (stack pointer, points to top of stack), RBP (base/frame pointer), R8-R11 (arguments and scratch), R12-R15 (callee-saved). RIP (instruction pointer).",
    "6.3.2": "Rules governing function calls. System V AMD64 ABI (Linux/macOS): passes first 6 integer/pointer arguments in registers (RDI, RSI, RDX, RCX, R8, R9), remaining on stack; return value in RAX. Microsoft x64 (Windows): first 4 arguments in RCX, RDX, R8, R9 with a mandatory 32-byte 'shadow store' allocated on stack. Stack must be 16-byte aligned before `call`.",
    "6.3.3": "Caller-saved (volatile) registers: can be overwritten by the called function; if the caller needs their values across the call, it must save them to stack beforehand (e.g. RAX, RCX, RDX, RSI, RDI, R8-R11). Callee-saved (non-volatile) registers: the called function must preserve their original values before using them and restore them before returning (e.g. RBX, RSP, RBP, R12-R15).",
}

def enrich_cs_html():
    with open(CS_HTML_PATH, "r", encoding="utf-8") as f:
        content = f.read()

    # Pattern to match:
    # <li data-cid="CID" ...>...<div class="cname">TITLE</div><div style="font-size:11.5px;color:var(--text-faint);margin-top:2px">OLD_DESC</div>...</li>
    count = 0
    def replacer(match):
        nonlocal count
        full = match.group(0)
        cid = match.group(1)
        if cid in ENRICHMENTS:
            enriched_desc = ENRICHMENTS[cid]
            old_desc = match.group(3)
            # Replace old_desc with enriched_desc
            new_inner = full.replace(f'>{old_desc}<', f'>{enriched_desc}<')
            count += 1
            return new_inner
        return full

    # Regex matching the concept item
    pattern = re.compile(r'<li\b[^>]*data-cid="([^"]+)"[^>]*>[\s\S]*?<div class="cname">([\s\S]*?)<\/div><div style="font-size:11.5px;color:var\(--text-faint\);margin-top:2px">([\s\S]*?)<\/div>', re.IGNORECASE)
    new_content = pattern.sub(replacer, content)

    # Atomic write
    dir_name = os.path.dirname(CS_HTML_PATH)
    fd, temp_path = tempfile.mkstemp(dir=dir_name, text=True)
    with os.fdopen(fd, "w", encoding="utf-8") as tmp:
        tmp.write(new_content)
    os.replace(temp_path, CS_HTML_PATH)
    print(f"Successfully enriched {count} concepts in cs_fundamentals.html!")

if __name__ == "__main__":
    enrich_cs_html()
