#!/usr/bin/env python3
"""
Enriches cs_fundamentals.html with detailed multi-approach explanations,
architectural trade-offs, and deep-dives into core mechanisms.
Preserves all IDs, counts, and structural markup for 100% test compatibility.
"""
import re, os, tempfile

CS_HTML_PATH = os.path.join(os.path.dirname(__file__), "..", "cs_fundamentals.html")

# Comprehensive dictionary of enriched concept descriptions: cid -> enriched description text
ENRICHMENTS = {
    # =========================================================================
    # Section 1: Operating Systems (28 concepts)
    # =========================================================================
    # 1.1 Processes & Threads
    "1.1.1": "Isolated address space with dedicated PCB (Process Control Block), page directory, virtual memory maps (text, data, BSS, heap, stack), file descriptor table, and credentials. Processes cannot access each other's memory without explicit IPC. Created via fork() utilizing Copy-on-Write (COW) page semantics.",
    "1.1.2": "Lightweight execution unit sharing the parent process's address space, heap, open file descriptors, and global variables, but possessing its own Thread Control Block (TCB), Program Counter (PC), CPU registers, and private stack (typically 1MB-8MB in OS threads vs ~2KB in Go goroutines). Tradeoff: extreme shared-memory speed vs concurrency bugs (race conditions, deadlocks).",
    "1.1.3": "Kernel mechanism storing the CPU register state, Program Counter, and stack pointer of a running thread into its PCB/TCB, reloading another thread's state, and switching page tables via CR3 register on x86. Direct cost ~1-2µs, but indirect cost is massive: L1/L2 CPU cache pollution, branch predictor invalidation, and TLB (Translation Lookaside Buffer) flushes.",
    "1.1.4": "Core OS lifecycle: Ready (queued in runqueue awaiting CPU allocation), Running (executing on a core), and Blocked/Waiting (sleeping for I/O completion, lock acquisition, or timer expiration). Transitions are mediated by kernel hardware timer interrupts and system calls.",
    "1.1.5": "The classic POSIX process lifecycle: fork() clones the calling process via Copy-on-Write (duplicating page tables marked read-only until written); execve() replaces the current process address space with a new executable binary; wait()/waitpid() suspends parent execution until child terminates and collects its exit status code.",
    "1.1.6": "Zombie process: child has completed execution (exit status stored in process table) but parent has not called wait() to reap it; consumes PID entries. Orphan process: parent terminates before child; kernel reparents the orphan to PID 1 (init/systemd), which periodically reaps terminating children.",

    # 1.2 CPU Scheduling
    "1.2.1": "FCFS (First-Come, First-Served): non-preemptive FIFO queue, suffers from the Convoy Effect (short tasks stall behind a long CPU-bound process). SJF (Shortest Job First): optimal average wait time, but requires clairvoyance of CPU burst durations. SRTF (Shortest Remaining Time First): preemptive SJF, preemption occurs if a new arrival has a shorter remaining burst.",
    "1.2.2": "Preemptive scheduling allocating a fixed CPU time quantum (slice, e.g., 10-100ms) per process in circular FIFO order. Trade-off: short quantum ensures snappy user interactivity but wastes CPU in context-switching overhead; long quantum degenerates into FCFS with sluggish response times.",
    "1.2.3": "Adaptive priority scheduling utilizing multiple distinct FIFO queues with decreasing priorities and increasing time slices. I/O-bound interactive processes remain in top-priority queues with small slices; CPU-intensive batch jobs are demoted to lower queues. Periodic priority boosting prevents starvation of low-priority jobs.",
    "1.2.4": "Default Linux scheduler modeling an ideal multi-tasking CPU using a self-balancing Red-Black Tree. Tracks each task's virtual runtime (vruntime = execution time normalized by task 'nice' priority weight). Always schedules the leftmost node (lowest vruntime). O(log N) insertion, O(1) selection of next task to run.",
    "1.2.5": "Preemptive multitasking: OS kernel enforces execution limits via hardware timer interrupts, forcefully context-switching non-cooperative threads (prevents starvation and hangs). Cooperative multitasking (e.g., Python asyncio, older Mac OS): processes must explicitly yield control (via sleep/await); a single rogue CPU loop hangs the entire system.",

    # 1.3 Memory Management
    "1.3.1": "Decouples process logical memory addresses from physical RAM addresses using hardware Memory Management Unit (MMU). Grants each process a uniform contiguous address space (e.g. 48-bit/256TB in x86-64), provides memory isolation, enables memory mapping (mmap), and permits transparent overcommit beyond physical RAM capacity via swap.",
    "1.3.2": "Divides address space into fixed-size chunks (typically 4KB, or 2MB/1GB HugePages). Multi-level page tables (e.g. 4-level PML4 on x86-64) map virtual page numbers (VPN) to physical page frame numbers (PFN). TLB (Translation Lookaside Buffer) acts as a high-speed hardware cache for translations; TLB misses incur high-latency multi-cycle memory walks.",
    "1.3.3": "Lazy memory allocation where pages are not loaded into physical RAM until touched. When a process accesses an unmapped virtual address, the MMU triggers a Page Fault interrupt. Minor fault: page resides in memory cache or shared pages (fast resolve). Major fault: page must be fetched from disk storage/swap (millisecond latency penalty).",
    "1.3.4": "Eviction policies when physical memory frames are exhausted. FIFO: simple, but suffers from Belady's Anomaly. Optimal (MIN): evicts page needed furthest in the future (theoretical ceiling). LRU: evicts least recently used page, high tracking overhead. Clock (Second Chance): circular list checking use bit. ARC (Adaptive Replacement Cache): dynamically self-tunes between recency and frequency.",
    "1.3.5": "Stack: contiguous LIFO memory region per thread, managed directly by CPU stack pointer register (RSP), zero allocation overhead, auto-freed on function return, prone to stack overflow on deep recursion. Heap: dynamically allocated memory (malloc/new), runtime lifetime, prone to fragmentation, memory leaks, and allocator contention.",
    "1.3.6": "User-space allocators bridging malloc()/free() with kernel brk()/mmap() syscalls. Employs freelists, segregated fits, and buddy allocators. Production allocators (jemalloc, TCMalloc) utilize per-thread arenas and thread-local caches to eliminate lock contention on multi-core concurrent allocations.",
    "1.3.7": "Automated runtime memory reclamation. Reference Counting: immediate reclamation, zero pause, but cannot collect cyclic graphs and incurs atomic counter overhead. Tracing GC (Mark-Sweep, Generational): divides heap into Eden/Young/Tenured based on generational hypothesis ('most objects die young'); modern collectors (ZGC, Go GC) perform concurrent marking to reduce Stop-the-World pauses under 1ms.",

    # 1.4 I/O & File Systems
    "1.4.1": "Inodes store file metadata (permissions, owner, timestamps, file size, block pointers/extents) independently of filenames. Directories are specialized files containing tables mapping string filenames to inode numbers. Hard links share the same inode; symbolic links point to another path string.",
    "1.4.2": "Crash-resilient file system architecture (ext4, NTFS, XFS). Writes file metadata (and optionally payload blocks) sequentially to a dedicated circular Write-Ahead Log (WAL) journal before updating physical disk blocks. Enables rapid post-crash recovery by replaying or rolling back unfinished journal transactions, eliminating slow fsck scans.",
    "1.4.3": "Blocking I/O: calling thread suspends in kernel wait queue until hardware data transfer completes (simple programming model, but requires 1:1 thread per connection). Non-blocking I/O (O_NONBLOCK): read/write syscalls return immediately with EAGAIN/EWOULDBLOCK if buffer is not ready, enabling single-threaded event loop multiplexing.",
    "1.4.4": "I/O Multiplexing primitives. select(): O(N) linear array scan, 1024 fd limit. poll(): O(N) scan without fd limit. epoll (Linux) & kqueue (BSD/macOS): O(1) event-driven notification using in-kernel Red-Black tree for interest registration and a ready-list linked list; supports Level-Triggered (poll-like) and Edge-Triggered (state change only). Modern Linux io_uring uses shared ring-buffers for zero-syscall async I/O.",
    "1.4.5": "Hardware mechanism allowing high-throughput network cards, NVMe controllers, and disk controllers to transfer raw data blocks directly to/from main system RAM via system bus without CPU intervention. Mitigates CPU interrupt storms via interrupt coalescing and ring buffers.",

    # 1.5 IPC
    "1.5.1": "Kernel-managed unidirectional FIFO byte-stream communication buffer (typically 64KB). Anonymous pipes: parent-child process communication via inherited file descriptors (created via pipe()). Named pipes (FIFOs, created via mkfifo): visible in file system namespace, allowing unrelated processes to communicate over standard file I/O operations.",
    "1.5.2": "Fastest IPC mechanism available on modern OS. Multiple processes map identical physical memory pages into their respective virtual address spaces via mmap() or shmget(). Zero-copy data exchange directly in RAM at memory bus speeds. Trade-off: requires external user-level synchronization (POSIX semaphores, mutexes) to avoid race conditions.",
    "1.5.3": "Kernel-persisted discrete message queues (POSIX mq_open, System V msgget). Allows processes to exchange structured, prioritized message packets asynchronously without maintaining an active concurrent connection. Senders write and exit; receivers retrieve highest-priority messages on demand.",
    "1.5.4": "Bidirectional IPC endpoint utilizing standard socket APIs (socket(AF_UNIX)) for processes running on the same host kernel. Bypasses the network stack, IP routing, checksum calculations, and packet framing, delivering over 2x throughput of localhost loopback TCP. Crucially supports passing open file descriptors between processes via SCM_RIGHTS.",
    "1.5.5": "Asynchronous software interrupts delivered by the kernel to a process to notify events. Handled via default action, ignore, or custom signal handler. Critical distinction: SIGTERM (15) requests graceful termination allowing cleanup; SIGKILL (9) and SIGSTOP (19) immediately freeze/kill the process at the kernel level and cannot be caught, blocked, or ignored.",

    # =========================================================================
    # Section 2: Networking (23 concepts)
    # =========================================================================
    # 2.1 OSI & TCP/IP Models
    "2.1.1": "Theoretical 7-layer networking stack: Physical (bits, signals), Data Link (MAC frames, Ethernet, switches), Network (IP packets, routing), Transport (TCP/UDP segments, ports), Session (RPC session maintenance), Presentation (data serialization, encryption/TLS), Application (HTTP, DNS, SSH, gRPC).",
    "2.1.2": "Practical 4-layer architecture powering the internet: Link/Network Access (Ethernet, Wi-Fi, ARP), Internet (IPv4, IPv6, ICMP, BGP routing), Transport (TCP, UDP, QUIC), Application (HTTP, DNS, TLS, SMTP). Consolidates OSI layers 5-7 into Application and layers 1-2 into Link.",
    "2.1.3": "Outbound transmission wraps data recursively with layer-specific headers (Application payload -> TCP header [ports, seq] -> IP header [source/dest IP, TTL] -> Ethernet frame [MAC addresses, CRC trailer]). Inbound reception decapsulates each header layer upon validation.",

    # 2.2 IP & Routing
    "2.2.1": "32-bit addresses providing ~4.29 billion global unique addresses. Exhausted in 2011. Mitigated by Classless Inter-Domain Routing (CIDR), Network Address Translation (NAT), and private address spaces (RFC 1918: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16).",
    "2.2.2": "128-bit address space (3.4 × 10^38 addresses), eliminating the need for NAT. Features mandatory IPsec support, simplified 40-byte fixed header (no header checksum for faster router processing), SLAAC (stateless address autoconfiguration), and multicast replacing broadcast.",
    "2.2.3": "CIDR notation (e.g. 192.168.1.0/24) specifies network prefix length. Subnet masks divide IP addresses into network portion (routing identifier) and host portion. Enables route aggregation (supernetting) to prevent global internet routing table explosion.",
    "2.2.4": "Network Address Translation: maps multiple private internal IP addresses to a single public IP address using ephemeral Layer 4 port mappings (NAPT/PAT). Modifies IP and TCP/UDP checksums in real-time. Impedes direct peer-to-peer connectivity, necessitating STUN, TURN, and ICE traversal protocols.",
    "2.2.5": "BGP (Border Gateway Protocol): path-vector exterior gateway protocol routing traffic between Autonomous Systems (AS) across the global internet using policy-based routing. OSPF (Open Shortest Path First): link-state interior gateway protocol utilizing Dijkstra's algorithm for fast intra-datacenter routing.",
    "2.2.6": "Internet Control Message Protocol (Layer 3 diagnostic protocol). Encapsulated in IP packets without transport ports. ping uses ICMP Echo Request (Type 8) and Echo Reply (Type 0). traceroute sends incrementing TTL packets, discovering hops when intermediate routers return ICMP Time Exceeded (Type 11).",

    # 2.3 TCP & UDP
    "2.3.1": "Full-duplex, connection-oriented, reliable byte-stream protocol. Guarantees in-order delivery via sequence numbers and cumulative ACKs, provides end-to-end reliability via retransmissions (RTO calculation based on SRTT), prevents buffer overflow via sliding window flow control, and protects the network via congestion control.",
    "2.3.2": "Connection establishment: Client sends SYN (seq=x); Server replies with SYN-ACK (seq=y, ack=x+1); Client sends ACK (ack=y+1). Mitigates SYN flood attacks using SYN Cookies (cryptographically encoding state into sequence number without allocating server TCB memory until ACK arrives). Termination uses a 4-way FIN/ACK handshake, concluding in TIME_WAIT state (2*MSL, typically 60s) to prevent lingering delayed packets from corrupting new connections.",
    "2.3.3": "Congestion window (cwnd) management. Slow Start: exponential growth doubling cwnd each RTT until ssthresh. Congestion Avoidance: AIMD linear additive increase. Fast Retransmit: 3 duplicate ACKs trigger instant retransmission without waiting for RTO timer. Algorithms: TCP Reno (loss-based, halving window), TCP Cubic (cubic polynomial curve, standard in Linux for high bandwidth-delay product networks), Google BBR (model-based: measures Bottleneck Bandwidth and min-RTT to operate at optimal pipe capacity without causing bufferbloat).",
    "2.3.4": "Minimalist connectionless transport protocol (8-byte header: Source Port, Dest Port, Length, Checksum). No handshakes, no acknowledgments, no ordering, no retransmissions, zero head-of-line blocking. Ideal for real-time multiplayer gaming, VoIP/video conferencing (RTP), DNS lookups, and modern custom protocols like QUIC.",
    "2.3.5": "UDP-based transport protocol standardized as the foundation for HTTP/3. Embeds TLS 1.3 encryption natively to eliminate connection latency (1-RTT or 0-RTT connection resumption). Multiplexes independent streams without transport-layer Head-of-Line blocking (loss on stream A does not stall stream B). Supports seamless Connection Migration across network changes (Wi-Fi to 5G) via 64-bit Connection IDs.",
    "2.3.6": "A network socket represents an OS IPC abstraction identified by a 5-tuple: (Source IP, Source Port, Dest IP, Dest Port, Protocol). Well-known ports (0-1023: HTTP 80, HTTPS 443, SSH 22, DNS 53), registered ports (1024-49151), and dynamic ephemeral ports (49152-65535).",

    # 2.4 HTTP & DNS
    "2.4.1": "Stateless client-server protocol. Request: HTTP Method (GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS), URI path, headers (Host, User-Agent, Content-Type, Authorization), and optional payload body. Response: Status Code (1xx Info, 2xx Success, 3xx Redirect, 4xx Client Error, 5xx Server Error), response headers, and payload.",
    "2.4.2": "HTTP/1.1: textual protocol, keep-alive persistent connections, pipelining suffered from severe Head-of-Line blocking. HTTP/2: binary framing layer, multiplexed bidirectional streams over a single TCP connection, HPACK header compression, server push (TCP HOL blocking persists on packet loss). HTTP/3: built on UDP/QUIC, eliminates TCP HOL blocking, integrates TLS 1.3 0-RTT, and enables instant connection migration.",
    "2.4.3": "Hierarchical name resolution: Browser Cache -> OS Resolver Cache (hosts file) -> Recursive DNS Resolver (ISP/Cloudflare 1.1.1.1/Google 8.8.8.8) -> Root Nameservers ('.') -> TLD Nameservers ('.com') -> Authoritative Nameservers ('example.com'). Recursive resolver caches responses adhering to TTL directives.",
    "2.4.4": "Core DNS zone records: A (maps hostname to IPv4 address), AAAA (maps to 128-bit IPv6 address), CNAME (canonical name alias pointing to another hostname, cannot coexist with other records at zone apex), ALIAS/ANAME (virtual CNAME resolved at apex by DNS server), MX (mail exchange records with priority weights), TXT (arbitrary text; critical for SPF, DKIM, and domain ownership verification).",
    "2.4.5": "Multi-tier caching hierarchy minimizing DNS lookup latency (which costs 20-120ms). Governed by Time-To-Live (TTL) field set by domain administrators. High TTL (86400s) maximizes cache hit rates and reduces resolver load; low TTL (60s) enables rapid failover during migrations or disaster recovery events.",

    # 2.5 TLS / Security
    "2.5.1": "Cryptographic transport layer security. TLS 1.2 requires 2 full round-trips (2-RTT) to negotiate cipher suites, exchange key parameters (RSA/Diffie-Hellman), and verify certificates. TLS 1.3 cuts handshake latency to 1-RTT (and 0-RTT Early Data for resumed sessions) by mandating Ephemeral Diffie-Hellman (PFS) and deprecating insecure legacy ciphers (RC4, 3DES, MD5, SHA-1).",
    "2.5.2": "Public Key Infrastructure: enables trust without prior communication. Servers present an X.509 certificate signed by an intermediate Certificate Authority (CA), forming a cryptographic chain of trust validated against Root CA certificates pre-installed in the client OS trust store. Mutual TLS (mTLS) enforces two-way verification where clients must also present certificates to authenticate microservices.",
    "2.5.3": "HSTS (HTTP Strict Transport Security): response header instructing browsers to automatically upgrade all insecure HTTP requests to HTTPS for a declared duration (e.g. max-age=31536000; includeSubDomains; preload), thwarting SSL-stripping attacks. OCSP Stapling: server periodically queries CA for signed revocation status and staples it directly to the TLS handshake, eliminating client-side OCSP blocking latency and privacy leaks.",

    # =========================================================================
    # Section 3: Databases (22 concepts)
    # =========================================================================
    # 3.1 SQL Basics
    "3.1.1": "Relational algebra set operations. INNER JOIN: returns rows with matching keys in both tables. LEFT/RIGHT OUTER JOIN: preserves all rows from left/right table, populating unmatched columns with NULL. FULL OUTER JOIN: preserves all rows from both tables. CROSS JOIN: Cartesian product (N × M rows). In query engines, implemented via Nested Loop Join (O(M×N), fast with index), Hash Join (O(M+N), builds in-memory hash table for large unindexed datasets), or Sort-Merge Join (O(M log M + N log N), optimal for pre-sorted inputs).",
    "3.1.2": "Data summarization operations. GROUP BY partitions rows sharing identical grouping keys. Aggregates (COUNT, SUM, AVG, MIN, MAX) compute scalar metrics per group. Critical interview distinction: WHERE filters individual rows before grouping occurs; HAVING filters aggregated groups after GROUP BY evaluation.",
    "3.1.3": "Computes aggregate-like calculations across a subset ('window') of rows while preserving individual row identities (unlike GROUP BY which collapses rows). Syntax: `OVER (PARTITION BY ... ORDER BY ...)`. Includes ranking (ROW_NUMBER(), RANK(), DENSE_RANK()), offset navigation (LAG(), LEAD()), and cumulative running totals (SUM() OVER (...)).",
    "3.1.4": "Common Table Expressions (WITH clause): defines temporary named result sets scoped to the execution of a single query, significantly improving SQL readability and modularity over deeply nested subqueries. Recursive CTEs enable traversal of hierarchical and graph structures (e.g. organizational charts, bill-of-materials, ancestor trees).",
    "3.1.5": "Non-correlated subqueries execute once, allowing optimizer substitution. Correlated subqueries reference outer query columns and evaluate repeatedly for every outer row (O(N×M) penalty if unindexed). Modern cost-based optimizers rewrite subqueries into equivalent JOINs or semi-joins (EXISTS/IN) to leverage index scans and hash joins.",

    # 3.2 Normalization
    "3.2.1": "Systematic database design reducing data redundancy and preventing update anomalies. 1NF: atomic column values, unique rows (primary key). 2NF: 1NF + no partial dependency (all non-key attributes fully dependent on whole candidate key). 3NF: 2NF + no transitive dependencies (non-key attributes depend only on the primary key). BCNF (Boyce-Codd): stricter 3NF where every determinant must be a candidate key.",
    "3.2.2": "Deliberate introduction of controlled redundancy into normalized schemas (e.g. precomputed totals, duplicate customer names in order tables) to eliminate expensive multi-table JOINs and reduce read latency in read-heavy applications. Trade-offs: increased storage footprint, higher write latency (write amplification), and severe risk of data inconsistency requiring distributed transactions or background reconciliation jobs.",

    # 3.3 Indexes
    "3.3.1": "Index data structures. B+ Tree: self-balancing search tree with high fanout (100-500) and low depth (3-4); stores records/pointers only in leaf nodes connected via doubly linked list, optimizing range scans and equality lookups. Hash Index: O(1) equality lookups, but completely incapable of range queries or sorting. GIN (Generalized Inverted Index): maps components (JSON keys, full-text words, array elements) to row pointers, essential for document and full-text search.",
    "3.3.2": "Clustered Index: dictates the physical ordering of table rows on disk; leaf pages contain the actual table data rows (only 1 clustered index permitted per table, typically the Primary Key). Non-Clustered (Secondary) Index: independent B+ tree structure whose leaf nodes contain index keys and a pointer/primary key to the physical data row; secondary queries require a secondary lookup ('bookmark lookup') unless all requested columns exist in the index ('Covering Index').",
    "3.3.3": "Multi-column index (e.g. index on (A, B, C)). Governed by the Leftmost Prefix Rule: queries can utilize the index for filtering if they constrain the leading column (A), (A, B), or (A, B, C). Queries filtering on (B) or (C) alone cannot navigate the tree root and result in a full index/table scan.",
    "3.3.4": "Cardinality: the count of distinct values in a column. Selectivity: the ratio of distinct values to total rows (`cardinality / total_rows`). High selectivity (~1.0, e.g. UUID, email, user_id) makes an index extremely efficient. Low selectivity (e.g. boolean flags, gender status) causes query optimizers to bypass the index in favor of a sequential table scan because random disk I/O from index lookups costs more than sequential reading.",
    "3.3.5": "Query profiling commands. EXPLAIN outputs the query execution plan generated by the cost-based optimizer (showing anticipated cost, estimated rows, and selected join/scan operators). EXPLAIN ANALYZE actually executes the query and reports real runtime execution times, actual row counts, memory/buffer usage, and disk spill metrics (identifying Seq Scans, nested loops, and temporary disk sorts).",

    # 3.4 Transactions & Isolation
    "3.4.1": "Atomicity: all operations in a transaction succeed together or rollback completely via Write-Ahead Log (WAL) or undo logs. Consistency: transactions transition database from one valid state to another, satisfying all schema constraints, foreign keys, and triggers. Isolation: concurrent transactions execute without interfering with one another. Durability: committed changes persist through crashes and power loss via fsync to non-volatile storage.",
    "3.4.2": "ANSI SQL Isolation Levels: Read Uncommitted (allows dirty reads, no read locks), Read Committed (prevents dirty reads, reads latest committed snapshot per statement), Repeatable Read (prevents non-repeatable reads, reads snapshot taken at transaction start), Serializable (highest isolation, guarantees concurrent execution is equivalent to some serial ordering).",
    "3.4.3": "Concurrency anomalies. Dirty Read: reading uncommitted data written by a concurrent transaction that later rolls back. Non-repeatable (Fuzzy) Read: re-reading the same row returns modified column values committed by another transaction. Phantom Read: re-executing a range query returns newly inserted/deleted rows matching the predicate. Write Skew: concurrent transactions read overlapping data, make disjoint modifications, and commit invalid state violating cross-row constraints.",
    "3.4.4": "Multi-Version Concurrency Control: concurrent transactions see point-in-time consistent snapshots without blocking writers, and writers do not block readers. Implemented via row versioning: PostgreSQL appends new tuple versions with `xmin`/`xmax` transaction IDs and reclaims dead tuples via VACUUM; MySQL InnoDB modifies rows in-place in clustered index pages and stores previous versions in an Undo Log rollback segment.",
    "3.4.5": "Locking mechanisms: Shared Locks (S-locks, read locks, multiple concurrent holders) and Exclusive Locks (X-locks, write locks, single holder). Deadlock occurs when two or more transactions hold locks the other needs in a circular wait dependency (e.g., T1 holds A, waits for B; T2 holds B, waits for A). Resolved by engine via Deadlock Detection (wait-for graph cycle hunting and aborting the cheapest victim transaction) or Deadlock Prevention (wait-die or wound-wait timestamp schemes).",
    "3.4.6": "Optimistic Concurrency Control (OCC): transactions execute reads and writes without acquiring locks under the assumption that conflicts are rare. Upon commit, the transaction validates whether data changed during its execution (typically by verifying a `version` integer column or timestamp). If conflicted, the transaction aborts and retries. Superior throughput for read-heavy, low-contention workloads.",

    # 3.5 NoSQL types
    "3.5.1": "Stores semi-structured data as JSON/BSON documents with dynamic, flexible schemas (MongoDB, Couchbase). Allows embedding child entities (e.g. order items inside order document) to enable atomic single-document reads without joins. Ideal for catalogs, content management, and rapidly evolving domain models.",
    "3.5.2": "High-performance data store associating opaque or structured data values with unique string keys (Redis, Memcached, DynamoDB). In-memory engines deliver sub-millisecond latencies using single-threaded event loops (Redis) and specialized in-memory data structures (Hashes, Sorted Sets, Bitmaps, HyperLogLogs). Employs persistence strategies: RDB snapshots and AOF (Append-Only File) journals.",
    "3.5.3": "Distributed column-family architecture derived from Google Bigtable (Apache Cassandra, ScyllaDB). Organizes data by Partition Key (hashed via consistent hashing to locate replica nodes) and Clustering Key (determines physical on-disk sort order within the partition). Powered by LSM-Trees; excels at high-throughput write-intensive workloads, time-series data, and petabyte-scale horizontal scaling with tunable consistency (QUORUM).",
    "3.5.4": "Graph database modeling complex, highly interconnected networks as explicit Nodes, Directed Edges (Relationships), and Properties (Neo4j, AWS Neptune). Implements Index-Free Adjacency where each node acts as a micro-index with direct memory pointers to adjacent neighbors, providing O(1) relationship traversal times independent of total graph size. Essential for social networks, fraud detection, and recommendation engines.",

    # =========================================================================
    # Section 4: Concurrency & Parallelism (22 concepts)
    # =========================================================================
    # 4.1 Concurrency vs Parallelism
    "4.1.1": "Concurrency is about structure: dealing with lots of things at once by decomposing a program into independent execution units (threads, coroutines, event loops) that can be interleaved on a single core or executed across multiple cores. Focuses on responsiveness, coordination, and non-blocking I/O.",
    "4.1.2": "Parallelism is about execution: physically doing lots of things at the exact same instant by utilizing multiple CPU hardware cores, SIMD vector units, or distributed nodes. Requires hardware support and focuses strictly on computational throughput and latency reduction for compute-heavy workloads.",
    "4.1.3": "Theoretical formula bounding maximum speedup S = 1 / ((1-p) + p/N), where p is the parallelizable fraction of the task and N is the number of processor cores. Demonstrates that even with infinite cores (N -> inf), maximum speedup is strictly capped by the serial fraction 1/(1-p) (e.g., if 5% of code is sequential, max theoretical speedup is 20x). Contrasted with Gustafson's Law for scaling problem sizes.",

    # 4.2 Synchronization Primitives
    "4.2.1": "Mutual Exclusion lock: guarantees that only a single thread can execute inside a designated critical section at any given moment. Blocking mutexes (e.g. pthread_mutex) place contending threads into an OS sleep queue via the Linux futex syscall. Critical trade-off: prevents race conditions but incurs context switch overhead (~1-2µs) when contention occurs.",
    "4.2.2": "Signaling mechanism maintaining an internal integer counter protected by atomics. Counting Semaphore: initialized to N permits, allowing up to N concurrent threads into a resource pool (e.g. database connection pool, rate limiter). Binary Semaphore: permit count 0 or 1, similar to a mutex but differs fundamentally: a semaphore has no concept of ownership (thread A can post/release a semaphore acquired by thread B).",
    "4.2.3": "Signaling primitive enabling threads to suspend execution (sleep) until notified that a specific application state condition has become true (paired with an associated mutex). Always requires checking the condition inside a while loop (never if) to guard against Spurious Wakeups (waking without explicit signal) and race conditions before lock reacquisition.",
    "4.2.4": "Reader-Writer Lock (Shared-Exclusive lock): allows unlimited simultaneous reader threads (Shared lock) or exactly one writer thread (Exclusive lock). Drastically boosts read throughput in read-heavy workloads (e.g., routing tables, config caches). Must be carefully designed to prevent Writer Starvation (continuous incoming readers blocking a pending writer) using fair queueing or write-preference policies.",
    "4.2.5": "Spinlock: contending threads repeatedly execute a tight CPU polling loop ('spin') testing an atomic flag instead of yielding the CPU. Optimal only when the critical section is extremely brief (< context switch latency ~1µs) and on multi-core systems; disastrous on single-core or long-running sections as it burns 100% CPU.",
    "4.2.6": "Hardware CPU instructions executing read-modify-write operations uninterruptedly at the memory bus level without locking: test-and-set, fetch-and-add, and Compare-And-Swap (CMPXCHG on x86). CAS compares a memory location against an expected value; if equal, it updates to the new value in a single atomic cycle and returns success. Foundation for lock-free queues, stacks, and counters.",
    "4.2.7": "Thread-safe coordination barriers. Barrier: synchronizes a fixed group of N threads at a designated execution milestone; all threads block until the last thread reaches the barrier, whereupon all are released simultaneously (reusable, e.g. CyclicBarrier). Latch: one-time countdown trigger (CountDownLatch); threads wait until the counter reaches zero before proceeding.",

    # 4.3 Classic Problems
    "4.3.1": "Permanent stall where two or more threads cannot proceed because each is waiting for a resource held by another. Four Coffman Conditions must hold simultaneously: 1. Mutual Exclusion, 2. Hold and Wait, 3. No Preemption, 4. Circular Wait. Eliminating any single condition prevents deadlock (most commonly breaking Circular Wait via strict total ordering of lock acquisition).",
    "4.3.2": "Active threads continuously change internal state in response to each other without making any forward progress (like two polite people in a narrow hallway repeatedly stepping to the same side in unison). State changes actively consume CPU cycles, unlike deadlock where threads sleep.",
    "4.3.3": "Starvation: a runnable thread is perpetually denied access to a shared resource or CPU time due to biased scheduling or unfair lock acquisition algorithms. Priority Inversion: a high-priority thread is blocked waiting for a lock held by a low-priority thread, while intermediate-priority threads preempt the low-priority thread, effectively stalling the high-priority task (the Mars Pathfinder bug, solved via Priority Inheritance).",
    "4.3.4": "Flaw where system behavior depends unpredictably on the relative execution timing, interleaving, or order of concurrent threads or processes. Data races occur when two threads access the same memory location concurrently with at least one write and without synchronization. Prevented via mutexes, locks, atomics, or immutable data structures.",
    "4.3.5": "Producer threads append items into a fixed-capacity bounded buffer; consumer threads extract items. Must coordinate access to prevent race conditions on buffer state and handle boundary constraints: producers block when buffer is full (not_full condition), consumers block when buffer is empty (not_empty condition). Implemented via mutex + 2 condition variables or 2 counting semaphores.",
    "4.3.6": "Coordinates concurrent access to shared data between readers and writers. Formulations: First Readers-Writers (favors readers, risks writer starvation), Second Readers-Writers (favors writers, prevents starvation), Third Readers-Writers (fair FIFO queueing using a turnstile semaphore ensuring no thread is starved).",
    "4.3.7": "Classic synchronization problem by Dijkstra: 5 philosophers sit at a table with 5 forks; each requires 2 adjacent forks to eat. Naive approach (each picks left fork, waits for right) causes circular deadlock. Solutions: Resource Hierarchy (number forks 1..5, always acquire lowest-numbered fork first), Arbitrator/Waiter (mutex restricting at most 4 philosophers to table), or Chandy/Misra distributed algorithm.",

    # 4.4 Async & Coroutines
    "4.4.1": "Single-threaded non-blocking concurrency model. Continuously cycles through an event queue dispatching callbacks for completed I/O operations multiplexed via OS kernel primitives (epoll, kqueue, IOCP). Offloads heavy CPU computations or blocking operations to background worker thread pools (libuv) to prevent blocking the main loop.",
    "4.4.2": "Concurrency abstractions representing the eventual deferred result of an asynchronous operation that has not yet completed. Provides state transitions: Pending -> Fulfilled (resolved with value) or Rejected (with error/exception). Enables non-blocking monadic composition (.then(), .catch()) without callback nesting ('callback hell').",
    "4.4.3": "Syntactic sugar over Promises and Coroutines making asynchronous, non-blocking code read sequentially like synchronous code. The await expression pauses the execution of the enclosing async function, yielding control back to the event loop, and resumes once the underlying Promise resolves or rejects.",
    "4.4.4": "OS Threads: kernel-managed preemptive execution contexts with private OS stacks (1-8MB) and high context-switch latency (~1-2µs) due to kernel privilege transitions and TLB pollution. Coroutines: cooperative user-space lightweight execution units (e.g. Go goroutines ~2KB stack, Python coroutines) multiplexed (M:N) over a small pool of OS threads with sub-microsecond context switches.",
    "4.4.5": "Concurrent computation paradigm treating independent, stateful 'Actors' as universal primitives. Actors share zero state; all communication occurs asynchronously via immutable message passing to private actor mailboxes. Each actor processes messages sequentially, preventing race conditions by construction, and provides fault tolerance via hierarchical supervision trees ('let it crash').",

    # =========================================================================
    # Section 5: Security (19 concepts)
    # =========================================================================
    # 5.1 Cryptography
    "5.1.1": "Identical secret key for both encryption and decryption (AES-256, ChaCha20). High throughput (multiple GB/s) powered by hardware acceleration (AES-NI). Modes: AES-GCM provides Authenticated Encryption with Associated Data (AEAD), guaranteeing confidentiality, integrity, and authenticity; CBC requires separate HMAC and is vulnerable to padding oracle attacks.",
    "5.1.2": "Asymmetric cryptography using mathematically linked key pairs: public key encrypts, private key decrypts (RSA-3072, ECC Curve25519/ECDSA). Computationally heavier than symmetric; utilized for secure session key exchange (ECDH) and digital signatures. ECC provides equivalent cryptographic security to RSA with significantly smaller key lengths (256-bit ECC ≈ 3072-bit RSA).",
    "5.1.3": "One-way cryptographic hash functions producing fixed-size digests (SHA-256: 256 bits; BLAKE3: 256 bits). Properties: Pre-image resistance, second pre-image resistance, and collision resistance. High-throughput data integrity checks and content-addressable storage (Git commits, CAS). Never used directly for password storage due to susceptibility to GPU brute-force attacks.",
    "5.1.4": "Deliberately computationally expensive, memory-hard algorithms designed to thwart GPU, FPGA, and ASIC brute-force dictionary attacks. Argon2id (winner of Password Hashing Competition) provides configurable memory cost, time iterations, and parallelism. Bcrypt utilizes a configurable work factor and mandatory unique cryptographic salts to defeat rainbow tables.",
    "5.1.5": "Cryptographic mechanism providing authentication, non-repudiation, and message integrity. The signer encrypts/signs a cryptographic hash of the message using their private key; any recipient verifies the signature using the signer's corresponding public key (e.g. RSA-PSS, Ed25519). If any bit of the payload changes, signature verification fails.",
    "5.1.6": "Hash-based Message Authentication Code: combines a shared secret key with a cryptographic hash function (HMAC-SHA256). Guarantees both message integrity and authenticity: proves the payload was generated by a party holding the shared secret and was not tampered with in transit. Foundation for API request signing (AWS SigV4) and JWT integrity signatures.",

    # 5.2 Auth
    "5.2.1": "Session-based: server maintains stateful session data in a central store (Redis/DB) and issues an opaque session cookie; grants instant revocation, but requires centralized lookups on every request. Token-based: client transmits signed stateless JSON Web Tokens (JWT) in Authorization headers; scales horizontally across microservices, but token revocation before TTL expiry is non-trivial (requires token blocklists).",
    "5.2.2": "Authorization delegation framework allowing third-party applications limited access to an HTTP resource without exposing user passwords. Primary flows: Authorization Code Flow with PKCE (Proof Key for Code Exchange) for Single-Page Apps (SPAs) and mobile clients; Client Credentials Flow for machine-to-machine service authentication; Refresh Token Flow for refreshing expired access tokens.",
    "5.2.3": "Identity layer built directly on top of OAuth 2.0. While OAuth 2.0 provides authorization (access tokens for API resources), OIDC standardizes authentication, issuing an id_token (signed JWT) containing claims about the authenticated end-user (sub, email, exp) along with a standardized /userinfo endpoint.",
    "5.2.4": "Security Assertion Markup Language: XML-based open federated authentication and authorization standard predominantly utilized in enterprise single sign-on (SSO) environments. Exchanges cryptographically signed XML assertions between an Identity Provider (IdP, e.g. Okta, Azure AD) and a Service Provider (SP, e.g. Salesforce, corporate portals).",
    "5.2.5": "Multi-Factor Authentication combining two or more independent factors: knowledge (password), possession (TOTP authenticator app, SMS), and inherence (biometrics). WebAuthn (FIDO2 standard) replaces phishable shared secrets with asymmetric public-key cryptography tied to hardware security keys (YubiKey) or platform authenticators (TouchID, Windows Hello); immune to phishing and man-in-the-middle attacks.",
    "5.2.6": "Access control paradigms. RBAC (Role-Based Access Control): assigns permissions to predefined roles (e.g. Admin, Editor, Viewer), and binds users to roles; simple to audit and manage, but suffers from role explosion in complex organizations. ABAC (Attribute-Based Access Control): dynamically evaluates access policies against attributes of the user, resource, action, and environment context (e.g. IP location, time of day); fine-grained and expressive.",

    # 5.3 Web Security (OWASP)
    "5.3.1": "OWASP Top 1: untrusted user-supplied input is directly concatenated or interpolated into interpreter commands (SQL, NoSQL, OS shell, LDAP), enabling attackers to manipulate query logic, bypass authentication, or execute arbitrary commands. Remediation: mandatory use of Parameterized Queries (Prepared Statements) where query structure is compiled separately and input is strictly treated as data; Object-Relational Mappers (ORMs); and input validation.",
    "5.3.2": "Failures in identity verification mechanisms allowing attackers to compromise passwords, session keys, or impersonate legitimate users. Common vulnerabilities: credential stuffing, missing brute-force rate limits, session fixation, permissive password policies, and exposed session identifiers in URLs. Remediation: enforce MFA, robust session management (regenerate session IDs on login), and rate-limiting.",
    "5.3.3": "Cross-Site Scripting: injection of malicious client-side JavaScript executed within a victim's browser context. Types: Stored XSS (persisted in DB), Reflected XSS (mirrored in immediate request URL/parameters), DOM XSS (vulnerable client JavaScript manipulation). Exploits: stealing session cookies, redirecting users, modifying DOM. Remediation: Context-aware HTML entity encoding, Content Security Policy (CSP) headers, and modern frameworks (React) that auto-escape JSX values.",
    "5.3.4": "Cross-Site Request Forgery: tricks an authenticated user's browser into executing unwanted state-mutating actions on a trusted web application using the victim's existing session cookies. Remediation: Set SameSite=Strict or SameSite=Lax on session cookies, and validate cryptographically random Anti-CSRF Tokens (synchronizer token pattern) on all state-mutating requests (POST/PUT/DELETE).",
    "5.3.5": "Vulnerability occurring when untrusted data is processed by language deserializers (Python pickle, Java ObjectInputStream, PHP unserialize), allowing attackers to instantiate arbitrary classes, manipulate application logic, or execute Remote Code Execution (RCE). Remediation: avoid native language serialization for untrusted input; use standard safe formats (JSON, Protocol Buffers) with strict schema validation.",
    "5.3.6": "Server-Side Request Forgery: an attacker induces the backend server to make unauthorized HTTP requests to an arbitrary destination. Severe risk in cloud environments: attackers query internal cloud metadata services (http://169.254.169.254/latest/meta-data/iam/security-credentials/) to exfiltrate IAM credentials. Remediation: strict allowlists for outbound URLs, disabling unused protocols, and requiring IMDSv2 (session tokens).",
    "5.3.7": "Prevalent vulnerability arising from default credentials, unpatched software, unnecessary enabled features, permissive CORS policies (Access-Control-Allow-Origin: *), verbose error stack traces exposed to end-users, and misconfigured cloud storage buckets (public S3 buckets). Remediation: automated infrastructure-as-code hardening, automated security scanners, and least-privilege configurations.",

    # =========================================================================
    # Section 6: Computer Architecture (14 concepts)
    # =========================================================================
    # 6.1 CPU Architecture
    "6.1.1": "Fundamental CPU execution cycle. Fetch: load instruction from memory pointed to by Instruction Pointer (RIP) into Instruction Register. Decode: micro-op decoders interpret opcode and operand specifiers. Execute: ALU/FPU executes arithmetic, logic, or control operations. Memory Access: load or store data to/from L1 data cache. Writeback: commit execution results to the target architectural register.",
    "6.1.2": "Instruction pipelining overlaps the execution stages of multiple consecutive instructions simultaneously (like an assembly line). Classic 5-stage RISC pipeline: IF, ID, EX, MEM, WB. Pipelining hazards: Structural (resource contention), Data (Read-After-Write RAW dependencies requiring operand forwarding), and Control (conditional branches).",
    "6.1.3": "Microarchitectural mechanism that predicts the outcome and target of conditional branch instructions before they are evaluated, keeping the instruction pipeline full. Modern CPUs use two-level adaptive predictors, Branch Target Buffers (BTB), and TAGE predictors. A branch misprediction forces a pipeline flush, discarding speculatively fetched instructions and incurring a 15-20 cycle penalty.",
    "6.1.4": "Microarchitectural optimization where the CPU dynamically executes independent instructions as soon as their operand data becomes available, rather than waiting for prior stalled instructions (e.g. cache misses). Employs reservation stations, Register Renaming (eliminating false WAW and WAR dependencies), and a Reorder Buffer (ROB) to ensure instructions commit in strict architectural program order.",
    "6.1.5": "Single Instruction, Multiple Data: hardware vector execution units operating on multiple packed data values simultaneously in a single CPU instruction (Intel AVX2 operates on 256-bit registers holding 8 32-bit floats; AVX-512 operates on 512-bit registers). Delivers massive speedups for graphics, scientific computing, matrix multiplication, cryptography, and deep learning tensor operations.",

    # 6.2 Memory Hierarchy
    "6.2.1": "Physical latency and capacity hierarchy. CPU Registers (~0.5ns, 1 cycle) -> L1 Cache (~1ns, 4 cycles, 32-64KB per core) -> L2 Cache (~4ns, 14 cycles, 512KB-1MB per core) -> L3 Cache (~10-20ns, 40-75 cycles, 16-64MB shared across cores) -> Main Memory DRAM (~60-100ns, 200 cycles, gigabytes) -> NVMe SSD (~50-100µs) -> Disk / Network (~1-100ms). Designing algorithms with high cache hit rates yields orders of magnitude speedups.",
    "6.2.2": "Hardware protocol ensuring uniform memory views across multi-core private caches. The MESI protocol categorizes cache lines (typically 64 bytes) into 4 states: Modified (dirty, exclusively cached), Exclusive (clean, exclusively cached), Shared (clean, present in multiple caches), and Invalid. Writes to a shared line broadcast invalidation requests over the bus/interconnect to keep caches coherent.",
    "6.2.3": "Cache Line: the fundamental 64-byte unit of data transfer between main memory and CPU caches. False Sharing: insidious multi-threaded performance degradation occurring when threads running on different cores modify distinct, independent variables that happen to reside within the exact same 64-byte cache line. Causes perpetual ping-pong invalidations across cores; eliminated by aligning variables to 64-byte boundaries with padding.",
    "6.2.4": "Foundational caching principles. Spatial Locality: accessing a memory location makes nearby addresses likely to be accessed soon (exploited by loading entire 64-byte cache lines and hardware stride prefetchers; e.g. sequential array iteration). Temporal Locality: accessing a memory address makes the same location likely to be re-accessed soon (exploited by retaining recently accessed cache lines in L1/L2 caches).",
    "6.2.5": "Data organization optimized for CPU cache lines and memory prefetching. Contiguous memory arrays (vectors) drastically outperform node-based pointer chains (linked lists, binary trees) which cause frequent cache misses and pointer-chasing stalls. Struct-of-Arrays (SoA) layout groups identical attributes contiguously for vectorization, outperforming Array-of-Structs (AoS) when processing subsets of fields.",

    # 6.3 Data Representation
    "6.3.1": "Standard binary encoding for signed integers. The most significant bit (MSB) acts as a negative sign weight (-2^(N-1)). Key advantages: unified hardware arithmetic adder circuitry for both addition and subtraction, and a single unique representation of zero (eliminating the positive/negative zero ambiguity of sign-magnitude). Overflow occurs when arithmetic wraps across the MSB boundary.",
    "6.3.2": "Universal standard for floating-point arithmetic representation: 1 sign bit, exponent bits (with bias), and fraction/mantissa bits. Formats: Single precision (float32: 1+8+23 bits) and Double precision (float64: 1+11+52 bits). Features special values: +/-0, +/-infinity, and Not-a-Number results (qNaN/sNaN). Pitfalls: non-associative addition, rounding errors, and catastrophic cancellation when subtracting nearly equal numbers.",
    "6.3.3": "Ordering of bytes representing multi-byte words in physical memory. Little-Endian: least significant byte (LSB) stored at the lowest memory address (standard in x86-64 and ARM processors). Big-Endian: most significant byte (MSB) stored at lowest memory address (standard in network protocols, 'Network Byte Order'). Conversions between host and network byte orders utilize htons/ntohs and htonl/ntohl.",
    "6.3.4": "Evolution from 7-bit ASCII (128 characters) to Unicode. UTF-8: backward-compatible variable-length encoding using 1 to 4 bytes per Unicode code point. Single-byte ASCII characters (0-127) encode identically as 1 byte with MSB 0. Multi-byte sequences use self-synchronizing prefix bits (110..., 1110...), preventing framing errors and enabling fast scanning without state machines."
}

def enrich_cs_html():
    with open(CS_HTML_PATH, "r", encoding="utf-8") as f:
        content = f.read()

    # Pattern to match:
    # <li data-cid="CID" ...>...<div class="cname">TITLE</div><div style="font-size:11.5px;color:var(--text-faint);margin-top:2px">OLD_DESC</div>...</li>
    count = 0
    def replacer(match):
        nonlocal count
        full = match.group(0)
        cid = match.group(1)
        if cid in ENRICHMENTS:
            enriched_desc = ENRICHMENTS[cid]
            old_desc = match.group(3)
            new_inner = full.replace(f'>{old_desc}<', f'>{enriched_desc}<')
            count += 1
            return new_inner
        return full

    pattern = re.compile(r'<li\b[^>]*data-cid="([^"]+)"[^>]*>[\s\S]*?<div class="cname">([\s\S]*?)<\/div><div style="font-size:11.5px;color:var\(--text-faint\);margin-top:2px">([\s\S]*?)<\/div>', re.IGNORECASE)
    new_content = pattern.sub(replacer, content)

    # Atomic write
    dir_name = os.path.dirname(CS_HTML_PATH)
    fd, temp_path = tempfile.mkstemp(dir=dir_name, text=True)
    with os.fdopen(fd, "w", encoding="utf-8") as tmp:
        tmp.write(new_content)
    os.replace(temp_path, CS_HTML_PATH)
    print(f"Successfully enriched {count} concepts in cs_fundamentals.html!")

if __name__ == "__main__":
    enrich_cs_html()
