// Gap-coverage sections generated into each concept page. Every topic below was
// flagged as a missing/priority candidate in content-audit.md.
// Format per source key: { num, hue, title, tagline, when, keyIdea, resources, subsections }
export const gapSections = {
  sd: {
    num: 15,
    hue: 285,
    title: "Low-Level Design & Object-Oriented Design",
    tagline: "Implementation-level design: classes, modules, interfaces, object models, UML, and design patterns.",
    when: "After the high-level architecture is clear, or whenever the interviewer asks for object models, APIs, schemas, or machine-coding design.",
    keyIdea: "HLD explains how services collaborate; LLD explains how code units collaborate. Keep the boundary clear.",
    resources: [
      ["Doc", "GFG Low-Level Design Tutorial", "GeeksforGeeks", "https://www.geeksforgeeks.org/system-design/what-is-low-level-design-or-lld-learn-system-design/"],
      ["Doc", "HLD vs LLD Difference", "GeeksforGeeks", "https://www.geeksforgeeks.org/system-design/difference-between-high-level-design-and-low-level-design/"],
      ["Doc", "Object-Oriented Analysis and Design", "GeeksforGeeks", "https://www.geeksforgeeks.org/software-engineering/object-oriented-analysis-and-design/"],
      ["Doc", "SOLID Principles", "GeeksforGeeks", "https://www.geeksforgeeks.org/system-design/solid-principle-in-programming-understand-with-real-life-examples/"],
      ["Doc", "UML Introduction", "GeeksforGeeks", "https://www.geeksforgeeks.org/system-design/unified-modeling-language-uml-introduction/"],
      ["Doc", "Design Patterns", "GeeksforGeeks", "https://www.geeksforgeeks.org/system-design/software-design-patterns/"],
      ["Course", "Thita LLD Learning Path", "Thita", "https://thita.ai/dashboard/learning-path/lld"],
    ],
    subsections: [
      ["HLD vs LLD Boundaries", "Know which level of detail the interviewer is asking for.", [
        ["High-level design scope", "Services, data flow, storage, queues, caches, scaling, and failure modes."],
        ["Low-level design scope", "Classes, interfaces, methods, object relationships, schemas, and in-process behavior."],
        ["When to switch from HLD to LLD", "Switch only after requirements, scale, and major components are clear or the interviewer asks."],
        ["API contract vs class contract", "HLD APIs define service boundaries; LLD interfaces define code boundaries."],
      ]],
      ["Object-Oriented Foundations", "The vocabulary for implementation-level design.", [
        ["Encapsulation", "Hide state behind behavior; expose stable methods instead of internal fields."],
        ["Abstraction", "Model only what the problem needs; avoid leaking implementation details."],
        ["Inheritance vs composition", "Prefer composition for flexible behavior; use inheritance for true is-a relationships."],
        ["Polymorphism", "Depend on interfaces so behavior can vary without branching everywhere."],
      ]],
      ["Design Principles", "Rules that keep low-level designs simple and change-friendly.", [
        ["SOLID principles", "Single responsibility, open-closed, Liskov substitution, interface segregation, dependency inversion."],
        ["DRY principle", "Remove duplicated knowledge, not every repeated line."],
        ["KISS principle", "Prefer the simplest design that satisfies current requirements."],
        ["YAGNI principle", "Do not add future features before there is a real requirement."],
      ]],
      ["UML & Interaction Modeling", "Use diagrams to communicate object behavior, not decorate the answer.", [
        ["Class diagrams", "Show classes, fields, methods, interfaces, inheritance, composition, and cardinality."],
        ["Sequence diagrams", "Show request order and object/service interactions over time."],
        ["Activity diagrams", "Show branching workflows such as checkout, booking, or approval flows."],
        ["State diagrams", "Show lifecycle transitions such as order, ride, payment, or ticket states."],
      ]],
      ["Design Patterns For LLD", "Use patterns as vocabulary for recurring object-design problems.", [
        ["Factory pattern", "Centralize object creation when construction varies by type or configuration."],
        ["Strategy pattern", "Swap algorithms without changing the caller."],
        ["Observer pattern", "Publish state changes to interested subscribers."],
        ["Decorator pattern", "Add behavior by wrapping an object instead of subclassing repeatedly."],
        ["State pattern", "Move state-specific behavior into separate objects instead of giant conditionals."],
      ]],
      ["Machine Coding & LLD Case Studies", "Practice turning requirements into maintainable code structure.", [
        ["Parking lot design", "Model vehicles, spots, tickets, pricing, gates, and payment flow."],
        ["Elevator system design", "Model requests, scheduling strategy, elevator state, and direction changes."],
        ["LRU cache design", "Combine a hash map with a doubly linked list for O(1) get/put."],
        ["BookMyShow / ticket booking LLD", "Model shows, seats, holds, lock expiry, booking, and payment states."],
        ["Splitwise / expense sharing LLD", "Model users, groups, expenses, balances, simplification, and settlement."],
      ]],
    ],
  },
  cs: {
    num: 7,
    hue: 330,
    title: "Languages, Runtimes & Engineering Practice",
    tagline: "Compilers, GC, serialization, distributed basics, testing, and profiling.",
    when: "Language internals questions, debugging sessions, performance interviews, senior-engineer depth.",
    keyIdea: "Code runs on layers you can inspect: compiler, runtime, OS. Learn to look one layer down.",
    resources: [
      ["📖", "Crafting Interpreters (free book)", "Bob Nystrom", "https://craftinginterpreters.com/"],
      ["📖", "CPython Internals", "Real Python", "https://realpython.com/products/cpython-internals-book/"],
      ["📝", "Protocol Buffers Docs", "Google", "https://protobuf.dev/"],
      ["📝", "Jepsen Analyses (distributed systems)", "Jepsen", "https://jepsen.io/analyses"],
      ["📝", "Flame Graphs", "Brendan Gregg", "https://www.brendangregg.com/flamegraphs.html"],
      ["🎓", "MIT 6.824 Distributed Systems", "MIT", "https://pdos.csail.mit.edu/6.824/"],
    ],
    subsections: [
      ["Compilers & Interpreters", "From source code to execution.", [
        ["Compilation pipeline", "Lexing → parsing → AST → optimization → codegen."],
        ["Interpreters vs JIT compilation", "Interpret: simple, slow. JIT: compile hot paths at runtime (V8, JVM)."],
        ["Bytecode and virtual machines", "JVM, CPython compile to bytecode run by a VM."],
        ["Static vs dynamic typing", "Compile-time checks vs runtime flexibility. Gradual typing bridges."],
        ["Linkers, loaders and ABIs", "Static vs dynamic linking; symbol resolution; calling conventions."],
      ]],
      ["Runtimes & Garbage Collection", "How managed languages handle memory.", [
        ["Mark-and-sweep vs generational GC", "Most objects die young — collect the nursery often."],
        ["Reference counting and cycles", "CPython refcounts + cycle detector. Swift ARC needs weak refs."],
        ["Stop-the-world vs concurrent GC", "G1, ZGC, Shenandoah shrink pauses to milliseconds."],
        ["Memory leaks in managed languages", "Leaks = unwanted reachability: caches, listeners, globals."],
      ]],
      ["Serialization & Data Formats", "Moving data between systems safely.", [
        ["JSON vs Protobuf vs Avro", "Text + flexible vs binary + schema vs schema-evolution-first."],
        ["Schema evolution and compatibility", "Backward/forward compatibility; never reuse field numbers."],
        ["Endianness and binary encoding", "Big vs little endian; network byte order is big-endian."],
        ["Text encodings (UTF-8)", "Variable-width, ASCII-compatible, dominant on the web."],
      ]],
      ["Distributed Systems Basics", "The minimum every engineer needs.", [
        ["Fallacies of distributed computing", "The network is not reliable, latency is not zero, topology changes."],
        ["Logical clocks and ordering", "Lamport clocks order events without synchronized time."],
        ["Idempotency and retries", "Safe retries need idempotency keys. Design for duplicates."],
        ["At-least-once vs exactly-once delivery", "Exactly-once = at-least-once + idempotent processing."],
        ["CAP in practice", "Under partition choose C or A. Most systems choose per-operation."],
      ]],
      ["Testing Fundamentals", "Confidence through automation.", [
        ["Test pyramid", "Many unit, fewer integration, few e2e. Invert it and suffer."],
        ["Mocks, stubs and fakes", "Mock: verify calls. Stub: canned answers. Fake: working lightweight impl."],
        ["Property-based testing", "Generate inputs, assert invariants (Hypothesis, QuickCheck)."],
        ["Coverage and mutation testing", "Coverage says executed, mutation testing says actually verified."],
        ["Flaky tests and determinism", "Time, ordering, shared state, network — the four horsemen of flakiness."],
      ]],
      ["Performance Profiling", "Measure before optimizing.", [
        ["CPU profiling and flame graphs", "Sampled stacks → flame graph. Width = time spent."],
        ["Memory profiling and heap dumps", "Find retained size and allocation hot spots."],
        ["Latency percentiles (p50/p95/p99)", "Averages lie. Tail latency drives user experience."],
        ["Benchmarking pitfalls", "JIT warmup, dead-code elimination, coordinated omission."],
        ["Little's law and queueing intuition", "L = λW. Concurrency = throughput x latency."],
      ]],
    ],
  },
  bh: {
    num: 6,
    hue: 25,
    title: "Competency Deep Dives",
    tagline: "The eight competencies interviewers actually probe — each needs a prepared story.",
    when: "Any behavioral round: Amazon LPs, Google GCA, Meta signals, startup culture-fit screens.",
    keyIdea: "One strong, true, quantified story per competency beats ten generic ones.",
    resources: [
      ["📝", "Amazon Leadership Principles (official)", "Amazon", "https://www.amazon.jobs/content/en/our-workplace/leadership-principles"],
      ["📖", "Behavioral Guide", "Tech Interview Handbook", "https://www.techinterviewhandbook.org/behavioral-interview/"],
      ["📝", "STAR Method Guide", "Indeed", "https://www.indeed.com/career-advice/interviewing/how-to-use-the-star-interview-response-technique"],
      ["🎥", "Behavioral Mock Interviews", "interviewing.io", "https://interviewing.io/mocks"],
    ],
    subsections: [
      ["Navigating Ambiguity", "Acting well with incomplete information.", [
        ["Acting with incomplete information", "Story: shipped a decision with 70% certainty. Show the framework you used."],
        ["Defining scope when none is given", "Story: turned a vague ask into a concrete plan with milestones."],
        ["Communicating assumptions", "Story: stated assumptions up front, revisited them when facts changed."],
      ]],
      ["Ownership & Initiative", "Going beyond your job description.", [
        ["Going beyond your role", "Story: fixed something outside your team because it blocked customers."],
        ["Long-term thinking vs quick wins", "Story: chose durable fix over patch and defended the timeline."],
        ["Owning outcomes after handoff", "Story: followed through after the project left your hands."],
      ]],
      ["Conflict & Influence", "Disagreement handled like an adult.", [
        ["Disagreeing with a manager", "Story: disagree and commit — pushed back with data, then aligned."],
        ["Influencing without authority", "Story: convinced another team via prototype, data, or shared goals."],
        ["Driving alignment across teams", "Story: brokered a decision between teams with conflicting incentives."],
      ]],
      ["Failure & Learning", "Real failure, real lesson, real change.", [
        ["Telling a real failure story", "Own the failure fully — no 'my weakness is working too hard'."],
        ["Post-mortems and prevention", "Story: ran a blameless post-mortem and shipped a prevention mechanism."],
        ["Receiving hard feedback", "Story: specific feedback that stung, and the visible behavior change."],
      ]],
      ["Mentoring & Growth", "Multiplying other engineers.", [
        ["Onboarding and coaching juniors", "Story: ramped someone up; measure their later success."],
        ["Delegation and trust", "Story: handed a meaty project to someone and supported without hovering."],
        ["Raising the bar in reviews", "Story: improved quality culture via code review or design review."],
      ]],
      ["Prioritization & Trade-offs", "Saying no with data.", [
        ["Saying no with data", "Story: declined a request using impact/effort evidence, kept the relationship."],
        ["Tech debt vs features", "Story: negotiated debt paydown by quantifying its drag."],
        ["Deadline triage", "Story: cut scope honestly instead of cutting quality silently."],
      ]],
      ["Customer Impact", "Working backwards from the user.", [
        ["Working backwards from the customer", "Story: started from customer pain, not from the tech."],
        ["Quantifying customer outcomes", "Story: metric moved — latency, retention, support tickets, revenue."],
        ["Handling customer escalations", "Story: owned an escalation end-to-end, fixed cause not just symptom."],
      ]],
      ["Technical Judgment", "Choices that aged well.", [
        ["Choosing boring technology", "Story: picked the proven option and justified innovation tokens."],
        ["Architecture decision records", "Story: documented context and trade-offs so the decision survived you."],
        ["Estimating and de-risking projects", "Story: front-loaded the riskiest unknown; estimate held."],
      ]],
    ],
  },
  ai: {
    num: 11,
    hue: 260,
    title: "Production AI Engineering",
    tagline: "Structured outputs, RAG evals, agent reliability, observability, guardrails, and cost control.",
    when: "AI engineer interviews and real LLM products: everything past the demo stage.",
    keyIdea: "The demo is 5% of the work. Reliability, evals, safety, and cost are the other 95%.",
    resources: [
      ["📖", "OpenAI Cookbook: Structured Outputs", "OpenAI", "https://cookbook.openai.com/examples/structured_outputs_intro"],
      ["📝", "Anthropic Tool Use Docs", "Anthropic", "https://docs.claude.com/en/docs/agents-and-tools/tool-use/overview"],
      ["📝", "RAGAS: RAG Evaluation", "RAGAS", "https://docs.ragas.io/"],
      ["📝", "OWASP Top 10 for LLM Applications", "OWASP", "https://owasp.org/www-project-top-10-for-large-language-model-applications/"],
      ["📝", "LangSmith Observability Docs", "LangChain", "https://docs.smith.langchain.com/"],
      ["📖", "Applied LLMs: A Year of Building", "O'Reilly authors", "https://applied-llms.org/"],
    ],
    subsections: [
      ["Structured Outputs & Tool Calling", "Making model output machine-reliable.", [
        ["JSON mode and schema-constrained decoding", "Grammar/schema constraints guarantee parseable output."],
        ["Function calling APIs", "Model emits tool name + JSON args; your code executes and returns results."],
        ["Tool selection and routing", "Few good tools beat many vague ones. Descriptions are prompts."],
        ["Parallel tool calls", "Independent calls batched in one turn cut latency."],
        ["Validating and repairing output", "Validate against schema; retry with the error message on failure."],
      ]],
      ["RAG Evaluation", "Proving retrieval actually works.", [
        ["Retrieval metrics (recall@k, MRR)", "Did the right chunk appear, and how high did it rank?"],
        ["Faithfulness and groundedness", "Is the answer supported by retrieved context? LLM-as-judge scoring."],
        ["Golden datasets and synthetic evals", "Curate Q-A-context triples; bootstrap with generated questions."],
        ["End-to-end RAG eval pipelines", "Score retrieval and generation separately — they fail differently."],
      ]],
      ["Agent Reliability", "Agents that don't run off the rails.", [
        ["Agent failure modes", "Loops, hallucinated tools, lost context, goal drift. Name them to catch them."],
        ["Guardrails on actions and budgets", "Step limits, spend caps, allow-listed tools, dry-run modes."],
        ["Human-in-the-loop checkpoints", "Approval gates before irreversible actions."],
        ["Tracing agent decisions", "Log every thought/tool/result step for replay and debugging."],
      ]],
      ["Prompt & Version Management", "Prompts are code — treat them like it.", [
        ["Prompt registries and versioning", "Store prompts with versions and owners, outside the code hot path."],
        ["A/B testing prompts", "Compare variants on live traffic with quality + cost metrics."],
        ["Regression testing on prompt change", "Run the eval suite before shipping any prompt edit."],
        ["Templates and variable hygiene", "Escape user input; never let users write into system prompts."],
      ]],
      ["LLM Observability", "Seeing what the model is doing in prod.", [
        ["Token, cost and latency dashboards", "Track per-feature unit economics, not just totals."],
        ["Logging completions safely", "Redact PII before storage; sample full traces."],
        ["Quality drift detection", "Score sampled prod outputs continuously; alert on drops."],
        ["User feedback loops", "Thumbs up/down + implicit signals feed the next eval set."],
      ]],
      ["Safety & Guardrails", "Defense in depth for LLM apps.", [
        ["Input and output content filtering", "Classifier layers before and after the model."],
        ["Prompt injection defenses", "Treat retrieved/user content as data, not instructions; privilege separation."],
        ["Jailbreak detection", "Detect role-play exploits and encoded payloads; log and rate-limit."],
        ["PII redaction", "Strip identifiers before the model and before the logs."],
      ]],
      ["Cost & Latency Optimization", "Unit economics of LLM features.", [
        ["Model routing and cascades", "Try the small model first; escalate on low confidence."],
        ["Caching (exact and semantic)", "Hash-match identical calls; embed-match similar ones."],
        ["Batching and streaming", "Batch offline work; stream online responses for perceived speed."],
        ["Quantization and distillation", "Smaller weights or distilled students for self-hosted serving."],
        ["Context window budgeting", "Trim, summarize, and rank context. Tokens are money."],
      ]],
    ],
  },
  cloud: {
    num: 11,
    hue: 175,
    title: "Architecture & Governance",
    tagline: "Well-Architected pillars, landing zones, cost, DR, secrets, containers, zero-trust, and migration.",
    when: "Cloud architect interviews, multi-account real-world setups, and the org-level questions seniors get.",
    keyIdea: "Cloud maturity = governance: identity, account structure, cost control, and recovery discipline.",
    resources: [
      ["📖", "AWS Well-Architected Framework", "AWS", "https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html"],
      ["📖", "Azure Well-Architected Framework", "Microsoft", "https://learn.microsoft.com/en-us/azure/well-architected/"],
      ["📝", "AWS Organizations Best Practices", "AWS", "https://docs.aws.amazon.com/organizations/latest/userguide/orgs_best-practices.html"],
      ["📝", "FinOps Framework", "FinOps Foundation", "https://www.finops.org/framework/"],
      ["📖", "Kubernetes Documentation", "CNCF", "https://kubernetes.io/docs/home/"],
      ["📝", "Azure Architecture Center", "Microsoft", "https://learn.microsoft.com/en-us/azure/architecture/"],
    ],
    subsections: [
      ["Well-Architected Pillars", "The shared vocabulary of cloud review.", [
        ["Operational excellence", "Run as code, small reversible changes, learn from failure."],
        ["Security pillar", "Identity first, defense in depth, trace everything, automate response."],
        ["Reliability pillar", "Auto-recover, scale horizontally, test recovery, manage quotas."],
        ["Performance efficiency", "Right-size, go global in minutes, use managed and serverless options."],
        ["Cost optimization", "Measure spend, match supply to demand, adopt consumption pricing."],
        ["Sustainability", "Maximize utilization, choose efficient regions and hardware."],
      ]],
      ["Landing Zones & Multi-Account", "Org structure before workloads.", [
        ["AWS Organizations and Control Tower", "Account factory + guardrails + centralized logging."],
        ["Azure management groups and subscriptions", "Hierarchy for policy inheritance and billing separation."],
        ["Account/subscription isolation strategy", "Blast-radius isolation: prod, non-prod, security, shared services."],
        ["Guardrails: SCPs and Azure Policy", "Preventive org-wide controls no workload admin can bypass."],
      ]],
      ["Cost Governance", "FinOps before the bill surprises you.", [
        ["Tagging and cost allocation", "Enforced tags make showback/chargeback possible."],
        ["Budgets and anomaly alerts", "AWS Budgets / Cost Anomaly Detection; Azure Cost Management alerts."],
        ["Savings plans and reserved capacity", "Commit to baselines; keep burst on demand."],
        ["FinOps practice", "Inform → optimize → operate loop owned jointly by eng and finance."],
      ]],
      ["Backup & Disaster Recovery", "RTO/RPO as design inputs.", [
        ["RTO and RPO targets", "How fast back up, how much data loss tolerable. Drives everything."],
        ["Backup vs snapshot vs replication", "Point-in-time copies vs continuous replicas. Test restores!"],
        ["DR strategies", "Backup-restore → pilot light → warm standby → multi-site active-active."],
        ["Cross-region failover testing", "An untested DR plan is a rumor. Game days make it real."],
      ]],
      ["Secrets & Key Management", "No credentials in code, ever.", [
        ["Secrets Manager vs Key Vault", "Managed secret storage with rotation on both clouds."],
        ["KMS envelope encryption", "Data keys encrypt data; master keys encrypt data keys."],
        ["Secret rotation", "Automate rotation; short-lived credentials beat long-lived ones."],
        ["IAM roles vs static credentials", "Instance/workload identity eliminates stored keys."],
      ]],
      ["Containers & Kubernetes", "Managed container platforms.", [
        ["ECS vs EKS vs AKS", "Opinionated AWS-native vs managed Kubernetes on either cloud."],
        ["Fargate and serverless containers", "No nodes to patch; pay per task."],
        ["Cluster autoscaling", "HPA scales pods; cluster autoscaler/Karpenter scales nodes."],
        ["Service discovery and ingress", "Services, DNS, ingress controllers, load balancer integration."],
        ["Image registries and scanning", "ECR/ACR with vulnerability scanning in the pipeline."],
      ]],
      ["Zero-Trust Networking", "Identity is the new perimeter.", [
        ["Identity-based access vs network perimeter", "Verify every request; never trust the network location."],
        ["PrivateLink and private endpoints", "Keep service traffic off the public internet."],
        ["mTLS service-to-service", "Both sides authenticate; mesh or sidecar issued certs."],
        ["Microsegmentation", "Security groups/NSGs per workload, least-privilege east-west."],
      ]],
      ["Migration Patterns", "Getting to the cloud sanely.", [
        ["The 6 Rs of migration", "Rehost, replatform, repurchase, refactor, retire, retain."],
        ["Strangler fig pattern", "Route traffic incrementally from legacy to new system."],
        ["Database migration (DMS)", "Continuous replication enables near-zero-downtime cutover."],
        ["Hybrid connectivity", "Direct Connect / ExpressRoute + VPN backup for on-prem links."],
      ]],
    ],
  },
};

// Curated resource libraries injected as panels on pages that were resource-thin.
export const resourceLibraries = {
  cs: {
    title: "Resource Library: CS Fundamentals",
    blurb: "Curated free deep-dive resources mapped to this page's sections.",
    links: [
      ["OSTEP (Operating Systems)", "https://pages.cs.wisc.edu/~remzi/OSTEP/"],
      ["CS:APP Book Site", "https://csapp.cs.cmu.edu/"],
      ["Beej's Guide to Network Programming", "https://beej.us/guide/bgnet/"],
      ["High Performance Browser Networking", "https://hpbn.co/"],
      ["Use The Index, Luke (DB indexing)", "https://use-the-index-luke.com/"],
      ["CMU 15-445 Database Systems", "https://15445.courses.cs.cmu.edu/"],
      ["Jepsen Consistency Map", "https://jepsen.io/consistency"],
      ["Preshing on Programming (concurrency)", "https://preshing.com/"],
      ["Crafting Interpreters", "https://craftinginterpreters.com/"],
      ["Brendan Gregg's Performance Site", "https://www.brendangregg.com/"],
      ["Computerphile (YouTube)", "https://www.youtube.com/user/Computerphile"],
      ["MIT 6.824 Distributed Systems", "https://pdos.csail.mit.edu/6.824/"],
      ["OWASP Cheat Sheet Series", "https://cheatsheetseries.owasp.org/"],
      ["Putting the You in CPU", "https://cpu.land/"],
    ],
  },
  bh: {
    title: "Resource Library: Behavioral Prep",
    blurb: "Direct guides, question banks, and mock-practice platforms.",
    links: [
      ["Amazon Leadership Principles", "https://www.amazon.jobs/content/en/our-workplace/leadership-principles"],
      ["Tech Interview Handbook: Behavioral", "https://www.techinterviewhandbook.org/behavioral-interview/"],
      ["STAR Technique Guide (Indeed)", "https://www.indeed.com/career-advice/interviewing/how-to-use-the-star-interview-response-technique"],
      ["interviewing.io Mock Interviews", "https://interviewing.io/mocks"],
      ["Exponent Behavioral Questions", "https://www.tryexponent.com/questions?type=behavioral"],
      ["Jeff H Sipe (YouTube, Google-focused)", "https://www.youtube.com/@jeffhsipepi"],
      ["The Manager's Path (book)", "https://www.oreilly.com/library/view/the-managers-path/9781491973882/"],
      ["Staff Engineer Stories (StaffEng)", "https://staffeng.com/stories/"],
      ["Glassdoor Interview Questions", "https://www.glassdoor.com/Interview/index.htm"],
      ["Thita Behavioral Sheet", "https://www.thita.ai/behavioral-sheet"],
    ],
  },
  cloud: {
    title: "Resource Library: AWS & Azure",
    blurb: "Official learning paths, architecture references, and community staples.",
    links: [
      ["AWS Skill Builder", "https://skillbuilder.aws/"],
      ["Microsoft Learn for Azure", "https://learn.microsoft.com/en-us/training/azure/"],
      ["AWS Architecture Center", "https://aws.amazon.com/architecture/"],
      ["Azure Architecture Center", "https://learn.microsoft.com/en-us/azure/architecture/"],
      ["AWS Whitepapers", "https://aws.amazon.com/whitepapers/"],
      ["AWS Well-Architected Labs", "https://www.wellarchitectedlabs.com/"],
      ["Azure Charts (service map)", "https://azurecharts.com/"],
      ["Open Guide to AWS", "https://github.com/open-guides/og-aws"],
      ["Last Week in AWS", "https://www.lastweekinaws.com/"],
      ["Cloud Resume Challenge", "https://cloudresumechallenge.dev/"],
      ["AWS re:Post Community", "https://repost.aws/"],
      ["FinOps Foundation", "https://www.finops.org/"],
    ],
  },
  dsa: {
    title: "Practice System: Drills & Meta-Skills",
    blurb: "The audit flagged these practice habits as missing. Use them as your weekly operating system.",
    drills: [
      "Pattern recognition drill: read 5 unseen problem statements, name the pattern in under 60 seconds each, no solving.",
      "Complexity trade-off drill: for each solved problem, state an alternative approach and why its time/space trade is worse.",
      "Edge-case checklist: empty input, single element, duplicates, negatives, overflow, sorted/reverse-sorted, max constraints.",
      "Mock communication drill: solve one problem out loud in 25 minutes — restate, plan, code, test, complexity.",
      "Re-solve queue: every bookmarked ★ problem returns in 7 days; solved-with-help returns in 3.",
    ],
    links: [
      ["NeetCode Roadmap", "https://neetcode.io/roadmap"],
      ["Striver A2Z DSA Sheet", "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/"],
      ["LeetCode Patterns (Sean Prashad)", "https://seanprashad.com/leetcode-patterns/"],
      ["CP-Algorithms", "https://cp-algorithms.com/"],
      ["Tech Interview Handbook", "https://www.techinterviewhandbook.org/"],
      ["AlgoMonster Flowchart", "https://algo.monster/flowchart"],
      ["USACO Guide", "https://usaco.guide/"],
      ["VisuAlgo (algorithm visualizer)", "https://visualgo.net/en"],
    ],
  },
};
