// Gap-coverage sections generated into each concept page. Every topic below was
// flagged as a missing/priority candidate in content-audit.md.
// Format per source key: { num, hue, title, tagline, when, keyIdea, resources, subsections }
export const gapSections = {
  sd: {
    num: 15,
    hue: 285,
    title: "Low-Level Design & Object-Oriented Design",
    tagline: "Implementation-level design: classes, modules, interfaces, object models, UML, and design patterns.",
    when: "After the high-level architecture is clear, or whenever the interviewer asks for object models, APIs, schemas, or machine-coding design.",
    keyIdea: "HLD explains how services collaborate; LLD explains how code units collaborate. Keep the boundary clear.",
    resources: [
      ["Doc", "GFG Low-Level Design Tutorial", "GeeksforGeeks", "https://www.geeksforgeeks.org/system-design/what-is-low-level-design-or-lld-learn-system-design/"],
      ["Doc", "HLD vs LLD Difference", "GeeksforGeeks", "https://www.geeksforgeeks.org/system-design/difference-between-high-level-design-and-low-level-design/"],
      ["Doc", "Object-Oriented Analysis and Design", "GeeksforGeeks", "https://www.geeksforgeeks.org/software-engineering/object-oriented-analysis-and-design/"],
      ["Doc", "SOLID Principles", "GeeksforGeeks", "https://www.geeksforgeeks.org/system-design/solid-principle-in-programming-understand-with-real-life-examples/"],
      ["Doc", "UML Introduction", "GeeksforGeeks", "https://www.geeksforgeeks.org/system-design/unified-modeling-language-uml-introduction/"],
      ["Doc", "Design Patterns", "GeeksforGeeks", "https://www.geeksforgeeks.org/system-design/software-design-patterns/"],
      ["Doc", "Refactoring Guru: Design Patterns", "RefactoringGuru", "https://refactoring.guru/design-patterns"],
    ],
    subsections: [
      ["HLD vs LLD Boundaries", "Know which level of detail the interviewer is asking for.", [
        ["High-level design scope", "Services, data flow, storage, queues, caches, scaling, and failure modes."],
        ["Low-level design scope", "Classes, interfaces, methods, object relationships, schemas, and in-process behavior."],
        ["When to switch from HLD to LLD", "Switch only after requirements, scale, and major components are clear or the interviewer asks."],
        ["API contract vs class contract", "HLD APIs define service boundaries; LLD interfaces define code boundaries."],
      ]],
      ["Object-Oriented Foundations", "The vocabulary for implementation-level design.", [
        ["Encapsulation", "Hide state behind behavior; expose stable methods instead of internal fields."],
        ["Abstraction", "Model only what the problem needs; avoid leaking implementation details."],
        ["Inheritance vs composition", "Prefer composition for flexible behavior; use inheritance for true is-a relationships."],
        ["Polymorphism", "Depend on interfaces so behavior can vary without branching everywhere."],
      ]],
      ["Design Principles", "Rules that keep low-level designs simple and change-friendly.", [
        ["SOLID principles", "Single responsibility, open-closed, Liskov substitution, interface segregation, dependency inversion."],
        ["DRY principle", "Remove duplicated knowledge, not every repeated line."],
        ["KISS principle", "Prefer the simplest design that satisfies current requirements."],
        ["YAGNI principle", "Do not add future features before there is a real requirement."],
      ]],
      ["UML & Interaction Modeling", "Use diagrams to communicate object behavior, not decorate the answer.", [
        ["Class diagrams", "Show classes, fields, methods, interfaces, inheritance, composition, and cardinality."],
        ["Sequence diagrams", "Show request order and object/service interactions over time."],
        ["Activity diagrams", "Show branching workflows such as checkout, booking, or approval flows."],
        ["State diagrams", "Show lifecycle transitions such as order, ride, payment, or ticket states."],
      ]],
      ["Design Patterns For LLD", "Use patterns as vocabulary for recurring object-design problems.", [
        ["Factory pattern", "Centralize object creation when construction varies by type or configuration."],
        ["Strategy pattern", "Swap algorithms without changing the caller."],
        ["Observer pattern", "Publish state changes to interested subscribers."],
        ["Decorator pattern", "Add behavior by wrapping an object instead of subclassing repeatedly."],
        ["State pattern", "Move state-specific behavior into separate objects instead of giant conditionals."],
      ]],
      ["Machine Coding & LLD Case Studies", "Practice turning requirements into maintainable code structure.", [
        ["Parking lot design", "Model vehicles, spots, tickets, pricing, gates, and payment flow."],
        ["Elevator system design", "Model requests, scheduling strategy, elevator state, and direction changes."],
        ["LRU cache design", "Combine a hash map with a doubly linked list for O(1) get/put."],
        ["BookMyShow / ticket booking LLD", "Model shows, seats, holds, lock expiry, booking, and payment states."],
        ["Splitwise / expense sharing LLD", "Model users, groups, expenses, balances, simplification, and settlement."],
      ]],
    ],
  },
  cs: {
    num: 7,
    hue: 330,
    title: "Languages, Runtimes & Engineering Practice",
    tagline: "Compilers, GC, serialization, distributed basics, testing, and profiling.",
    when: "Language internals questions, debugging sessions, performance interviews, senior-engineer depth.",
    keyIdea: "Code runs on layers you can inspect: compiler, runtime, OS. Learn to look one layer down.",
    resources: [
      ["📖", "Crafting Interpreters (free book)", "Bob Nystrom", "https://craftinginterpreters.com/"],
      ["📖", "CPython Internals", "Real Python", "https://realpython.com/products/cpython-internals-book/"],
      ["📝", "Protocol Buffers Docs", "Google", "https://protobuf.dev/"],
      ["📝", "Jepsen Analyses (distributed systems)", "Jepsen", "https://jepsen.io/analyses"],
      ["📝", "Flame Graphs", "Brendan Gregg", "https://www.brendangregg.com/flamegraphs.html"],
      ["🎓", "MIT 6.824 Distributed Systems", "MIT", "https://pdos.csail.mit.edu/6.824/"],
    ],
    subsections: [
      ["Compilers & Interpreters", "From source code to machine execution.", [
        ["Compilation pipeline", "Lexing (tokens) → parsing (AST) → semantic analysis (type checking) → IR (LLVM) → optimization (inlining, loop unrolling) → machine codegen."],
        ["Interpreters vs JIT compilation", "Interpreter executes bytecode/AST with low startup latency; JIT (V8 TurboFan, HotSpot C1/C2) profiles hot loops and compiles to optimized assembly with deopt guards."],
        ["Bytecode and virtual machines", "Stack-based VMs (JVM, CPython: simple instruction set, zero register allocation) vs Register-based VMs (LuaJIT: fewer instructions, faster dispatch loop)."],
        ["Static vs dynamic typing", "Static typing validates types at compile-time (optimizing memory layout); Dynamic typing validates types at runtime; Gradual typing (TypeScript, mypy) bridges ergonomics."],
        ["Linkers, loaders and ABIs", "Static linking embeds dependencies into standalone binary; Dynamic linking loads shared libraries (.so/.dll) at runtime; Symbol resolution and relocations."],
      ]],
      ["Runtimes & Garbage Collection", "How managed languages handle memory lifecycle.", [
        ["Mark-and-sweep vs generational GC", "Generational hypothesis: >95% of objects die young. Fast copying nursery collection; surviving objects promoted to tenured heap, collected less frequently."],
        ["Reference counting and cycles", "Immediate deterministic reclamation upon counter reaching zero (CPython, Swift ARC), but fails on circular references without cycle detectors or weak refs."],
        ["Stop-the-world vs concurrent GC", "Modern collectors (Go GC, Java ZGC, Shenandoah) perform root scanning and marking concurrently using read/load barriers, shrinking pauses to <1ms."],
        ["Memory leaks in managed languages", "Unwanted reachability preventing GC collection: unbounded static caches without eviction, unremoved event listeners, and thread-local variables in pooled threads."],
      ]],
      ["Serialization & Data Formats", "Moving data across network and storage boundaries safely.", [
        ["JSON vs Protobuf vs Avro", "JSON: human-readable, self-describing, but slow and bulky. Protobuf: binary, compiled schema, varints, fast for gRPC. Avro: schema-with-data, optimal for streaming/Kafka."],
        ["Schema evolution and compatibility", "Backward compatibility (new code reads old data), forward compatibility (old code reads new data); never renumber or delete existing tag fields in Protobuf."],
        ["Endianness and binary encoding", "Big-endian (most significant byte first, network byte order) vs Little-endian (least significant byte first, native x86/ARM); byte swapping overhead."],
        ["Text encodings (UTF-8)", "Variable-length (1-4 bytes), fully backward-compatible with 7-bit ASCII, self-synchronizing byte sequences; universal standard for web and APIs."],
      ]],
      ["Distributed Systems Basics", "Core principles for building resilient distributed architectures.", [
        ["Fallacies of distributed computing", "Network is unreliable, latency is non-zero, bandwidth is finite, topology changes, network is insecure; must engineer for partial failures."],
        ["Logical clocks and ordering", "Lamport timestamps establish partial causal order without synchronized physical clocks; Vector clocks detect concurrent conflicting mutations across replicas."],
        ["Idempotency and retries", "Network retries duplicate requests; Idempotency Keys (unique tokens validated in DB) guarantee identical side-effects on duplicate transmissions."],
        ["At-least-once vs exactly-once delivery", "Physical networks only guarantee at-most-once or at-least-once; 'exactly-once' is achieved via at-least-once delivery + idempotent deduplication."],
        ["CAP in practice", "PACELC theorem: If partition (P), choose Availability (A) or Consistency (C); Else (E), choose Latency (L) or Consistency (C) during normal operations."],
      ]],
      ["Testing Fundamentals", "Confidence through automated verification pyramids.", [
        ["Test pyramid", "Broad base of fast deterministic Unit tests, focused Integration tests (DB, queues, APIs), thin top layer of End-to-End synthetic tests."],
        ["Mocks, stubs and fakes", "Stub: returns canned answers. Mock: verifies expected method calls and args. Fake: working lightweight in-memory implementation (e.g. SQLite memory DB)."],
        ["Property-based testing", "Generates hundreds of randomized inputs to assert invariant system properties (e.g. reverse(reverse(x)) == x; Hypothesis, QuickCheck)."],
        ["Coverage and mutation testing", "Line coverage indicates executed lines; Mutation testing injects deliberate bugs (mutants) to verify that tests actually fail and catch regressions."],
        ["Flaky tests and determinism", "Root causes: wall-clock time/timezone dependencies, concurrency race conditions, shared database state across parallel workers, unmocked network calls."],
      ]],
      ["Performance Profiling", "Measure before optimizing and eliminate bottlenecks systematically.", [
        ["CPU profiling and flame graphs", "Sampled call-stack profilers (perf, async-profiler); Flame Graph box width corresponds directly to on-core CPU execution time."],
        ["Memory profiling and heap dumps", "Tracks allocation rate and retained memory; distinguishes shallow size (object itself) from retained size (object + reachable subgraph)."],
        ["Latency percentiles (p50/p95/p99)", "Averages hide severe tail latency; p99 latency governs user perception and dominates end-to-end latency in microservice fan-out trees."],
        ["Benchmarking pitfalls", "Flaws from JIT warmup variance, dead-code elimination, GC pauses, and Coordinated Omission (profiler pausing during server hiccups)."],
        ["Little's law and queueing intuition", "L = λW (average concurrency = arrival throughput × latency); dictates queue sizing, socket limits, and worker thread pool capacity."],
      ]],
    ],
  },
  bh: {
    num: 6,
    hue: 25,
    title: "Competency Deep Dives",
    tagline: "The eight competencies interviewers actually probe — each needs a prepared story.",
    when: "Any behavioral round: Amazon LPs, Google GCA, Meta signals, startup culture-fit screens.",
    keyIdea: "One strong, true, quantified story per competency beats ten generic ones.",
    resources: [
      ["📝", "Amazon Leadership Principles (official)", "Amazon", "https://www.amazon.jobs/content/en/our-workplace/leadership-principles"],
      ["📖", "Behavioral Guide", "Tech Interview Handbook", "https://www.techinterviewhandbook.org/behavioral-interview/"],
      ["📝", "STAR Method Guide", "Indeed", "https://www.indeed.com/career-advice/interviewing/how-to-use-the-star-interview-response-technique"],
      ["🎥", "Behavioral Mock Interviews", "interviewing.io", "https://interviewing.io/mocks"],
    ],
    subsections: [
      ["Navigating Ambiguity", "Acting well with incomplete information.", [
        ["Acting with incomplete information", "Framework: Quantify confidence threshold (Jeff Bezos 70% rule), bound blast radius via feature flags and canary deployments, and establish explicit metrics for automated rollback."],
        ["Defining scope when none is given", "Framework: Deconstruct ambiguity into personas, core user stories, non-functional latency/throughput constraints, and an iterative phased milestone roadmap."],
        ["Communicating assumptions", "Framework: State assumptions and risk vectors explicitly in an RFC/Architecture Decision Record (ADR); schedule weekly alignment checkpoints to validate against real data."],
      ]],
      ["Ownership & Initiative", "Going beyond your job description.", [
        ["Going beyond your role", "Story: Stepped outside team boundaries to investigate cross-team latency spikes, diagnosing upstream partition skew and authoring an automated pipeline fix."],
        ["Long-term thinking vs quick wins", "Story: Pushed back against fragile hardcoded routing patches; delivered an extensible metadata-driven dynamic routing layer that scaled to 200+ enterprise tenants."],
        ["Owning outcomes after handoff", "Story: Monitored telemetry, error rates, and on-call runbooks for 60 days post-launch; mentored client operations team to ensure sustained SLA adherence."],
      ]],
      ["Conflict & Influence", "Disagreement handled like an adult.", [
        ["Disagreeing with a manager", "Story: Disagree and commit. Voiced technical risks of NoSQL migration with empirical ACID transaction benchmark data in private 1:1; once decided, committed 100% to flawless execution."],
        ["Influencing without authority", "Story: Built a working end-to-end prototype and automated performance benchmark suite to align two deadlocked engineering teams around gRPC adoption."],
        ["Driving alignment across teams", "Story: Brokered an enterprise search unification agreement between 4 independent product divisions by presenting a unified multi-tenant architecture with 60% cost reduction."],
      ]],
      ["Failure & Learning", "Real failure, real lesson, real change.", [
        ["Telling a real failure story", "Story: Errant migration script triggered an 11-minute production auth outage. Took 100% personal ownership, published transparent status updates, and added CI lock analysis."],
        ["Post-mortems and prevention", "Story: Facilitated a blameless post-mortem analyzing the five whys of an outage; implemented permanent automated guards, canary gates, and runbook playbooks."],
        ["Receiving hard feedback", "Story: Received feedback on overly abrasive code review comments. Transitioned to inquisitive coaching ('What failure modes occur if X fails?'), improving team trust."],
      ]],
      ["Mentoring & Growth", "Multiplying other engineers.", [
        ["Onboarding and coaching juniors", "Story: Mentored an SDE-1 through weekly system design pairing, guided their delivery of a critical payment webhook gateway, and supported their promotion to SDE-2."],
        ["Delegation and trust", "Story: Delegated architectural ownership of a mission-critical billing refactor to a mid-level engineer, providing strategic scaffolding while trusting their execution."],
        ["Raising the bar in reviews", "Story: Instituted structured RFC review templates and automated linting/coverage gates in CI, uplifting engineering velocity and reducing regression bugs by 64%."],
      ]],
      ["Prioritization & Trade-offs", "Saying no with data.", [
        ["Saying no with data", "Story: Declined an executive request to add un-cached real-time dashboard analytics by showing load test data proving it would degrade core checkout latency."],
        ["Tech debt vs features", "Story: Negotiated a dedicated 20% sprint budget for tech debt remediation by quantifying that flaky tests and brittle legacy code cost 35 engineering hours per week."],
        ["Deadline triage", "Story: 6 weeks before contractual deadline, descoped non-essential P2 features and parallelized workstreams to ship core payment capabilities with 100% financial accuracy."],
      ]],
      ["Customer Impact", "Working backwards from the user.", [
        ["Working backwards from the customer", "Story: Started with user friction logs showing 22% authentication drop-offs; replaced legacy OAuth flow with RFC 8628 device flow, slashing drop-offs to 1.5%."],
        ["Quantifying customer outcomes", "Story: Solved high-latency mobile API waterfalls in Latin America, dropping p99 latency from 4.8s to 340ms and driving a 22% increase in user retention."],
        ["Handling customer escalations", "Story: Personally debugged intermittent webhook dropouts for an enterprise customer, diagnosing TCP window exhaustion and authoring an adaptive backoff client SDK."],
      ]],
      ["Technical Judgment", "Choices that aged well.", [
        ["Choosing boring technology", "Story: Chose proven PostgreSQL over trendy NoSQL for a high-throughput ledger; avoided distributed transaction complexity and met all SLA targets easily."],
        ["Architecture decision records", "Story: Established repository-tracked ADRs detailing context, evaluated alternatives, and trade-offs, enabling architectural decisions to endure team rotations."],
        ["Estimating and de-risking projects", "Story: Identified third-party integration latency as the biggest project risk; built a proof-of-concept spike in sprint 1 to de-risk timeline estimates."],
      ]],
    ],
  },
  ai: {
    num: 11,
    hue: 260,
    title: "Production AI Engineering",
    tagline: "Structured outputs, RAG evals, agent reliability, observability, guardrails, and cost control.",
    when: "AI engineer interviews and real LLM products: everything past the demo stage.",
    keyIdea: "The demo is 5% of the work. Reliability, evals, safety, and cost are the other 95%.",
    resources: [
      ["📖", "OpenAI Cookbook: Structured Outputs", "OpenAI", "https://cookbook.openai.com/examples/structured_outputs_intro"],
      ["📝", "Anthropic Tool Use Docs", "Anthropic", "https://docs.claude.com/en/docs/agents-and-tools/tool-use/overview"],
      ["📝", "RAGAS: RAG Evaluation", "RAGAS", "https://docs.ragas.io/"],
      ["📝", "OWASP Top 10 for LLM Applications", "OWASP", "https://owasp.org/www-project-top-10-for-large-language-model-applications/"],
      ["📝", "LangSmith Observability Docs", "LangChain", "https://docs.smith.langchain.com/"],
      ["📖", "Applied LLMs: A Year of Building", "O'Reilly authors", "https://applied-llms.org/"],
    ],
    subsections: [
      ["Structured Outputs & Tool Calling", "Making model output machine-reliable.", [
        ["JSON mode and schema-constrained decoding", "CFG / Regex logit masking at each token step guarantees 100% valid JSON schema compliance at generation time with zero parsing errors."],
        ["Function calling APIs", "Model emits tool name and JSON args matching OpenAPI schemas; client runtime executes and returns results as tool-role messages for final synthesis."],
        ["Tool selection and routing", "Keep tool definitions minimal and discriminative; tool descriptions are prompts guiding the model on boundaries, inputs, and operational side effects."],
        ["Parallel tool calls", "Independent tool calls batched in a single turn reduce multi-turn roundtrip latency by up to 75% for read-heavy agent workflows."],
        ["Validating and repairing output", "Pydantic validation with automated repair loops feeding execution tracebacks and validation errors back to the model for iterative correction."],
      ]],
      ["RAG Evaluation", "Proving retrieval actually works.", [
        ["Retrieval metrics (recall@k, MRR)", "Recall@K measures chunk presence in top-K; Mean Reciprocal Rank (MRR) evaluates ranking position of first relevant chunk across evaluation queries."],
        ["Faithfulness and groundedness", "Evaluates whether claims in generated answer are mathematically supported by retrieved context via LLM-as-a-judge (Ragas framework)."],
        ["Golden datasets and synthetic evals", "Curate 50-200 ground-truth Q-A-Context triples; bootstrap adversarial edge cases with synthetic question generation across diverse document domains."],
        ["End-to-end RAG eval pipelines", "Decouple retrieval evaluation (Hit Rate, MRR, Context Relevance) from generation evaluation (Faithfulness, Groundedness) to isolate pipeline failures."],
      ]],
      ["Agent Reliability", "Agents that don't run off the rails.", [
        ["Agent failure modes", "Infinite tool calling loops, hallucinated arguments, context window overflow, and goal drift. Mitigate with hard step caps, timeouts, and state checkpoints."],
        ["Guardrails on actions and budgets", "Step limits (max 10 iterations), per-session token/spend budgets, strict tool allowlists, and dry-run execution modes for mutations."],
        ["Human-in-the-loop checkpoints", "Mandatory human review and approval gates before executing high-blast-radius actions (database writes, refunds, customer communications)."],
        ["Tracing agent decisions", "OpenTelemetry-compatible step-by-step tracing (Langfuse, LangSmith) capturing thoughts, tool calls, return values, latency, and token cost."],
      ]],
      ["Prompt & Version Management", "Prompts are code — treat them like it.", [
        ["Prompt registries and versioning", "Version control prompts with semantic versioning and metadata outside the application hot path; track prompt lineage across releases."],
        ["A/B testing prompts", "Route live traffic between prompt variants; measure statistical significance on downstream completion rates, user retention, and token cost."],
        ["Regression testing on prompt change", "Automated CI/CD gates running regression eval suites on golden datasets before merging any prompt modification."],
        ["Templates and variable hygiene", "Strict XML/JSON input escaping; never concatenate raw untrusted user input directly into system prompts or developer instructions."],
      ]],
      ["LLM Observability", "Seeing what the model is doing in prod.", [
        ["Token, cost and latency dashboards", "Granular real-time telemetry attributing input/output token usage, prompt cache hits, and dollar cost down to individual features and tenants."],
        ["Logging completions safely", "Automated PII scrubbing (Presidio) before logging; sample full execution traces to data lakes with strict retention policies."],
        ["Quality drift detection", "Continuous sampling of production interactions; run automated LLM judges to detect sudden drops in groundedness or user satisfaction."],
        ["User feedback loops", "Explicit (thumbs up/down, corrections) and implicit (copy-paste, dwell time) user telemetry feeding future evaluation and fine-tuning datasets."],
      ]],
      ["Safety & Guardrails", "Defense in depth for LLM apps.", [
        ["Input and output content filtering", "Multi-layered guardrail classifiers (Llama Guard, NeMo Guardrails) evaluating safety and toxicity before model call and before returning response."],
        ["Prompt injection defenses", "Enforce privilege separation: delimit untrusted external text in isolated XML tags; instruct model to treat retrieved data purely as passive text."],
        ["Jailbreak detection", "Detect adversarial prefix injection, role-play exploits, and Base64-encoded payloads; log and apply aggressive rate limits to offending tenants."],
        ["PII redaction", "Mask credit card numbers, SSNs, and personal credentials on client side prior to egressing data outside the organizational perimeter."],
      ]],
      ["Cost & Latency Optimization", "Unit economics of LLM features.", [
        ["Model routing and cascades", "Route incoming requests to smaller cheap models (GPT-4o-mini, Haiku); escalate to frontier models only on low confidence or high complexity."],
        ["Caching (exact and semantic)", "Exact hash caching for identical prompt strings; vector embedding semantic caching (>=0.95 cosine similarity) for common queries."],
        ["Batching and streaming", "Server-Sent Events (SSE) for low TTFT online queries; asynchronous batch API processing for offline jobs at 50% discount."],
        ["Quantization and distillation", "AWQ / GPTQ 4-bit weight quantization and knowledge distillation from frontier models into specialized 8B/70B models for on-prem serving."],
        ["Context window budgeting", "Dynamic context truncation, hierarchical summarization, and vector retrieval filtering to prevent prompt bloat and 'Lost in the Middle' degradation."],
      ]],
    ],
  },
  cloud: {
    num: 11,
    hue: 175,
    title: "Architecture & Governance",
    tagline: "Well-Architected pillars, landing zones, cost, DR, secrets, containers, zero-trust, and migration.",
    when: "Cloud architect interviews, multi-account real-world setups, and the org-level questions seniors get.",
    keyIdea: "Cloud maturity = governance: identity, account structure, cost control, and recovery discipline.",
    resources: [
      ["📖", "AWS Well-Architected Framework", "AWS", "https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html"],
      ["📖", "Azure Well-Architected Framework", "Microsoft", "https://learn.microsoft.com/en-us/azure/well-architected/"],
      ["📝", "AWS Organizations Best Practices", "AWS", "https://docs.aws.amazon.com/organizations/latest/userguide/orgs_best-practices.html"],
      ["📝", "FinOps Framework", "FinOps Foundation", "https://www.finops.org/framework/"],
      ["📖", "Kubernetes Documentation", "CNCF", "https://kubernetes.io/docs/home/"],
      ["📝", "Azure Architecture Center", "Microsoft", "https://learn.microsoft.com/en-us/azure/architecture/"],
    ],
    subsections: [
      ["Well-Architected Pillars", "The shared vocabulary of cloud review.", [
        ["Operational excellence", "Manage infrastructure as code, make frequent small reversible changes, anticipate failures, and conduct blameless post-mortems."],
        ["Security pillar", "Identity-centric defense in depth, zero-trust network boundaries, ubiquitous encryption at rest and in transit, and automated incident response."],
        ["Reliability pillar", "Multi-AZ and multi-region deployment topologies, automated failure recovery, horizontal elasticity, distributed rate limiting, and regular DR drills."],
        ["Performance efficiency", "Right-size compute instance families, leverage serverless event-driven architectures, deploy edge caching globally, and benchmark continuously."],
        ["Cost optimization", "Implement FinOps governance, eliminate idle resources, leverage Reserved Instances and Savings Plans, and optimize storage lifecycle tiering."],
        ["Sustainability", "Maximize hardware utilization, adopt energy-efficient ARM-based AWS Graviton processors, and scale down non-production workloads during off-peak hours."],
      ]],
      ["Landing Zones & Multi-Account", "Org structure before workloads.", [
        ["AWS Organizations and Control Tower", "Automated account factory, centralized IAM Identity Center SSO, consolidated billing, and continuous compliance monitoring."],
        ["Azure management groups and subscriptions", "Hierarchical management structure providing unified policy inheritance, role assignments, and cost boundaries across hundreds of subscriptions."],
        ["Account/subscription isolation strategy", "Isolate environments into dedicated accounts (Prod, Staging, Dev, Shared Services, Security Tooling) to strictly bound blast radiuses."],
        ["Guardrails: SCPs and Azure Policy", "Enforce mandatory preventive guardrails (e.g. restrict regions, mandate encryption, deny public S3 buckets) that account administrators cannot disable."],
      ]],
      ["Cost Governance", "FinOps before the bill surprises you.", [
        ["Tagging and cost allocation", "Enforce mandatory resource tagging (CostCenter, Environment, Owner) to enable granular cost allocation showback and chargeback accounting."],
        ["Budgets and anomaly alerts", "AWS Budgets and Azure Cost Management with automated ML anomaly detection alerting teams before cloud overruns occur."],
        ["Savings plans and reserved capacity", "Analyze 90-day compute baseline usage; commit to 1-3 year Compute Savings Plans for up to 72% discount while keeping burst on-demand."],
        ["FinOps practice", "Cross-functional Inform -> Optimize -> Operate framework aligning engineering, finance, and product teams on unit economics (cost per transaction)."],
      ]],
      ["Backup & Disaster Recovery", "RTO/RPO as design inputs.", [
        ["RTO and RPO targets", "Recovery Time Objective (maximum tolerable downtime) and Recovery Point Objective (maximum tolerable data loss) determine architecture and budget."],
        ["Backup vs snapshot vs replication", "Point-in-time snapshots (S3-backed EBS snapshots) vs continuous block-level or database streaming replication (Aurora Global Database)."],
        ["DR strategies", "Backup & Restore (high RTO/RPO, lowest cost) -> Pilot Light (minimal core running) -> Warm Standby (scaled-down replica) -> Multi-Site Active-Active (zero RTO/RPO)."],
        ["Cross-region failover testing", "Scheduled Game Day disaster simulation drills injecting regional partition failures (Chaos Engineering) to validate DNS failover and database promotion."],
      ]],
      ["Secrets & Key Management", "No credentials in code, ever.", [
        ["Secrets Manager vs Key Vault", "Centralized, encrypted secret storage providing automated password rotation via Lambda/Functions, fine-grained IAM access, and audit logging."],
        ["KMS envelope encryption", "Two-tier key hierarchy: customer master keys (KMS CMK) protect data encryption keys (DEK); data is encrypted locally using the DEK."],
        ["Secret rotation", "Automated continuous rotation of database credentials and API tokens every 30-90 days with zero application downtime using dual-credential buffering."],
        ["IAM roles vs static credentials", "Workload Identity (AWS IAM Roles for Service Accounts - IRSA, Azure Workload Identity) eliminating static API keys and service principal secrets."],
      ]],
      ["Containers & Kubernetes", "Managed container platforms.", [
        ["ECS vs EKS vs AKS", "AWS ECS provides simplified native container management; AWS EKS and Azure AKS provide managed CNCF-compliant Kubernetes for complex cloud-native architectures."],
        ["Fargate and serverless containers", "Run containers without managing virtual machine node instances; AWS and Azure handle OS patching, security hardening, and compute capacity."],
        ["Cluster autoscaling", "Horizontal Pod Autoscaler (HPA) scales replica counts on metrics; Karpenter or Cluster Autoscaler provisions optimal EC2 instance types dynamically in seconds."],
        ["Service discovery and ingress", "Kubernetes Service abstractions, AWS Cloud Map, and Ingress Controllers (AWS ALB Ingress Controller) managing external L7 traffic routing."],
        ["Image registries and scanning", "Amazon ECR and Azure ACR with automated vulnerability scanning (CVE checks on push), immutable image tags, and cross-region replication."],
      ]],
      ["Zero-Trust Networking", "Identity is the new perimeter.", [
        ["Identity-based access vs network perimeter", "Authenticate and authorize every transaction explicitly; never trust requests based solely on origin IP or internal network location."],
        ["PrivateLink and private endpoints", "Secure private connectivity between VPCs/VNets and cloud services over internal backbones without traversing the public internet or requiring NAT gateways."],
        ["mTLS service-to-service", "Mutual Transport Layer Security (mTLS) with cryptographically verified identity certificates between all internal microservice calls using a service mesh (Istio, Linkerd)."],
        ["Microsegmentation", "Granular host-level and subnet-level security groups enforcing least-privilege traffic flow between individual workload tiers (east-west traffic control)."],
      ]],
      ["Migration Patterns", "Getting to the cloud sanely.", [
        ["The 6 Rs of migration", "Rehost (lift-and-shift), Replatform (lift-tinker-and-shift to managed DB), Repurchase (drop-and-shop to SaaS), Refactor (cloud-native rewrite), Retire, Retain."],
        ["Strangler fig pattern", "Incrementally replace legacy monolith components by routing specific API endpoints to newly deployed cloud microservices via an API Gateway."],
        ["Database migration (DMS)", "AWS Database Migration Service with Change Data Capture (CDC) replicating ongoing transactions to minimize cutover downtime to seconds."],
        ["Hybrid connectivity", "Dual-redundant AWS Direct Connect / Azure ExpressRoute circuits paired with backup IPSec VPN tunnels for high-availability corporate datacenter interconnect."],
      ]],
    ],
  },
};

// Curated resource libraries injected as panels on pages that were resource-thin.
export const resourceLibraries = {
  cs: {
    title: "Resource Library: CS Fundamentals",
    blurb: "Curated free deep-dive resources mapped to this page's sections.",
    links: [
      ["OSTEP (Operating Systems)", "https://pages.cs.wisc.edu/~remzi/OSTEP/"],
      ["CS:APP Book Site", "https://csapp.cs.cmu.edu/"],
      ["Beej's Guide to Network Programming", "https://beej.us/guide/bgnet/"],
      ["High Performance Browser Networking", "https://hpbn.co/"],
      ["Use The Index, Luke (DB indexing)", "https://use-the-index-luke.com/"],
      ["CMU 15-445 Database Systems", "https://15445.courses.cs.cmu.edu/"],
      ["Jepsen Consistency Map", "https://jepsen.io/consistency"],
      ["Preshing on Programming (concurrency)", "https://preshing.com/"],
      ["Crafting Interpreters", "https://craftinginterpreters.com/"],
      ["Brendan Gregg's Performance Site", "https://www.brendangregg.com/"],
      ["Computerphile (YouTube)", "https://www.youtube.com/user/Computerphile"],
      ["MIT 6.824 Distributed Systems", "https://pdos.csail.mit.edu/6.824/"],
      ["OWASP Cheat Sheet Series", "https://cheatsheetseries.owasp.org/"],
      ["Putting the You in CPU", "https://cpu.land/"],
    ],
  },
  bh: {
    title: "Resource Library: Behavioral Prep",
    blurb: "Direct guides, question banks, and mock-practice platforms.",
    links: [
      ["Amazon Leadership Principles", "https://www.amazon.jobs/content/en/our-workplace/leadership-principles"],
      ["Tech Interview Handbook: Behavioral", "https://www.techinterviewhandbook.org/behavioral-interview/"],
      ["STAR Technique Guide (Indeed)", "https://www.indeed.com/career-advice/interviewing/how-to-use-the-star-interview-response-technique"],
      ["interviewing.io Mock Interviews", "https://interviewing.io/mocks"],
      ["Exponent Behavioral Questions", "https://www.tryexponent.com/questions?type=behavioral"],
      ["Jeff H Sipe (YouTube, Google-focused)", "https://www.youtube.com/@jeffhsipepi"],
      ["The Manager's Path (book)", "https://www.oreilly.com/library/view/the-managers-path/9781491973882/"],
      ["Staff Engineer Stories (StaffEng)", "https://staffeng.com/stories/"],
      ["Glassdoor Interview Questions", "https://www.glassdoor.com/Interview/index.htm"],
      ["Dan Croitor (Behavioral Interview Prep)", "https://www.youtube.com/@DanCroitor"],
    ],
  },
  cloud: {
    title: "Resource Library: AWS & Azure",
    blurb: "Official learning paths, architecture references, and community staples.",
    links: [
      ["AWS Skill Builder", "https://skillbuilder.aws/"],
      ["Microsoft Learn for Azure", "https://learn.microsoft.com/en-us/training/azure/"],
      ["AWS Architecture Center", "https://aws.amazon.com/architecture/"],
      ["Azure Architecture Center", "https://learn.microsoft.com/en-us/azure/architecture/"],
      ["AWS Whitepapers", "https://aws.amazon.com/whitepapers/"],
      ["AWS Well-Architected Labs", "https://www.wellarchitectedlabs.com/"],
      ["Azure Charts (service map)", "https://azurecharts.com/"],
      ["Open Guide to AWS", "https://github.com/open-guides/og-aws"],
      ["Last Week in AWS", "https://www.lastweekinaws.com/"],
      ["Cloud Resume Challenge", "https://cloudresumechallenge.dev/"],
      ["AWS re:Post Community", "https://repost.aws/"],
      ["FinOps Foundation", "https://www.finops.org/"],
    ],
  },
  dsa: {
    title: "Practice System: Drills & Meta-Skills",
    blurb: "The audit flagged these practice habits as missing. Use them as your weekly operating system.",
    drills: [
      "Pattern recognition drill: read 5 unseen problem statements, name the pattern in under 60 seconds each, no solving.",
      "Complexity trade-off drill: for each solved problem, state an alternative approach and why its time/space trade is worse.",
      "Edge-case checklist: empty input, single element, duplicates, negatives, overflow, sorted/reverse-sorted, max constraints.",
      "Mock communication drill: solve one problem out loud in 25 minutes — restate, plan, code, test, complexity.",
      "Re-solve queue: every bookmarked ★ problem returns in 7 days; solved-with-help returns in 3.",
    ],
    links: [
      ["Local DSA Tutorial", "DSA_Tutorial/index.html"],
      ["NeetCode Roadmap", "https://neetcode.io/roadmap"],
      ["Striver A2Z DSA Sheet", "https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/"],
      ["LeetCode Patterns (Sean Prashad)", "https://seanprashad.com/leetcode-patterns/"],
      ["CP-Algorithms", "https://cp-algorithms.com/"],
      ["Tech Interview Handbook", "https://www.techinterviewhandbook.org/"],
      ["AlgoMonster Flowchart", "https://algo.monster/flowchart"],
      ["USACO Guide", "https://usaco.guide/"],
      ["VisuAlgo (algorithm visualizer)", "https://visualgo.net/en"],
    ],
  },
};
